### ISSUE TITLE
Just an idea: denote for attachments

### ISSUE THREAD

**Issue by Ypot** [protesilaos/denote#1]
`If you think this is something you might use, but disagree with some of its decisions, now is the best time to act. `

Just in case this idea could be useful:
I use attached or linked local files for adding multimedia (jpg, pdf, etc) or references (saved html, podcasts, etc) to my org notes. 
These multimedia files are in a folder almost kaotically. 
To sort those files in the way you've described could give to them a new dimension.

Thanks for elisping!

**Comment by protesilaos** [comment]
Thanks @Ypot!

> Just in case this idea could be useful:

Yes, it is useful.

> I use attached or linked local files for adding multimedia (jpg, pdf,
> etc) or references (saved html, podcasts, etc) to my org notes.  These
> multimedia files are in a folder almost kaotically.  To sort those
> files in the way you've described could give to them a new dimension.

I already do this locally for my multimedia, but I don't have any Elisp
for it.

I am now trying to think how it could be done.  We could have a command,
say, `denote-dired-rename` which only changes the name of the file at
point.  It will prompt for TITLE and KEYWORDS, just like `denote` and
`denote-org-capture`, but it will also ask for a file type extension:
jpd, pdf, and others can be available as completion candidates.

Unlike the other commands, `denote-dired-rename` will not create a
"note" per se.

What do you think?

[ Maybe a better name is `denote-dired-rename-non-note` or something to
  make it clear we are not operating on notes. ]

Though we need to be careful not to go very far with this idea, as it is
not directly connected to the note-taking goal.

> Thanks for elisping!

You are welcome!

**Comment by Ypot** [comment]
Not sure! I just thought attachments could be benefited with an analogous naming and listing. But it's more like a brainstormed idea that could fit in your project if it suits you.

For completion candidates I would find more useful keywords than extensions (why bother with existing extensions?).

Best regards :-)

**Comment by protesilaos** [comment]
Hello again!  Here is a prototype (I made some other changes---diff
below):

```elisp
(defun denote-dired-rename-file (title keywords)
  "Return path to new file with TITLE and KEYWORDS."
  (interactive
   (list
    (denote--title-prompt)
    (denote--keywords-prompt)))
  (let* ((file (dired-get-filename))
         (dir (file-name-directory file))
         (old-name (file-name-nondirectory file))
         (extension (file-name-extension file t))
         (new-name (denote--format-file
                    dir
                    (format-time-string denote--id)
                    keywords
                    (denote--sluggify title)
                    extension)))
    (when (y-or-n-p
           (format "Rename %s to %s?"
                   (propertize old-name 'face 'error)
                   (propertize (file-name-nondirectory new-name) 'face 'success)))
      (rename-file old-name new-name nil)
      (revert-buffer))))
```

It uses the standard prompts for `TITLE` and `KEYWORDS` and converts
them to a familiar Denote path.  The file type extension is read from
the underlying file.  So if you are renaming a .pdf it stays a .pdf, if
it is an .mp3 it remains that way, and so on.

The renaming only happens relative to the current directory.  It does
not move the file between directories.  I think this is consistent with
the task, which basically is "Give me a Denote-style file name".

The diff:

```diff
 denote-dired.el | 30 ++++++++++++++++++++++++++++++
 denote.el       | 14 +++++++++-----
 2 files changed, 39 insertions(+), 5 deletions(-)

diff --git a/denote-dired.el b/denote-dired.el
index 3c5ca05..81b7058 100644
--- a/denote-dired.el
+++ b/denote-dired.el
@@ -34,11 +34,41 @@ ;;; Commentary:
 ;;; Code:
 
 (require 'denote)
+(require 'dired)
 
 (defgroup denote-dired ()
   "Integration between Denote and Dired."
   :group 'denote)
 
+;;;; Commands
+
+(defun denote-dired-rename-file (title keywords)
+  "Rename file at point to new file with TITLE and KEYWORDS.
+This command is intended to complement note-taking, such as by
+renaming attachments that the user adds to their notes."
+  (interactive
+   (list
+    (denote--title-prompt)
+    (denote--keywords-prompt)))
+  (let* ((file (dired-get-filename))
+         (dir (file-name-directory file))
+         (old-name (file-name-nondirectory file))
+         (extension (file-name-extension file t))
+         (new-name (denote--format-file
+                    dir
+                    (format-time-string denote--id)
+                    keywords
+                    (denote--sluggify title)
+                    extension)))
+    (when (y-or-n-p
+           (format "Rename %s to %s?"
+                   (propertize old-name 'face 'error)
+                   (propertize (file-name-nondirectory new-name) 'face 'success)))
+      (rename-file old-name new-name nil)
+      (revert-buffer))))
+
+;;;; Extra fontification
+
 (defvar dired-font-lock-keywords)
 
 (defvar denote-dired-original-keywords dired-font-lock-keywords
diff --git a/denote.el b/denote.el
index 83da40c..f4451ff 100644
--- a/denote.el
+++ b/denote.el
@@ -112,7 +112,7 @@ (defconst denote--keyword-regexp "\\(--\\)\\([0-9A-Za-z_+]*\\)\\(--\\)"
   "Regular expression to match `denote-keywords'.")
 
 (defconst denote--file-regexp
-  (concat denote--id-regexp denote--keyword-regexp "\\(.*\\)\\.org")
+  (concat denote--id-regexp denote--keyword-regexp "\\(.*\\)\\..*")
   "Regular expression to match file names from `denote-new-note'.")
 
 (defconst denote--punctuation-regexp "[][{}!@#$%^&*()_=+'\"?,.\|;:~`‘’“”]*"
@@ -272,14 +272,18 @@ (defun denote--keywords-add-to-history (keywords)
 
 ;;;; New note
 
-(defun denote--format-file (path id keywords slug)
+(defun denote--format-file (path id keywords slug &optional extension)
   "Format file name.
 PATH, ID, KEYWORDS, SLUG are expected to be supplied by `denote'
-or equivalent: they will all be converted into a single string."
+or equivalent: they will all be converted into a single string.
+
+Optional EXTENSION is the file type extension.  Use .org if none
+is specified."
   (let ((kws (if denote-infer-keywords
                  (denote--keywords-combine keywords)
-               keywords)))
-    (format "%s%s--%s--%s.org" path id kws slug)))
+               keywords))
+        (ext (or extension ".org")))
+    (format "%s%s--%s--%s%s" path id kws slug ext)))
 
 (defun denote--file-meta-header (title date keywords filename id)
   "Front matter for new notes.
```

**Comment by protesilaos** [comment]
I made some changes early today to how renaming works.  The current functionality is described here: https://protesilaos.com/emacs/denote#h:532e8e2a-9b7d-41c0-8f4b-3c5cbb7d4dca

**Comment by Ypot** [comment]
I am receiving this message:
`dired-move-to-filename: No file on this line`

Maybe I should try without customizations.

**Comment by protesilaos** [comment]
> Offtopic: I am trying to send you what seems to be a "typo". 

Fixed.  Thank you!

**Comment by protesilaos** [comment]
I am closing this issue now as Denote supports the idea of renaming other files.
