### ISSUE TITLE
"Identifier" search regexp fails for TOML front-matter

### ISSUE THREAD

**Issue by kaushalmodi** [protesilaos/denote#10]
Hello,

I am afraid that this fails when using TOML front-matter:

https://github.com/protesilaos/denote/blob/f91d2472c3c1c856c239cb0da4f2205093437c0c/denote-link.el#L103-L104

We will need to look for `:` or `=`, with optional space before `=`.

Sample TOML format output

```
+++
title      = "testtoml"
date       = 2022-06-11T11:49:10-04:00
tags       = ["test"]
identifier = "20220611T114910"
+++
```

---

I was actually looking into it to see if I can live with just the ID property when using Org front-matter (Ref https://github.com/protesilaos/denote/issues/8). 

Do you think this is the only thing we'll need to tweak if I want to have Org front-matter without the `identifier` keyword?

```
:PROPERTIES:
:ID: 20220611T114436
:END:
#+title:    test
#+date:     [2022-06-11 Sat 11:44]
#+filetags: test
```

Or do you plan to deeply bake in the reliance on `#+identifier` / `identifier:` / `identifier =` matches?

**Comment by protesilaos** [comment]
> We will need to look for : or =, with optional space before =.

Oh, of course!  Sorry about that.  Will fix it right away.

> Or do you plan to deeply bake in the reliance on #+identifier / identifier: / identifier = matches?

I think this is open to discussion, given that we still are at the point where we can make breaking changes.

**Comment by protesilaos** [comment]
The `"^\\(#\\+\\)?\\(identifier\\)\\([\s\t]+\\)?[:=]\\([\s\t]+?\\)?\"?\\([0-9T]+\\)\"?"` matches all of the following with `M-x re-builder`.  Is there some other permutation we need to consider?

```
identifier = "20220611T114910"
identifier= 20220611T114910
identifier=20220611T114910
identifier= "20220611T114910"
identifier     ="20220611T114910"



identifier : "20220611T114910"
identifier: 20220611T114910
identifier:20220611T114910
identifier: "20220611T114910"
identifier     :"20220611T114910"
```

**Comment by kaushalmodi** [comment]
>  Is there some other permutation we need to consider?

Nope this covers (more than) everything!

---

(more than): Few illegal cases like `identifier= 20220611T114910` and `identifier=20220611T114910` too. But that's OK.

---

Regexp suggestion:

```
"\\bidentifier\\s-*[:=]\\s-*\"?\\([0-9T]+\\)"
```

![image](https://user-images.githubusercontent.com/3578197/173195767-a4a63191-51ba-4042-923d-bfbddc87f0b9.png)

**Comment by protesilaos** [comment]
> Regexp suggestion:

Vastly superior!  Thanks!

I guess now we need to abstract the "indentifier" part, right?  That gives the user maximum flexibility.

**Comment by kaushalmodi** [comment]
Suggestion 2:

```
"^.?.?\\b\\(identifier\\|ID\\)\\s-*[:=]\\s-*\"?\\([0-9T]+\\)"
```

![image](https://user-images.githubusercontent.com/3578197/173195895-6ab8e0fd-26e6-44d2-a2fc-0a59df0f55e4.png)

**Comment by kaushalmodi** [comment]
I think `^.?.?\\b\\` will be good enough to avoid any false matches.

**Comment by protesilaos** [comment]
Very wel!!  Since you wrote it, do you want to submit a PR (or send a patch)?  If you are on mobile, I can commit with you as the author (if you want).

**Comment by kaushalmodi** [comment]
I haven't tested it properly and won't have time to do so until tonight (~10 hrs from now).

But I can create a PR and let you decide. If the PR is still open after I am done testing, and I need to update it, I'll do so, else will create another PR

**Comment by protesilaos** [comment]
Okay, thank you!  Will wait then.

**Comment by kaushalmodi** [comment]
Closing this as it was fixed by https://github.com/protesilaos/denote/pull/11.

**Comment by protesilaos** [comment]
Thank you!
