### ISSUE TITLE
Denote links are not unique

### ISSUE THREAD

**Issue by felipebalbi** [protesilaos/denote#105]
Hi Prot,

I have just (finally) completed my conversion from `org-roam` to `denote`. In order to do that, I have heavily relied on `denote-dired-rename-marked-files`, then for each note I've manually corrected `+filetags` and called `denote-rename-file` to update the tags on the file name.

To my surprise, `denote` ended up using current timestamp instead of reusing the original one from `org-roam`. That's not really a big problem, anyway, as git history can give me some idea of when the file was originally created. That being said, upon trying to use any of the `denote-link-insert*` functions and looking at the generated link, I noticed that only the timestamp is part of the link, which means that, all of my original notes now evaluate to the same exact denote link.

Is there anything that can be done to improve the situation here?

Of course, I can go through my git history and manually correct time stamps, but I was thinking if this is something that denote should provide a more robust behavior in this situation.

Best regards

**Comment by protesilaos** [comment]
Hello @felipebalbi!

> To my surprise, `denote` ended up using current timestamp instead of reusing the original one from `org-roam`. [...] I noticed that only the timestamp is part of the link, which means that, all of my original notes now evaluate to the same exact denote link.

This is a major problem, though I cannot reproduce it.  If I create three new files and run `denote-dired-rename-marked-files` on them, each gets a unique identifier based on its modification time.  I got those:

```
20220910T014217--test-one__testing.org
20220910T014230--test-two__testing.org
20220910T014346--test-three__testing.org
```

We need to figure out what is going on here.  Perhaps those files were modified by a script and they all ended up with the exact modification time, down to the last second?

**Comment by felipebalbi** [comment]
> Hello @felipebalbi!
> 
> > To my surprise, `denote` ended up using current timestamp instead of reusing the original one from `org-roam`. [...] I noticed that only the timestamp is part of the link, which means that, all of my original notes now evaluate to the same exact denote link.
> 
> This is a major problem, though I cannot reproduce it. If I create three new files and run `denote-dired-rename-marked-files` on them, each gets a unique identifier based on its modification time. I got those:
> 
> ```
> 20220910T014217--test-one__testing.org
> 20220910T014230--test-two__testing.org
> 20220910T014346--test-three__testing.org
> ```

The difference is that you are creating three new notes using `denote`, whereas I was migrating my `org-roam` notes to `denote`. Because the file naming scheme is not compatible, `denote` fails (expected behaviour in this case) to recognise the time stamp as a time stamp and considers that as part of the document title. Then it goes ahead and prepends a fresh new timestamp, I have not dug through the code to check how it chooses a timestamp, but based on your comment above, it uses the file's last modification. This would imply that something in my system is constantly `touch`ing the note files.

> We need to figure out what is going on here. Perhaps those files were modified by a script and they all ended up with the exact modification time, down to the last second?

The only thing that touches those files is `org-roam` and, from now on, `denote`.

In any case, the result is that all the links are the same :-)

**Comment by protesilaos** [comment]
> The difference is that you are creating three new notes using `denote`, whereas I was migrating my `org-roam` notes to `denote`.

I created those files without `denote`.  I just used `M-x find-file` and then saved them.  Once I had the files in place, I marked them and did `denote-dired-rename-marked-files`.  Each file had a unique identified as a result, per the file names I shared before.

> Because the file naming scheme is not compatible, `denote` fails (expected behaviour in this case) to recognise the time stamp as a time stamp and considers that as part of the document title. Then it goes ahead and prepends a fresh new timestamp, I have not dug through the code to check how it chooses a timestamp, but based on your comment above, it uses the file's last modification. This would imply that something in my system is constantly `touch`ing the note files.

Is it possible to send me some sample files?  It will help me test what is going on.

**Comment by felipebalbi** [comment]
> > The difference is that you are creating three new notes using `denote`, whereas I was migrating my `org-roam` notes to `denote`.
> 
> I created those files without `denote`. I just used `M-x find-file` and then saved them. Once I had the files in place, I marked them and did `denote-dired-rename-marked-files`. Each file had a unique identified as a result, per the file names I shared before.

I think I see what happened :-)

My files were already in a `git` repository. While testing how to do the migration, I ended up getting my files in a bad state and decided to restart the process (this happened a couple times). Because I wanted to restart, I ended up using `git reset --hard` to go back to the last committed state of the files, thus dropping all changes. It appears that `git reset --hard` will change the file's modification time.

Here's a demonstration:

```
$ ls -l 20220909T163639--book__note.org 
-rw-r--r--   1 balbi          balbi         107 2022-09-09 17:33 20220909T163639--book__note.org
$ echo foo >> 20220909T163639--book__note.org
$ ls -l 20220909T163639--book__note.org 
-rw-r--r--   1 balbi          balbi         111 2022-09-10 20:21 20220909T163639--book__note.org
$ sleep 120 && git reset --hard && ls -l 20220909T163639--book__note.org 
HEAD is now at 97ef174708f1 correct filetag
-rw-r--r--   1 balbi          balbi         107 2022-09-10 20:24 20220909T163639--book__note.org
 ```

> > Because the file naming scheme is not compatible, `denote` fails (expected behaviour in this case) to recognise the time stamp as a time stamp and considers that as part of the document title. Then it goes ahead and prepends a fresh new timestamp, I have not dug through the code to check how it chooses a timestamp, but based on your comment above, it uses the file's last modification. This would imply that something in my system is constantly `touch`ing the note files.
> 
> Is it possible to send me some sample files? It will help me test what is going on.

Let me know if you still need the files after the discussion above. Happy to send you some samples, but it appears that you should be able to recreate the situation now. The steps would be:

1. Create files
2. Save files
3. Add to `git` repository
4. Modify all files
5. Wait for a few minutes
6. `git reset --hard`
7. Mark every file
8. `denote-dired-rename-marked-files`

I have created a temporary repo with 3 text files here for testing and I can reproduce the issue now. After the steps above, here are the file names:

```
-rw-r--r--   1 balbi          balbi    4 2022-09-10 20:29 20220910T202928--1__note.txt
-rw-r--r--   1 balbi          balbi    4 2022-09-10 20:29 20220910T202928--2__note.txt
-rw-r--r--   1 balbi          balbi    6 2022-09-10 20:29 20220910T202928--3__note.txt
```

All these files will result in the same `denote` link.

**Comment by protesilaos** [comment]
Okay, thanks for the information!  I don't need the files then.

I believe this change prevents Denote from making those renames:

```diff
 denote.el | 10 ++++++++--
 1 file changed, 8 insertions(+), 2 deletions(-)

diff --git a/denote.el b/denote.el
index c764303..64d4de6 100644
--- a/denote.el
+++ b/denote.el
@@ -1350,13 +1350,19 @@ (defun denote--file-attributes-time (file)
    denote--id-format
    (file-attribute-modification-time (file-attributes file))))
 
+;; TODO 2022-09-11: Generalise the check for duplicate IDs.
 (defun denote--file-name-id (file)
   "Return FILE identifier, else generate one."
   (cond
    ((string-match denote--id-regexp file)
     (substring file (match-beginning 0) (match-end 0)))
-   ((denote--file-attributes-time file))
-   (t (format-time-string denote--id-format))))
+   ((let ((id (denote--file-attributes-time file)))
+      (unless (denote--barf-duplicate-id id)
+        id)))
+   (t
+    (let ((id (format-time-string denote--id-format)))
+      (unless (denote--barf-duplicate-id id)
+        id)))))
 
 (defun denote-update-dired-buffers ()
   "Update Dired buffers of variable `denote-directory'."
```

I tested it on files that were generated by the shell command:

```sh
for i in one two three ; do touch $i ; done
```

* * *

For your case, perhaps you can run a loop which uses `touch` after a `sleep 1s`?

**Comment by protesilaos** [comment]
Hello again!

With commit `f0b9604` I have tried to handle this in `denote.el` directly.

```
commit f0b9604099bd2064aecbe67e24bc5e098e278673
Author: Protesilaos Stavrou <info@protesilaos.com>
Date:   Fri Jul 14 12:12:55 2023 +0300

    Acknowledge Bruno Boal for commit 69a7067
    
    The patch was sent via a private channel.  The change is small and
    thus does not require copyright assignment to the Free Software
    Foundation.

 README.org | 16 ++++++++--------
 1 file changed, 8 insertions(+), 8 deletions(-)
```

Discussion on the mailing list: https://lists.sr.ht/~protesilaos/denote/%3C87v8emeus0.fsf%40protesilaos.com%3E

**Comment by protesilaos** [comment]
This feature is now part of Denote version 2.0.0: https://protesilaos.com/codelog/2023-07-21-denote-2-0-0/
