### ISSUE TITLE
Error loading denote-org-dblock

### ISSUE THREAD

**Issue by jackbaty** [protesilaos/denote#113]
I was seeing an `Invalid read syntax ")"` error when evaluating `(require 'denote-org-dblock)` (using latest [ce8e661](https://github.com/protesilaos/denote/commit/ce8e6613257664a650e4cba86f9ee4e401876653)).

For me, removing what looks like an extra closing ")" on line 144 fixed the error.

https://github.com/protesilaos/denote/blob/ce8e6613257664a650e4cba86f9ee4e401876653/denote-org-dblock.el#L144

**Comment by protesilaos** [comment]
Thank you @jackbaty!  It turns out there was an extra parenthesis in line 142.  I just fixed it in commit `2414839`.
