### ISSUE TITLE
not getting previous keywords in option list when creating note

### ISSUE THREAD

**Issue by vigilancetech-com** [protesilaos/denote#119]
How do I enable this?

I'm running spacemacs with the ivy layer installed if that helps.

**Comment by protesilaos** [comment]
Hello @vigilancetech-com!

I am not sure which scenario you are referring to.  Do you not get a list of completion candidates at the minibuffer prompt?

Known keywords are stored in the user option `denote-known-keywords` as a list of strings.

Keywords can also be inferred from existing notes and presented as completion candidates when the user option `denote-infer-keywords` is `t` (the default).

Lastly, the user can exclude certain keywords from being inferred by writing the appropriate regular expression as the value of `denote-excluded-keywords-regexp`.

While at the minibuffer prompt, you can always get the previous input in the history with `M-p` (not sure if this works for Spacemacs though).  `M-n` and `M-p` cycle through the history elements.

**Comment by vigilancetech-com** [comment]
I think I found it.  I had to hit tab to see them come up.   They didn't come up automatically as they appear to do on the videos I've seen about denote.   Think I'd rather have them come up automatically but not sure how to make that happen.

**Comment by protesilaos** [comment]
I see.  By default, Emacs does not have that capability.  You can tweak the defaults, though I encourage you to use the `vertico` package.  It is exceptional.  Also check the companion packages that are mentioned in its README.  I recommend them all.

<https://github.com/minad/vertico>
