### ISSUE TITLE
README feedback 

### ISSUE THREAD

**Issue by kaushalmodi** [protesilaos/denote#12]
>  Consider the case where the alternative notes in the blog have no use for the identifier field inside the front matter. Let’s omit it

Is it safe to suggest that? Some user might do that and then wonder whey `denote-link` doesn't work. 

Additionally, if there is no identifier match, `denote-link` throws an error with backtrace i.e. it's not an elegant `user-error`.

**Comment by protesilaos** [comment]
> Some user might do that and then wonder whey `denote-link` doesn't
> work.

True.  Will remove this part.

> Additionally, if there is no identifier match, `denote-link` throws an
> error with backtrace i.e.  it's not an elegant `user-error`.

Better fix this then to fail gracefully.  I will most likely not be able
to do this right now, as I am about to go bed.  Tomorrow for sure!

**Comment by protesilaos** [comment]
> Better fix this then to fail gracefully. I will most likely not be able to do this right now, as I am about to go bed. Tomorrow for sure!

I believe I fixed this while also moving the relevant code to its own file instead of keeping it in `denote-link.el`.  The relevant part:

```elisp
(defun denote-retrieve--search (regexp)
  "Search for REGEXP in the current buffer."
  (save-excursion
    (save-restriction
      (widen)
      (goto-char (point-min))
      (re-search-forward regexp nil t 1)
      (match-string-no-properties 1))))

(defun denote-retrieve--find-value (regexp)
  "Return value from REGEXP by searching the file."
  (or (denote-retrieve--search regexp)
      (user-error "Cannot retrieve %s" regexp)))
```

**Comment by kaushalmodi** [comment]
Thanks! I'll close this issue then.

**Comment by protesilaos** [comment]
Thank you!
