### ISSUE TITLE
dir.local.el file - Invalid Function

### ISSUE THREAD

**Issue by aa-parky** [protesilaos/denote#124]
Emacs 28.2
Denote version 1.2.0

If I place a _dir-locals.el_ file in a silo and add 

`((nil . ((denote-directory . default-directory))))`

or 

`((nil . ((denote-directory . "/~path/to/silo"))))
`

It appears to have no effect on the option to _create-note-in-subdirectory_

If I evaluate the line I get the the message

>  Invalid Function.

Also, if I use dired to navigate to the silo that contains the dir-locals.el file I get the following message.

`The local variables list in /Users/aapark/Developer/denote_public/contains values that may not be safe (*).`

```
Do you want to apply it?  You can type
y  -- to apply the local variables list.
n  -- to ignore the local variables list.
!  -- to apply the local variables list, and permanently mark these
      values (*) as safe (in the future, they will be set automatically.)
i  -- to ignore the local variables list, and permanently mark these
      values (*) as ignored
```

I'm not sure if this is user error or possibly a problem with denote?

**Comment by protesilaos** [comment]
Hello @aa-parky!

I cannot reproduce this on my end.  Maybe you first need to apply the local variables, as suggested in the prompt, and then try again?

**Comment by aa-parky** [comment]
I will try from a bare bones Emacs install and report back. Applying the variables made no difference.

**Comment by protesilaos** [comment]
Okay, please let me know how it goes.

**Comment by aa-parky** [comment]
Not sure, what it was. Possible OS X Ventura folder access problem. But now fixed.

Steps taken.

1. recreated my emacs.d file from a working back up
2. granted Emacs full disk access in OSX preferences.

Thanks again for a great piece of software.

**Comment by protesilaos** [comment]
Very well!
