### ISSUE TITLE
Suggestion of a denote function that uses cl keywords.

### ISSUE THREAD

**Issue by MirkoHernandez** [protesilaos/denote#126]
I would like to suggest the implementation of a denote function that uses cl keywords, or something similar that combines the possibility of user provided data and the default denote prompts. The idea  is to facilitate the creation of custom functions that can default to the usual denote behavior.

```
(cl-defun denote-custom (&key title keywords file-type subdirectory date template signature)
  (funcall-interactively 'denote
			 (or title (denote-title-prompt))
			 (or keywords (denote-keywords-prompt))
			 file-type
			 subdirectory
			 date
			 template
			 signature)) 

(denote-custom  :subdirectory "video")
(denote-custom  :title (some-custom-title-prompt))
(denote-custom  :signature (some-defun-that-set-the-signature))
```

**Comment by protesilaos** [comment]
Good idea!  I tweaked it a bit.  What do you think?

```elisp
(cl-defun denote-custom
    (&key
     (title (denote-title-prompt))
     (keywords (denote-keywords-prompt))
     (file-type (denote-file-type-prompt))
     (subdirectory (denote-subdirectory-prompt))
     (date (denote-date-prompt))
     (template (denote-template-prompt)))
  "Define custom `denote' command with :KEY VALUE pairs.

The :KEY corresponds to the TITLE, KEYWORDS, FILE-TYPE,
SUBDIRECTORY, DATE, and TEMPLATE arguments:

- `:title'
- `:keywords'
- `:file-type'
- `:subdirectory'
- `:date'
- `:template'

The VALUE for each of those is the same as explained in the doc
string of the `denote' command.  It defaults to what `denote'
would do.  VALUE may also be a function that returns the desired
value."
  (funcall-interactively 'denote title keywords file-type subdirectory date template))
```

Note that I will add the `SIGNATURE` argument in the other branch we have for it.

**Comment by MirkoHernandez** [comment]
Great! that was the idea. I forgot to mention the function that grabs the note from dired for renaming. ` denote--rename-dired-file-or-prompt` I really like that functionality. hopefully that can be incorporated as well, or in a variation of this function.

**Comment by protesilaos** [comment]
I will add `denote-custom` and update the manual accordingly.

Can you tell me more about `denote--rename-dired-file-or-prompt`?  What is your use-case of it?  How do you plan to modify its behaviour?  Note that it is a private function right now, so its usage outside of Denote is technically uncharted territory.

**Comment by MirkoHernandez** [comment]
Right there is probably no use case for that, I'm so used to calling denote from dired (denote and denote-rename-file). I was thinking of the rename function. Maybe a variation of this could could be implemented for `denote-rename-file`, specifically for keyword and signature manipulation. Currently `denote-keywords-add` does not change the filename so I'm using `denote-rename-file` exclusively.

**Comment by protesilaos** [comment]
There have been many changes since we last discussed this. I think what we have here is no longer applicable. There is also this discussion, which is about how best to approach this hackabilitty aspect of the Denote code base: https://github.com/protesilaos/denote/issues/257
