### ISSUE TITLE
Additional keywords delimiter after the last keywords

### ISSUE THREAD

**Issue by 2nd-civilization** [protesilaos/denote#128]
Hi, prot.
For now denote don't add keywords delimiter for the last keyword. This may cause some problems.
Say I have both keywords `bee` and `beef`.  Searching `_bee` may return notes with keywords `beef`. But I can't simly search `_bee_`because "bee" might be the last keyword.
It can be overcome with some regex, but I think add additional ending keywords delimiter will be more elegant.

**Comment by protesilaos** [comment]
Hello @2nd-civilization!

Adding an extra delimiter for this case will put the burden on the code in resolving potentially more edge cases like this one.  We will have to make it more complex.  In general, that is worth consider though here I feel that a regexp is the more flexible and straightforward approach.

Consider how in the following example, `M-x re-builder` with `"_\\<bee\\>"` matches only one target:

```
_b
_be
_bee
_beef
_beefy
```

![Screenshot from 2023-01-15 18-31-43](https://user-images.githubusercontent.com/12828033/212553629-6681677f-b9ba-4414-aae6-9beb7bc79f91.png)

**Comment by 2nd-civilization** [comment]
Well, it is not a problem in emacs.
I watched your youtube video introducing `denote` saying that you want denote to be as low-tech as possible (basically useable even outside emacs). And that is why I opened this issue.
If I want to use `grep` to full-text search my notes, that could causes some inconvinience.
Many command line tools like `grep` don't filter filenames using regex. Yes, one could still use commands like `find` along with them. But this , IMO, introduces more complexity.
If I'm using MS Windows, it is even more inconvenient.
But I agree it is not a big problem in most cases.

**Comment by Jochim** [comment]
> Many command line tools like `grep` don't filter filenames using regex. 

The [glob patterns](https://www.man7.org/linux/man-pages/man7/glob.7.html) supported by `grep` should be sufficient in most cases. A glob pattern of `*_bee[._]*` will match only on occurrences of the `_bee` tag. The limitation being that it will not match when `_bee` is the last tag and the file has no extension. You can get around this by appending ` *_bee` to the `grep` command.

> Yes, one could still use commands like `find` along with them. But this , IMO, introduces more complexity. If I'm using MS Windows, it is even more inconvenient. But I agree it is not a big problem in most cases.

In Powershell you can find matching filenames with `Get-ChildItem -Recurse -Include *_bee[._]*` or less verbosely as `gci -recurse *_bee[._]*`. The no extension edge case can be covered by comma separating the file globs like so: `*_bee[._]*,*_bee`.

`grep` and `find` should also be available to you on Windows via `git/usr/bin`.
