### ISSUE TITLE
Denote org capture a template to save in a subdirectory

### ISSUE THREAD

**Issue by aadi58002** [protesilaos/denote#132]
I have been trying to create a template for notes which denote saves to the Notes sub directory in the denote-directory.
The Notes directory already exists in denote directory.
.
├── Denote
│   ├── Entertainment
│   ├── Notes
│   ├── Resources
│   └── Todo 

This is my denote config
``` elisp
(use-package denote
    :config
    (setq denote-directory "~/Documents/Denote")
    (setq denote-known-keywords '())
    (setq denote-infer-keywords t)
    (setq denote-sort-keywords t)
    (setq denote-excluded-directories-regexp nil)
    (setq denote-excluded-keywords-regexp nil)
    (setq denote-date-prompt-use-org-read-date t)
    (setq denote-backlinks-show-context t))

(with-eval-after-load 'org-capture
  (add-to-list 'org-capture-templates
               '("n" "New note (with Denote)" plain
                 (file (concat (concat denote-directory "/Notes/") (file-name-nondirectory denote-last-path)))
                 #'denote-org-capture-delete-empty-file
                 :no-save t
                 :immediate-finish nil
                 :kill-buffer t
                 :jump-to-captured t)))
```

The above template exists without asking for any prompt with error Invalid file location.

**Comment by protesilaos** [comment]
Hello @aadi58002!

I just made the requisite changes and documented everything here: https://protesilaos.com/emacs/denote#h:95b78582-9086-47e8-967f-62373e2369a0

Please give it a try and let me know if it works for you.

Note that you do not need to use the `denote-org-capture-delete-empty-file`.  It is done internally by Denote.  Here is the relevant snippet from `denote.el`:

```elisp
(defun denote-org-capture-delete-empty-file ()
  "Delete file if capture with `denote-org-capture' is aborted."
  (when-let* ((file denote-last-path)
              ((denote--file-empty-p file)))
    (delete-file denote-last-path)))

(add-hook 'org-capture-after-finalize-hook #'denote-org-capture-delete-empty-file)
```

**Comment by aadi58002** [comment]
@protesilaos Thanks for the quick reply.
The new feature is quite useful.
But i was along the lines that i can set a the const directory for a template
For example the notes directory will always put the file in the `<denote-directory>/Notes/`
``` elisp
(add-to-list 'org-capture-templates
             '("N" "New note with prompts (with denote.el)" plain
               (file denote-last-path)
               (function
                (lambda ()
                  (denote-org-capture-with-prompts :title nil :subdirectory)))
               :no-save t
               :immediate-finish nil
               :kill-buffer t
               :jump-to-captured t))
```  
```
When called without arguments, do not prompt for anything.  Just
return the front matter with title and keyword fields empty and
the date and identifier fields specified.  Also make the file
name consist of only the identifier plus the Org file name
extension.

Otherwise produce a minibuffer prompt for every `non-nil` value
that corresponds to the TITLE, KEYWORDS, SUBDIRECTORY, DATE, and
TEMPLATE arguments.  The prompts are those used by the standard
denote command and all of its utility commands.
```

But the function denote-org-capture-with-prompts will always prompt me for Subdirectory selection which i will have to choose each times Even for the template i know should go in a predirectory.

If it could me made like below where the path can be set with arguments that will be perfect.
``` elisp
(with-eval-after-load 'org-capture
    (add-to-list 'org-capture-templates
                '("n" "New note" plain
                (file denote-last-path)
                (function
                    (lambda ()
                    (denote-org-capture-with-prompts :title :keyword (concat denote-directory "/Notes/"))))
                :no-save t
                :immediate-finish nil
                :kill-buffer t
                :jump-to-captured t))
)
```
Ps if i am understand something wrong here let me know. I am not to familiar with elisp yet so i might have missed something.


Anyway thanks for the amazing packages and youtube videos it really helped me explore emacs as a whole.

**Comment by protesilaos** [comment]
Oh, I see.  Please try this approach:

```elisp
(add-to-list 'org-capture-templates
             '("N" "New note in directory (with denote.el)" plain
               (file denote-last-path)
               (function
                (lambda ()
                  (let ((denote-directory (file-name-as-directory (concat (denote-directory) "testing"))))
                    (denote-org-capture))))
               :no-save t
               :immediate-finish nil
               :kill-buffer t
               :jump-to-captured t))
```

**Comment by aadi58002** [comment]
Thanks it is exactly i was looking.
Thanks for the great support

**Comment by protesilaos** [comment]
You are welcome!

**Comment by protesilaos** [comment]
> From: x61 ***@***.***>
> Date: Mon, 22 Apr 2024 18:45:25 -0700

> [... 18 lines elided]

> ```
>   (with-eval-after-load 'org-capture
>         (add-to-list 'org-capture-templates
>               '(
>                 ("g" "General" plain
>                  (file denote-last-path)
>                  (function
>                   (lambda ()
>                     (let ((denote-directory (file-name-as-directory (concat (denote-directory) "General"))))
>                       (denote-org-capture))))
>                  :no-save t
>                  :immediate-finish nil
>                  :kill-buffer t
>                  :jump-to-captured t)
>
>                 ("H" "House" plain
>                  (file denote-last-path)
>                  (function
>                   (lambda ()
>                     (let ((denote-directory (file-name-as-directory (concat (denote-directory) "House"))))
>                       (denote-org-capture))))
>                  :no-save t
>                  :immediate-finish nil
>                  :kill-buffer t
>                  :jump-to-captured t)
>
>                )
>
>   )
>         )
> ```
> I am getting the following error message:
> ``Wrong type argument: stringp, ("g" "General" plain (file denote-last-path) #'(lambda nil (let ((denote-directory (file-name-as-directory (concat (denote-directory) "General")))) (denote-org-capture))) :no-save t :immediate-finish nil :kill-buffer ...) ``
> Anything I am doing wrong? Sorry for reporting here instead of creating a new issue ticket. 

This is because 'add-to-list' adds a list of lists in the code you are
using. You do not want that because it breaks the expected final value
of the 'org-capture-templates'.

You need a separate 'add-to-list' for each template.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by x61** [comment]
Thank you. Is it possible to create templates without using multiple add-to-list? I am asking because with a regular org-mode-capture template, you can specify multiple capture templates at once. It is perfectly fine if it is not possible. Thanks again for your prompt response.

**Comment by protesilaos** [comment]
> From: x61 ***@***.***>
> Date: Tue, 23 Apr 2024 02:40:34 -0700
>
> Thank you. Is it possible to create templates without using multiple
> add-to-list? I am asking because with a regular org-mode-capture
> template, you can specify multiple capture templates at once. It is
> perfectly fine if it is not possible. Thanks again for your prompt
> response.

Note that there is nothing Denote-specific here. If you want to set all
templates at once, you need to use 'setq' or equivalent.

-- 
Protesilaos Stavrou
https://protesilaos.com
