### ISSUE TITLE
Org capture with denote while creating title programatically

### ISSUE THREAD

**Issue by relict007** [protesilaos/denote#133]
Hi  @protesilaos ,
Thanks a lot for Denote. I use it everyday and it has become an essential part of my workflow. 

I use org-capture with denote to capture different types of information.  One use case if of capturing a webpage
for which I would like denote title/filename to be of the title+domain extracted from the webpage. I also want to include webpage url in a `#+url:` property as well as its content in org format. I have defined some functions of my own to do it using org-capture with the help of `org-web-tools`, however, it involves using some internal denote functions. 

```emacs-lisp
;; make denote front matter using title and keyword
  (defun rlct/denote-make-frontmatter(title keywords)
    (denote--format-front-matter
     title (denote--date nil 'org) keywords
     (format-time-string denote-id-format nil) 'org)
    )

;; set appropriate value to denote-last-path based on title and keywords
  (defun rlct/denote-make-capture-filename (title keywords)
    (setq denote-last-path
          (denote--path title keywords
                        (file-name-as-directory (denote-directory))
                        (format-time-string denote-id-format) 'org))
    )

;; parse url from x clipboard and apply keywords
(defun rlct/denote-capture-website (keywords)
    (-let* (
            (url (org-web-tools--get-first-url))
            (data (rlct/url-fetch-clean-content url))
            (html-title (rlct/alist-get-equal "title" data))
            (html-excerpt (rlct/alist-get-equal "excerpt" data))
            (html-body (rlct/alist-get-equal "content" data))
            (site-name (rlct/alist-get-equal "site-name" data))
            (org-content (rlct/html-to-org html-body))
            (title (concat (s-left 100 html-title) " - " (s-left 100 site-name)))
            (extra-header (concat
                           "#+startup: showall \n"
                           "#+url: "
                           url
                           "\n"
                           "#+excerpt: " html-excerpt
                           "\n\n\n"
                           "* " html-title 
                           "\n\n"
                           ))
            (front-matter (rlct/denote-make-frontmatter title keywords))
            (final-content (concat front-matter extra-header org-content))
            )
      (rlct/denote-make-capture-filename title keywords)
      final-content
      )
    )

;; wrapper to capture websites that i want to read later (sets appropriate keywords)
(defun rlct/denote-capture-readlater()
    (rlct/denote-capture-website '("website" "readlater"))
    )

;;add this to org-capture-templates
  (add-to-list 'org-capture-templates
               '("wl" "read later"  plain
                 (file denote-last-path)
                 #'rlct/denote-capture-readlater
                 :jump-to-captured t
                 )
               )


```

I have skipped definitions of some functions in `rlct/denote-capture-website` which are used to download and parse
the url, I can add them if you would like to see them. 

As you can see in the above code, I am kind of overriding `denote-last-path`  and also generating header content
on my own so that title and filename gets the desired value. However, this all looks a bit hackish to me and feels like
I am missing something obvious. I also tried using `denote-templates` which are cool, however, `org-capture` has some nice keyword expansions that I like to use.  

I am kind of new with elisp so please excuse the rudimentary code that I have hacked up. 

Could you please share your thoughts. Let me know if I am not clear about my requirements.

**Comment by protesilaos** [comment]
Hello @relict007!

Changing the `denote-last-path` is fine.  We do it for the other points of entry with `org-capture`, namely, `denote-org-capture` and `denote-org-capture-with-prompts` (the latter is part of the current development version).

The `denote--path` and `denote--format-front-matter` are stable and I think we could make them public.  Though this may be an opportunity to think about possible ways to make this more flexible for DIY users and/or extension developers.

**Comment by protesilaos** [comment]
> I don't think I have any feedback on how to make whole thing more generic at the moment though.

Sure, no worries.  I was thinking out loud to have it as a discussion point here.  It may suffice to make those functions public.

**Comment by protesilaos** [comment]
We have made lots of changes since this was last discussed. I think we can close this now. Please re-open it if you think there is something we can do with the current version of Denote. Thank you!
