### ISSUE TITLE
Providing a way to extend the content of the backlinks buffer ?

### ISSUE THREAD

**Issue by lucasgruss** [protesilaos/denote#134]
Hi there ! Thank you for coming up with (and maintaining) denote :) 

Recently in [citar-denote](https://github.com/pprevos/citar-denote/issues/12) @pprevos and I discussed a way to find all the notes citing a specific reference. The solution uses the completion framework, which is coherent with the philosophy of the citar-denote. 

This made me realize that there could be additional sources of backlinks between notes, e.g. citations.

As such, would it be a good idea to provide an entry point for packages and users to populate the backlinks buffer with their own content ?

I was thinking that we could define a customization option as a list of functions to run when `denote-link-backlinks` is invoked, each populating the backlinks buffer with their results.

**Comment by pprevos** [comment]
I am toying around with a function that shows the local 'neigbhourhood' of a note using the hierarchy package. That could be a function that taps into the backlink buffer.

This function will display a tree with all notes linked to current buffer at 2 of three levels deep.

**Comment by protesilaos** [comment]
@pprevos Sounds promising!  Once we have something concrete to experiment with, we will see how best to put this together and what other options we have.

**Comment by pprevos** [comment]
@protesilaos It will take me a while. I am trying to achieve a balance between working with Emacs and working on Emacs is

**Comment by protesilaos** [comment]
@pprevos Yes, that's important.

**Comment by protesilaos** [comment]
The backlinks buffer is more flexible now, though I have not checked if it can do what you had originally described here. If do have time to check, please let me know. Closing this in the meantime.
