### ISSUE TITLE
denote--get-silo-path: Symbol’s function definition is void: file-name-parent-directory

### ISSUE THREAD

**Issue by ruahman** [protesilaos/denote#138]
I'm getting 

denote--get-silo-path: Symbol’s function definition is void: file-name-parent-directory

 when ever I try to run the "denote" command.

here is my configuration.

  (use-package denote
    :config
    (setq denote-directory (expand-file-name "~/denote"))
    (setq denote-infer-keywords t)
    (setq denote-sort-keywords t)
    (setq denote-file-type nil)
    (setq denote-prompts '(title keywords))
    (setq denote-allow-multi-word-keywords t))

what's going on here?  
any clues or hints would be appreciated.

**Comment by protesilaos** [comment]
Hello @ruahman!  Are you pulling from the Git source?  If so, I made a change earlier that should fix this.

**Comment by ruahman** [comment]
Okay, I think I fixed it.  but I am confused.

I added to  .dir-locals.el  to my denote directory.
but I don't have silos setup.

but I looks like I can use the denote command again.

**Comment by protesilaos** [comment]
You shouldn't have to add anything.  But if there is a problem, then it is a bug.

**Comment by ruahman** [comment]
I'm using straight.el so I try to pull the latest source code from that.
thank you for your quick response

**Comment by protesilaos** [comment]
You are welcome!  Please let me know if the latest commit works for you.

**Comment by diegovelascommerce** [comment]
It worked for me thank you

**Comment by protesilaos** [comment]
You are welcome!
