### ISSUE TITLE
denote-file-types plist now has 11 elements and not 8

### ISSUE THREAD

**Issue by doolio** [protesilaos/denote#139]
Namely,

   :extension
     :date-function
     :front-matter
     :title-key-regexp
     :title-value-function
     :title-value-reverse-function
     :keywords-key-regexp
     :keywords-value-function
     :keywords-value-reverse-function
     :link
     :link-in-context-regexp

https://github.com/protesilaos/denote/blob/65dd92e971b0af3ea31624eb426379582ce40604/denote.el#L1024

**Comment by protesilaos** [comment]
Good catch.  Thank you!
