### ISSUE TITLE
`denote-file-type` value get lost and always the Org meta data is inserted

### ISSUE THREAD

**Issue by kaushalmodi** [protesilaos/denote#14]
Hello,

I believe this is a recent regression

I am unable to make this work:

```el
(defun denote-md ()
  (interactive)
  (let ((denote-directory (file-name-directory (buffer-file-name)))
        (denote-file-type 'markdown-toml))
    (call-interactively #'denote)))
```

- The .md file gets created, but then the inserted meta data is in Org format.

When I did a quick debug using this:

```el
(defun denote--prepare-note (title keywords &optional path)
  "Use TITLE and KEYWORDS to prepare new note file.
Use optional PATH, else create it with `denote--path'."
  (message "denote-file-type: %S" denote-file-type)
  (let* ((p (or path (denote--path title keywords)))
         (default-directory denote-directory)
         (buffer (unless path (find-file p)))
         (header (denote--file-meta-header
                  title (denote--date) keywords
                  (format-time-string denote--id))))
    (unless path
      (with-current-buffer buffer (insert header))
      (setq denote-last-buffer buffer))
    (setq denote-last-front-matter header)))
```

I noticed that the `denote-file-type` is back to nil there even when I am setting it to `markdown-toml` in that let. I need to further debug this, but I won't have time to do that until tomorrow.

I am opening this issue just in case someone else lands up on the same issue.

**Comment by protesilaos** [comment]
Strange...  It seems to work on my end.  Just invoked your command:

```
+++
title      = "Testing this with denote-md command"
date       = 2022-06-12T17:52:12+03:00
tags       = ["testing"]
identifier = "20220612T175212"
+++
```

Note that the `(file-name-directory (buffer-file-name))` in `denote-md` does not work when called form the `*scratch*` buffer (my initial test).  But that is not related to the `denote-file-type`.

**Comment by kaushalmodi** [comment]
Oops, sorry for this noise. I had `denote-file-type` set to `nil` in a project .dir-locals.el. I think that denote internally creates a temp buffer and so the .dir-locals.el settings kick in there.

**Comment by protesilaos** [comment]
I got a backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  (let ((denote-directory (file-name-directory (buffer-file-name))) (denote-file-type 'markdown-toml)) (call-interactively #'denote))
  denote-md()
  funcall-interactively(denote-md)
  call-interactively(denote-md record nil)
  command-execute(denote-md record)
  execute-extended-command(nil "denote-md" nil)
  funcall-interactively(execute-extended-command nil "denote-md" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by kaushalmodi** [comment]
> Note that the (file-name-directory (buffer-file-name)) in denote-md does not work when called form the *scratch* buffer (my initial test).

Correct. I make sure I always call it from a file buffer (it was a quick way for me to change the denote directory.

**Comment by protesilaos** [comment]
> Oops, sorry for this noise.

No worries!

> .dir-locals.el settings

We should elaborate on this in the section about creating those user-level commands.  It will be useful, especially for the `denote-directory`.
