### ISSUE TITLE
Selecting a non-denote file navigates to only to denote files with `denote-link-find-file` minibuffer 

### ISSUE THREAD

**Issue by nobiot** [protesilaos/denote#142]
Related to #135. After 9ce9a245cc70723dbe8d7a65bf980abf62252b10 and 94a3ffd4429570e69090e72ff7656181972b6dd0, the prompt in minibuffer from `denote-link-find-file` shows non-denote files such as PDFs and images when you have multiple files with the single ID. This is an intended behavour.

However, if you select a non-denote file from the selection, when there exists a denote file type for the same ID, you can only open the file of the denote file type and not the non-denote file you select.

How to reproduce:

1. Create a normal denote file (e.g. an Org file with an ID)
2. Create a PDF file (or any non-denote file such as images) with the same ID as 1.
3. Go to a denote file (existing one or create another new one) and call `denote-link-insert-link`  to insert a link to the ID created in 1
4. In the same buffer, call `denote-link-find-file`
5. You should see both files from 1 and 2 (Org and non-denote file)
6. Select the non-denote file
7. You opens the Org file

The cause of this issue because `denote-link-find-file` uses `denote-get-path-by-id` after the prompt created by `denote-link--find-file-prompt`. I'm just raising this issue to record what I have been made aware. I don't have a solution at the moment.

**Comment by protesilaos** [comment]
Thank you @nobiot for fixing this!
