### ISSUE TITLE
 `denote-link-or-create` enters path instead of note name into title history

### ISSUE THREAD

**Issue by JonatanSahar** [protesilaos/denote#144]
Hi,

When creating notes while linking to them the previous history element contains the full path to the note being created (i.e. ~/notes/new-note) instead of just "new-note".

I couldn't understand where the path is coming from, since `denote-file-prompt` is called without arguments in `denote-link-or-create`...

**Comment by protesilaos** [comment]
Hello @JonatanSahar.  Yes, I see the problem.  I guess we can configure the prompt to not record the history in this case.  It needs more thought.  Any feedback is appreciated.

**Comment by protesilaos** [comment]
I just pushed a change that should fix this issue.  Please let me know if it persists.

**Comment by JonatanSahar** [comment]
Hi,
I'm now getting the title of the previous note created, but not the one I'm trying to create (or its path). 
I have a couple of other issues with the package though, so I'm not sure where the trouble lies here;

**Comment by JonatanSahar** [comment]
I just checked again - I do have the changes in your commit, but after calling `denote-link-or-create`, entering a new title which doesn't exist, and hitting `return` again for `[confirm]`, I get prompted for the title again, and the history doesn't have the title I just tried to create.

**Comment by JonatanSahar** [comment]
I looked at the code a little, and couldn't see how it's supposed to work - in `link-or-create` you're calling file prompt, which populates `--file-history`, but later `denote` calls `title-prompt`, which uses `--title-history`.
my elisp foo is  quie weak though, so I may be wrong..
