### ISSUE TITLE
Delimiters in signatures

### ISSUE THREAD

**Issue by fintelkai** [protesilaos/denote#147]
The `denote-signature-regexp` constant is set to `"==\\([[:alnum:][:nonascii:]]*\\)"`, limiting the choices for the construction of signatures.

As [mentioned](https://github.com/protesilaos/denote/issues/115#issuecomment-1361193500) by @sthesing:

> Luhmann used a broad thematic category at the beginning of his signatures, followed by a slash or comma and started his alternating system from there: `1/1b4d` would be a different note than `2/1b4d`. 

Obviously, a slash is rightly considered illegal in a filename. But a comma might be possible, but I don't expect that `denote=` should be revised to allow it.

I've tried to look for nonascii characters that might be both unobtrusive and pass the muster of `denote-signature-regexp`. One option that I like is `︙`, unicode number `U+FE19`, called "Presentation Form for Vertical Horizontal Ellipsis". This way I can have Luhmann-esque signatures like `1︙1a2b`, with the `1︙` prefix situating the sequence in a very broad category in my personal ontology. In my tests, `denote` seems to not mind this delimiter in signatures.

So, this is not a bug report or a feature request, but a remark on how to work with the existing code.

**Comment by protesilaos** [comment]
Hello @fintelkai!

We can relax the standard of what should go into the signature.  I wanted to start conservatively and then figure out what the needs of the community are.

**Comment by protesilaos** [comment]
A relevant thread on the mailist list: <https://lists.sr.ht/~protesilaos/denote/%3C2A597B4E-5F18-4D97-9457-B3C859DAA020%40zoho.eu%3E>

My comment:

```
Hello Jeremy, Alfredo,

> From: "Jeremy Friesen" <jeremy@jeremyfriesen.com>
> Date: Sat, 25 Mar 2023 10:42:12 -0400
>
> One of the adjustments I made when attempting the Luhmann sorting was
> to have the following prefix schema: 00aa11bb22cc
>
> [... 15 lines elided]
>
> All of which is to say, I'm often loath to put commas in my file names
> as an old DOS habit.

I also feel uncomfortable with commas in file names though I guess they
are not strictly wrong.  My intuition, in following with the Denote
naming scheme, is to use "=" as the separator.  This is consistent with
how "-" is separator for the title and "_" for the keywords.

The manual has a section about "Features of the file-naming scheme for
searching or filtering":
<https://protesilaos.com/emacs/denote#h:1a953736-86c2-420b-b566-fb22c97df197>.
Maybe that gives us a direction?

All the best,
Prot
```

**Comment by fintelkai** [comment]
I like the consistency of using `=` as a delimiter in signatures.

**Comment by protesilaos** [comment]
Thank you @fintelkai!  I just made the changes.  Please let me know if this works for you.

**Comment by fintelkai** [comment]
It works perfectly and so I'm closing the issue. Next, I plan to refine the signature workflow and I may be back with some proposals.

**Comment by protesilaos** [comment]
Very well!  The end goal is to make the signature work the same as other entries in a file's front matter.
