### ISSUE TITLE
denote-rename-file-using-front-matter doesn't work since last update

### ISSUE THREAD

**Issue by morgandavidson** [protesilaos/denote#148]
I'm using denote-1.2.0.0.20230320.92324 on Emacs 28.2. Since this last update `denote-rename-file-using-front-matter` doesn't work anymore, I have the following message when using it : `user-error: No front matter for title and/or keywords.`

**Comment by protesilaos** [comment]
Hello @morgandavidson!  This should be fixed since commit `ffbe225` (2023-03-21).  But it seems that GNU ELPA is not available right now so updates will not come through.

**Comment by morgandavidson** [comment]
Hello @protesilaos, thanks a lot!

**Comment by protesilaos** [comment]
> From: Morgan Davidson ***@***.***>
> Date: Sat, 25 Mar 2023 12:52:30 -0700
>
> Hello @protesilaos, thanks a lot!

You are welcome!  Please let me know if the issue persists.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by morgandavidson** [comment]
I now have `denote-1.2.0.0.20230325.160136` installed and `denote-rename-file-using-front-matter` works fine. Thank you!

**Comment by protesilaos** [comment]
You are welcome!
