### ISSUE TITLE
[feature request] Only display TITLE in tabs

### ISSUE THREAD

**Issue by morgandavidson** [protesilaos/denote#151]
Hello, and thank you for your wonderful work. I've been using denote for some weeks with `consult-notes` and I find it awesome.

As for now I only found one pain point: the length of the file name displayed in tabs.

I use [centaur-tabs](https://github.com/ema2159/centaur-tabs) to display a tab for each buffer, so I can easily navigate between buffers as one does between web pages in a web browser.

The issue is (and it would be the same for any other tabs plugin) that denote file names are so long, that only one to two tabs can be displayed per window. 

Of course, with `centaur-tabs`, one can fix the length of the tabs. So for example is you fix the length to `8`, your tab will only show the 8 first characters.

And the tab will display `20230410` instead of  `20230410T021830--title-i-gave-to-the-org-file__tag1_tag2_tab3_tag4.org`.

However, this number is not very useful to have a grasp of what the file is about...

What would be quite useful for denote users that also use tabs,  would be to have the tabs only display the TITLE part of the file name. 

Would that be feasible?

**Comment by protesilaos** [comment]
Hello @morgandavidson!

> What would be quite useful for denote users that also use tabs, would be to have the tabs only display the TITLE part of the file name.
>
> Would that be feasible?

Do you know if centaur-tabs provides a function to rename buffers?  If it does, then we can use it to achieve what you suggest.  I have not used centaur-tabs for anything other than testing purposes (for my themes) and thus am not familiar with the technicalities.  I can always check, but that requires time.

**Comment by morgandavidson** [comment]
Hello @protesilaos,

I don't know about centaur-tabs ability to rename buffers, I can ask the developers on centaur-tabs' Github. But is it about renaming buffers of tab names? 

There are various ways of displaying tabs in Emacs (tabbar, centaur-tabs, moody, etc.). I'm not specifically focused on keeping using centaur-tabs, but rather on being able to use denote with tabs. Also, I guess that there might be denote users using tabs without centaur-tabs. So maybe the best possible solution would be something generic.

Also, rethinking about this issue, I thought that instead of having the tab name produced automatically (i.e. taking the TITLE), there could be an option to specify it, let say `#+tabname:`.

**Comment by morgandavidson** [comment]
Got an interesting answer on [emacs stackexchange](https://emacs.stackexchange.com/questions/76839/is-there-a-way-to-specify-names-of-tabs/76848#76848). 

For what I understand what could be done is the following:

- Automated naming version: 
  a new denote function will rename the buffer with the TITLE of the file using `rename-buffer`
- Manual naming version:
  `#+tabname` option in header will allow to give the buffer a specific name. A deonte function will automatically change the buffer name with the value specified in `#+tabname`.

**Comment by protesilaos** [comment]
@morgandavidson I prefer the automated version because this is Emacs-specific.  The `#+tabname` adds noise because it has no meaning outside Emacs.

I will document how to do it as soon as possible.

**Comment by protesilaos** [comment]
Please try this.  We can refine it further, but it should be a starting point:

```elisp
(defun my-denote-rename-file-buffer ()
  (when-let* ((file (buffer-file-name))
              ((denote-file-has-identifier-p file))
              (title (denote-retrieve-filename-title file)))
    (rename-buffer title :unique)))

(add-hook 'find-file-hook #'my-denote-rename-file-buffer)
```

**Comment by morgandavidson** [comment]
Your code works quite well, thanks!

Maybe both (auto and manual) could be implemented as options of a variable. 

`denote-rename-buffer` could take 3 exclusive values : `a` for automatic, `m`, for manual and `nil`.

I am already using the manual implementation, (see my answer to [this question](https://emacs.stackexchange.com/questions/76839/is-there-a-way-to-specify-names-of-tabs?), which I find quite useful.

There could also be a `denote-rename-tab` variable, for the tab managers that support changing tab names without changing buffer names (see my answer to the above-mentioned emacs.stackexchange question). It is unfortunately not the case for centaur-tab at the moment.

I find the manual version more useful to me because sometimes my titles are quite long, which is good when you produce a document, but it is not practical to have such long titles as tab names. 

For example, if I'm creating an org file having "The Hitchhiker's Guide to the Galaxy" as a title, it would be more practical to have H2G2 as a tab name.

**Comment by morgandavidson** [comment]
Hello @protesilaos!

If the manual approach changes the buffer name, then it will work regardless of the tab package. Because to my knowledge, in all the tab packages, the tab name is the buffer name (and it can't be otherwise). There is an exception with `tab-bar-mode` where the tab name is by default the buffer name, but can be different from it if specified (with `tab-rename`).

I started trying alternatives to `centaur-tabs` to use built-in Emacs modes when possible. I tried `tab-bar-mode` but it wasn't adapted to my use case. Then I tried `tab-line-mode`, which was fine but not as satisfying as `centaur-tabs`. Now I'm using [intuitive-tab-line-mode](https://github.com/thread314/intuitive-tab-line-mode/tree/master). For all these packages, the following snippet implemented the manual approach satisfyingly: 

```
*** Specify buffer name with =#+tabname:= keyword
- Get =#+tabname:= value
  #+begin_src emacs-lisp 
    (defun org-get-kw-value (kw)
      "Get the value of keyword kw."
      (save-excursion
	(goto-char (point-min))
	(let ((case-fold-search t))
	  (re-search-forward (format "^#\\+%s:\\(.+\\)" kw) nil t)
	  (when-let (kwval (match-string-no-properties 1))
	    (string-trim kwval)))))
  #+end_src
- If =#+tabname:= exists set buffer-name to its value
#+begin_src emacs-lisp 
  (defun mda/org-hook-function ()
    "If keyword TABNAME exists, set buffer-name to its value."
    (when-let (new-buf-name (org-get-kw-value "tabname"))
      (rename-buffer new-buf-name)))
    (add-hook 'org-mode-hook #'mda/org-hook-function)
#+end_src
```
An alternative would be to use the [org-element-api](https://orgmode.org/worg/dev/org-element-api.html).

You're right when you say that it would not be trivial to have `mode-line` showing `20230410T021830--title-i-gave-to-the-org-file__tag1_tag2_tab3_tag4.org` and tab showing `My Org` due to `#+tabname: My Org`. I don't even understand how it could be possible to have such a solution, working for all tab packages. Since tab name and buffer name are the same thing for them.

**Comment by protesilaos** [comment]
Hello again @morgandavidson!

Just to note that I have published a prototype of an extension: `denote-rename-buffer.el`.  It provides a minor mode that simply renames the Denote buffers.  The idea is to make this configurable.

**Comment by morgandavidson** [comment]
Hello @protesilaos, thank you for letting me know,

If I understand correctly, there is one function that replaces the buffer name with the file title on demand, and a minor mode that replaces it automatically when activated. Am correct?

Do you plan to add a feature allowing users to name each buffer according to a name specifically chosen by them in the future?

**Comment by protesilaos** [comment]
> If I understand correctly, there is one function that replaces the buffer name with the file title on demand, and a minor mode that replaces it automatically when activated. Am correct?  Do you plan to add a feature allowing users to name each buffer according to a name specifically chosen by them in the future?

Yes, your understanding is correct.  The idea is to extend this basic functionality with user options.  I will work on it as soon as I can.

**Comment by morgandavidson** [comment]
Hello @protesilaos!

That is great news. Thanks a lot!

**Comment by protesilaos** [comment]
I defined a user option to allow users to specify the function they want to use.  I wrote the details in the manual: <https://protesilaos.com/emacs/denote#h:3ca4db16-8f26-4d7d-b748-bac48ae32d69>.

> Customize the user option `denote-rename-buffer-function` to affect how buffers are renamed.  Its value must be the symbol of a function.  The default is the `denote-rename-buffer-with-title`, with an alternative of `denote-rename-buffer-with-identifier`.
> 
> The user option also accepts an arbitrary function.  Refer to the implementation details of `denote-rename-buffer-with-title` or `denote-rename-buffer-with-identifier` for guidance on how to write a custom function.

**Comment by protesilaos** [comment]
This feature is now part of Denote version 2.0.0: https://protesilaos.com/codelog/2023-07-21-denote-2-0-0/

**Comment by morgandavidson** [comment]
Hello @protesilaos!
I just tested `denote-rename-buffer-mode` Denote 2.0.0 and it's really cool. Thanks!

```emacs-lisp
(denote-rename-buffer-mode 1)
```
changes the buffer name (and hence the tab name) to the note's title, and if you add
```emacs-lisp
    (setq denote-rename-buffer-function #'denote-rename-buffer-with-identifier)
```
it changes the buffer name to the note's identifier.

Also, you mention to look at `denote-rename-buffer-with-title` and `denote-rename-buffer-with-identifier` functions from `denote-rename-buffer.el` for guidance on how to write a custom function.

These two functions respectively rely on `denote--retrieve-title-or-filename` and `denote-retrieve-filename-identifier` functions, defined in `denote.el`.

I was wondering if there was an equivalent function, aiming to extract a custom buffer name specified within the buffer.

**Comment by protesilaos** [comment]
> From: Morgan Davidson ***@***.***>
> Date: Fri, 21 Jul 2023 13:28:29 -0700
>
> Hello @protesilaos!
> I just tested `denote-rename-buffer-mode` Denote 2.0.0 and it's really cool. Thanks!

You are welcome!

> [... 9 lines elided]

> Also, you mention to look at `denote-rename-buffer-with-title` and
> `denote-rename-buffer-with-identifier` functions from
> `denote-rename-buffer.el` for guidance on how to write a custom
> function.
>
> These two functions respectively rely on
> `denote--retrieve-title-or-filename` and
> `denote-retrieve-filename-identifier` functions, defined in
> `denote.el`.
>
> I was wondering if there was an equivalent function, aiming to extract
> a custom buffer name specified within the buffer.

There is no such function because we do not add any relevant entry in
the front matter.  You would have to define it yourself by basing it off
of one of the "retrieve" functions.  For example, a new custom function
to match "#+denoterename: Some title here":

    (defvar my-denote-rename-regexp "^#\\+denoterename\\s-*:"
      "Sample regular expression of Denote rename Org front matter.")

    (defun my-denote-retrieve-rename-value (file _file-type)
      "Return title value from FILE front matter.
    This is based on `denote-retrieve-title-value' but we do not use
    the FILE-TYPE argument as we only test for Org in the variable
    `my-denote-rename-regexp'."
      (with-temp-buffer
        (insert-file-contents file)
        (goto-char (point-min))
        (when (re-search-forward my-denote-rename-regexp nil t 1)
          (funcall #'denote-trim-whitespace
                   (buffer-substring-no-properties (point) (line-end-position))))))

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by morgandavidson** [comment]
Hi @protesilaos,

Thank you for the help with the function. As it is a bit sophisticated in regard to my Elisp level, I didn't have the time to work on it yet.

However, I found an easy way to rename an org buffer/tab.



Generally, you can specify the buffer name (and consequently the tab name) of a given org file by putting the following snippet at the bottom of this file:
```
* Local Variables :noexport:
# Local Variables:
# eval: (rename-buffer "foo")
# End:
```

Unfortunately, it doesn't work with denote files. But what is odd is that running

```
#+begin_src emacs-lisp 
(rename-buffer "foo")
#+end_src
```
inside a denote file works...

I was wondering if there was an equivalent of `rename-buffer` that would work to specify a local variable for a denote file.

**Comment by protesilaos** [comment]
> From: Morgan Davidson ***@***.***>
> Date: Fri, 29 Sep 2023 10:09:24 -0700
>
> Hi @protesilaos,

Hello Morgan

> Thank you for the help with the function. As it is a bit sophisticated
> in regard to my Elisp level, I didn't have the time to work on it yet.

You are welcome!  I am happy to help.  The code I provided before
addresses the point of extracting an arbitrary keyword/value from the
file's front matter.  We would then need to do something with that.

> However, I found an easy way to rename an org buffer/tab.
>
> Generally, you can specify the buffer name (and consequently the tab
> name) of a given org file by putting the following snippet at the
> bottom of this file:
>
> ```
> * Local Variables :noexport:
> # Local Variables:
> # eval: (rename-buffer "foo")
> # End:
> ```
>
> Unfortunately, it doesn't work with denote files. But what is odd is that running

In my case this works.  I created the file, included the above snippet,
killed the buffer, and then visited the file again.  Note that this only
works if 'denote-rename-buffer-mode' is disabled.

> ```
> #+begin_src emacs-lisp 
> (rename-buffer "foo")
> #+end_src
> ```
> inside a denote file works...
>
> I was wondering if there was an equivalent of `rename-buffer` that
> would work to specify a local variable for a denote file.

In principle, we do not have a "denote file", meaning that we do not
introduce any new functionality on top of Org, Markdown, etc.  What
ordinarily works for those should continue to work in this case.  If it
does not, it is a bug and we need to figure out what causes it.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by morgandavidson** [comment]
Hello Protesilaos,

Indeed I activated `denote-rename-buffer-mode` since I would like to have `#+title:` value as buffer name for most of my denote notes. In some cases though, I would have preferred to have a specific buffer name that is different from the  `#+title:` value.
