### ISSUE TITLE
How to open denote links outside of denote when the note is located in a silo?

### ISSUE THREAD

**Issue by morgandavidson** [protesilaos/denote#153]
I often use `org-store-link` and `org-insert-link` to create new links within org files not managed by denote.

So suppose I'm using `index.org` file to manage org-links and denote links. 

- If I store a denote link pointing to a file located in the default denote folder, the file will open correctly. 
- If I store a denote link pointing to a file located in a denote silo folder, the file won't open. 

Then how could I do to manage denote links from regular org files when the target note is located in a denote silo?

**Comment by protesilaos** [comment]
Hello @morgandavidson!

In theory we can have a file-local variable in `index.org` that sets the value of `denote-directory` (subject to some tweaks in `denote.el`.  But that will still not work with multiple silos.  There would have to be some other command that first prompts for a silo and then searches there.  Though this is prone to errors.

One way to handle this and scale it to multiple silos without any changes on Denote's side is to:

1. Write metanotes in the silo, which aggregate links to other notes and add relevant remarks: https://protesilaos.com/emacs/denote#h:6060a7e6-f179-4d42-a9de-a9968aaebecc
2. Create a regular Org file in the silo which can reference those metanotes.
3. In the `index.org` create a link to the regular Org file inside the silo.

**Comment by morgandavidson** [comment]
At the moment most of my denote files pointed by links outside of denote are from the default folder. I only have 3 files from Silos in my index. I use these files quite often, so they also are _registers_. As I don't expect to have much more of these, I think I will keep indexing these with regular org-links. I was just curious if this use case had been considered by the tool.
