### ISSUE TITLE
How to stop denote-dired-rename-marked-files from prompting for pdf files?

### ISSUE THREAD

**Issue by jayrajput** [protesilaos/denote#155]
How does one stop denote-dired-rename-marked-files for prompting "Add front matter or rewrite front matter of keywords (buffers are not saved)?" for pdf files? I use denote to rename files quite often, but I do not use denote front matter.

**Comment by protesilaos** [comment]
Hello @jayrajput!

I believe I replied to your question via email, but it seems it never reached this web page.  Anyhow, I made commit `[d34af36](https://github.com/protesilaos/denote/commit/d34af36ef158caa6d16d7f227f69cd5e30dcfb12)` which introduces a new `C-u` argument that skips the prompt.

Does that work for you?

**Comment by jayrajput** [comment]
Thanks. This works for me. I never received the mail other than this notification.

Thanks again.

**Comment by protesilaos** [comment]
You are welcome!
