### ISSUE TITLE
The denote-find-link is the new name of denote-link-find-file, as part of 2.0.0-dev.]

### ISSUE THREAD

**Issue by soilc** [protesilaos/denote#156]
Hi Prot,  
I'm trying to run denote with "14. Sample configuration" and I get the message: "Wrong type argument: commandp, denote-find-link". Similar situation with 'denote-find-backlink'. 
Here "7.8. Visiting linked files via the minibuffer" I see this: "The denote-find-link is the new name of denote-link-find-file, as part of 2.0.0-dev.]". So everything should work, but it doesn't. 
And besides, I don't find these functions (`denote-find-link` and `denote-find-link`) with 'C-h f' at all.  
After replacement:
 `(define-key map (kbd "C-c n f f") #'denote-link-find-file) ;; denote-link-find-file -> denote-find-link`  
`(define-key map (kbd "C-c n f b") #'denote-link-find-backlink) ;; denote-link-find-backlink -> denote-find-backlink` 

everything is working. Is there a problem here?
Thanks!

**Comment by protesilaos** [comment]
Hello @soilc!

What is likely happening is that you are not running the current development version, meaning the latest commit to this repository.  Instead, you are using the latest stable release where the old names still are the correct ones and the new names do not exist yet.

**Comment by soilc** [comment]
Hello Prot,
I see that I have denote-1.2.0 from elpa. Thanks!
