### ISSUE TITLE
A link to a certain part inside notes?

### ISSUE THREAD

**Issue by soilc** [protesilaos/denote#157]
Hello Prot!
I'm currently using `org-roam`, but I'm trying to figure out the quirks of the `Denote`, which I think is as good as anything you do - Thanks! 
If we ignore the specifics of the implementation of different note taking systems (`org-roam`, `Denote`, ...), then we need to understand that there should always be a division into two conditional parts: a certain focus (center) of mental activity (1) and a mental mixer  ('knowledge base') containing its own separate centers of crystal formation of thoughts (2).
The focus, at a minimum, should always be TODO list (`org-mode`) and perhaps some other things, such as a yearly diary (for example `org-journal`).
The entire daily fragmented stream of thoughts goes into the mental mixer. In order to somehow manage all this, you need to have a convenient system of mutual references (links), covering both the focus and the mental mixer.
And here there can be links (direct and reverse) both within each of these parts, and mutual links between the focus and the mental mixer. Basically I see this exists in `org-roam` and `Denote`. But, as far as I understand, in `Denote` there is no way to add a link not just to a separate file, but to a certain part inside this file. It's right?
And here it should be noted that in `org-roam` this possibility exists, since nodes can be not only files, but also headers inside them. It's hard for me to imagine that in `Denote` all files, including your daily journals - :), have a simple structure with no headers. Thanks a lot!

**Comment by protesilaos** [comment]
Hello @soilc!

> And here it should be noted that in `org-roam` this possibility exists, since nodes can be not only files, but also headers inside them. It's hard for me to imagine that in `Denote` all files, including your daily journals - :), have a simple structure with no headers. Thanks a lot!

Denote does not track any metadata to establish links: it reads what is in the file name.  This is why we can only link to files and not invidual headings.  Files can have headings, but those are not points of entry.  Whether this a feature or limitation is up to you.

The way I treat incomplete ideas is to either not write them down at all (because I have not thought them through) or to capture them as a "maybe" entry which will become its own fully fledged note when/if it is ready.

**Comment by soilc** [comment]
Hello Prot!
In any case, thanks a lot!

**Comment by soilc** [comment]
> Do you know which command that key sequence calls? Is it the Denote org-capture template?

Yes, it's an org-capture template and it's taken from your sample configuration (14. Sample configuration) here - https://protesilaos.com/emacs/denote#h:5d16932d-4f7b-493d-8e6a-e5c396b15fd6 .

> At any rate, ...

You did not understand me. I just pointed out the fact that I gave an example where you are forced to abandon your philosophy: 

> "... we can only link to files and not invidual headings. Files can have headings, but those are not points of entry."

 and in a new note, create a link to the heading inside the file.

**Comment by protesilaos** [comment]
> I just pointed out the fact that I gave an example where you are forced to abandon your philosophy:
>
> > "... we can only link to files and not invidual headings. Files > can have headings, but those are not points of entry."
>
> and in a new note, create a link to the heading inside the file.

I don't see the contradiction.  Perhaps I did not clarify the state of affairs.  We cannot create `denote:` links to headings.  They do not get an identifier nor do they get backlinks of their own.  Other Org features will still work, including `id:` links (plus the `denote:` link type will behave like the `file:` like type if it is given the search terms I mentioned before).

Taking a step back, these are Org features though Denote is not an Org extension per se.  It also works with Markdown and plain text out-of-the-box.

**Comment by soilc** [comment]
Ok. Thanks!

**Comment by protesilaos** [comment]
You are welcome!
