### ISSUE TITLE
"denote-rename-buffer-mode" not effective when the note is called from register.

### ISSUE THREAD

**Issue by morgandavidson** [protesilaos/denote#160]
I activated buffer renaming with `(denote-rename-buffer-mode 1)`. When I open a denote org file buffer from `consult-notes`, the buffer name is properly displayed (only `TITLE` is shown), but when I open a denote org file buffer from register (`jump-to-register`), the buffer name is `DATE--TITLE__KEYWORDS.EXTENSION` instead of `TITLE`.

**Comment by protesilaos** [comment]
> From: Morgan Davidson ***@***.***>
> Date: Fri, 28 Jul 2023 01:41:47 -0700
>
> I activated buffer renaming with `(denote-rename-buffer-mode 1)`. When
> I open a denote org file buffer from `consult-notes`, the buffer name
> is properly displayed (only TITLE is shown), but when I open a denote
> org file buffer from register (`jump-to-register`), the buffer name is
> DATE--TITLE__KEYWORDS.EXTENSION instead of TITLE.

Can you tell me how you stored the file in the register?  I tried with
'point-to-register' and the renaming works in my case.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by morgandavidson** [comment]
Sure, here is how I stored the file in the register:

```emacs-lisp 
(define-key org-mode-map (kbd "C-'") nil)
(global-set-key (kbd "C-'") 'jump-to-register)
...
(set-register ?k (cons 'file (concat silos-path "Documentation/20230407T034235--keybindings-reference-cards__soft_table.org")))
...
```
I noticed that once I open the file with `consult-notes`, then when I close it and reopen it with `jump-to-register` the buffer name is properly displayed.

**Comment by protesilaos** [comment]
Hello @morgandavidson! I could not work on this earlier. Though I have been reviewing/expanding the `denote-rename-buffer-mode` these days and I want to make sure your use-case is covered as well.

With regard to registers, I can get it to work with the latest development version of Denote. I created a new file with these contents and carried out the steps described therein:

```org
#+title:      Test buffer rename with a register jump
#+date:       [2023-10-16 Mon 14:18]
#+filetags:   :denote:testing:
#+identifier: 20231016T141857

This is how I store the register:

#+begin_src emacs-lisp
(set-register ?1 `(file . ,buffer-file-name))
#+end_src

Then I kill this buffer and type =C-x r j= (~jump-to-register~
command) followed by the =1= register.

The buffer is renamed as expected (with ~denote-rename-buffer-mode~
enabled).
```

If you can try again with Denote from Git, please let me know if it works for you.

**Comment by protesilaos** [comment]
Hello @morgandavidson! The new version of Denote is available, meaning that you should now be able to upgrade the usual way and give it a try. If you do, please let me know how it goes.

**Comment by morgandavidson** [comment]
Hello @protesilaos! Sorry for not responding earlier. I have now Denote version 20231019.62646 installed. To open denote files I usually use either `consult-notes` or `jump-to-register`. When I use `consult-notes` the buffer/tab name is its title. When I use `jump-to-register` the buffer/tab name is the file name when opened for the first time. Then if the buffer/tab is closed and reopen, the the buffer/tab name is its title.

**Comment by morgandavidson** [comment]
Hello @protesilaos, 

I also noticed that the issue arises when using `org-open-at-point`.

For example, suppose that I have the following `index.org` 

```
* Denote files
- [[PATH/20231114T043651--TITLE-1__TAG][TITLE-1]]
- [[PATH/20231122T095955--TITLE-2__TAG][TITLE-2]]
```

When I do `org-open-at-point` on `* Denote files`, the two new open buffers will be named `20231114T043651--TITLE-1__TAG` and `20231122T095955--TITLE-2__TAG` until they are not opened with another method (register excepted).

**Comment by protesilaos** [comment]
Hello again @morgandavidson! I cannot reproduce any of this with the current version of Denote. No matter how I open a Denote file, the renaming always works. I assume the issue is fixed, though it will be available in the next release of Denote. If that is not the case, please re-open this issue. Thank you!

**Comment by morgandavidson** [comment]
Hello @protesilaos I cannot reproduce the bug either. It seems that your latest upgrade fixed it. Thank you!
