### ISSUE TITLE
spaced repetition

### ISSUE THREAD

**Issue by Prague2049** [protesilaos/denote#163]
Is denote possible to implement writing inbox with support for spaced repetition?
Provides a spaced-repetition system that prompts you to review notes or revisit stubs and help them grow to maturity.

**Comment by protesilaos** [comment]
Hello @Prague2049!  Denote does not have any capability of this sort.  You would need another package for it.  Maybe `org-drill`?  <https://gitlab.com/phillord/org-drill/>
