### ISSUE TITLE
Rename current file

### ISSUE THREAD

**Issue by Nebucatnetzer** [protesilaos/denote#164]
It would be handy to have `denote-rename-file` rename the file for the current buffer or do it when provided with `C-u`.
At the moment it asks for a file in the current directory.

**Comment by jeanphilippegg** [comment]
At the prompt, if you hit RET (without typing anything), the current file will be selected for renaming. This default is indicated between square brackets in the prompt.

**Comment by protesilaos** [comment]
Hello @Nebucatnetzer!  It is as @jeanphilippegg suggested.  Perhaps we can make this use-case more obvious or, somehow, more direct.  I am open to ideas.

**Comment by Nebucatnetzer** [comment]
Ah good to know that it should already work.
It shows the filename in brackets but when I press enter I get the following error message: `denote--rename-dired-file-or-prompt: Only rename regular files`

I've attached a screenshot of the action.
![image](https://github.com/protesilaos/denote/assets/2287221/b76e4ba6-f8ce-43f9-b55f-8fbdb244cb25)

**Comment by jeanphilippegg** [comment]
I think this is because the file that is selected is actually "./". It is highlighted in your screenshot. If you try `M-p` at the prompt to highlight the modeline instead, does this work?

I use Vertico, but it does not automatically select the first candidate on my side for `denote-rename-file`.

**Comment by Nebucatnetzer** [comment]
`M-p` doesn’t work it just cycles through the files in the directory.
I’m currently using counsel/ivy but your suggestion showed me that I need to have a look at the Ivy manual :).
I close the issue for the moment because it’s more likely to be a problem with my setup.

**Comment by protesilaos** [comment]
> From: Andreas Zweili ***@***.***>
> Date: Mon, 18 Sep 2023 01:11:49 -0700
>
> `M-p` doesn’t work it just cycles through the files in the directory.
> I’m currently using counsel/ivy but your suggestion showed me that I need to have a look at the Ivy manual :).
> I close the issue for the moment because it’s more likely to be a problem with my setup.

When you have time, check what M-p or M-n do in the minibuffer.  While
in the minibuffer, type C-h k and then the corresponding key.  By
default, the commands are 'previous-history-element' and
'next-history-element'.

I believe Ivy respects those defaults, though I have not used it in a
while to confirm as much.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by Nebucatnetzer** [comment]
You were absolutely right the `M-p` is the correct key combination.
I confused it with `C-p` 🤦‍♂️

```
Signature                                                                                                     
(ivy-next-history-element ARG)

Documentation                                                                                                 
Forward to next-history-element with ARG.
```
