### ISSUE TITLE
Speed up the process of selecting a subdirectory with denote-subdirectory 

### ISSUE THREAD

**Issue by tokstokstoks** [protesilaos/denote#165]
First I would like to state that I fully understand that the way I use Denote described hereunder does not embody the way Zettelkasten works. I'm fairly new to Zettelkasten and am trying/looking if Zettelkasten is something for my workflow. I mainly work with org-mode and projectile in combination with org-project-capture currently.
I have a private and work project directory. My project directory consists of around 100 project directories with a date prefix in its name. There are around 1400 files in the project directories of which some are images/pdf files/zip files.

As a software developer I use the project directory as a collection of notes concerning endpoints, bugfixes, updates, code snippets, conversations, summaries et cetera. 
The name of the project directory reflects a real internal work project.

I am still a bit hesitant to radically throw all files from all project directories in one or a few directories.
If possible I would like to slowly change my information structure and workflow.
Therefore I really like that denote has a option to select a subdirectory for a new note.
Though in my occasion selecting a subdirectory works very slow.
Every time it takes around 40-50 seconds before a subdirectory list pops up.
Is there a way to speed up this process (such as caching) besides excluding directories?

I have to state I use emacs at work with wsl2 (windows) and my org directory is a Windows directory mounted within the wsl2 environment (/mnt/c/Users/username/org). 
Maybe this is part of the problem?

**Comment by tokstokstoks** [comment]
I had the solution right under my nose. 

It was indeed [wsl2](https://stackoverflow.com/questions/68972448/why-is-wsl-extremely-slow-when-compared-with-native-windows-npm-yarn-processing) accessing the Windows ntfs filesystem which is very slow apparently. 

I moved the org directory to the linux wsl filesystem and the subdirectory list loaded almost instantaneously. Sorry for bothering and many thanks for the great Denote package!

**Comment by protesilaos** [comment]
> From: Arjan ***@***.***>
> Date: Tue, 12 Sep 2023 12:21:40 -0700
>
> Closed #165 as completed.

Hello there!  I was slow to respond as I had no Internet access at the
time.  I am glad to see you solved this.

-- 
Protesilaos Stavrou
https://protesilaos.com
