### ISSUE TITLE
Add Signature to the Link Description

### ISSUE THREAD

**Issue by mholson** [protesilaos/denote#167]
Is there a way to add the SIGNATURE to the link description? Based on the documentation it seems that only the TITLE can be included? I am considering using the signature to store a custom 4-CHAR ID ported from my current system and would like to have it visible as part of the link. 

Example:
[[denote:yymmddThhmmss][#### Title of Note]], where #### is the SIGNATURE

**Comment by protesilaos** [comment]
Hello @mholson!  Do you want the signature to be included unconditionally, or on demand?

**Comment by mholson** [comment]
Hi @protesilaos. Thanks for the quick response. It would be great if I could use a **custom function** that would insert the link description that _included the signature_. The problem is that I do not use the #### ID for every note that I write - for example a Map of Content.

Maybe I am too caught up in using the SIGNATURE to store this #### value. Perhaps I should just include this as the first four characters of the title. 

Massive Thanks! // Mark

**Comment by protesilaos** [comment]
Thank you @mholson!  I just pushed some changes which make this possible.  Check the command `denote-link-with-signature` and please let me know how it works for you.

**Comment by mholson** [comment]
Massive Thank You @protesilaos .  I have been testing since yesterday and it works brilliantly. 

Over the next couple of months, I will be porting my notes (~5000) over to denote from org-roam. Denote has been inspirational in helping me evaluate how I write, reference and maintain my notes. 

Thanks again for writing such an awesome package and documenting it meticulously.

**Comment by protesilaos** [comment]
> From: Mark Olson ***@***.***>
> Date: Tue, 26 Sep 2023 23:03:39 -0700
>
> Massive Thank You @protesilaos .

You are welcome!

>  I have been testing since yesterday and it works brilliantly. 

Very well!

> Over the next couple of months, I will be porting my notes (~5000)
> over to denote from org-roam. Denote has been inspirational in helping
> me evaluate how I write, reference and maintain my notes.

Good to know!  I wonder if there is some automated way to go about it.
Though I don't know the details of what you are doing.

> Thanks again for writing such an awesome package and documenting it
> meticulously.

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
