### ISSUE TITLE
Separate identifier format for journal entries

### ISSUE THREAD

**Issue by Basrandir** [protesilaos/denote#168]
From what I can tell the `denote-id-format` is a single constant that's used for all new notes creation. I would like my journal entries identifier to have just the date and not the time. Mostly it's so I can programmatically link the _yesterday_ and _tomorrow_ journal entries without having to worry about determining the time as well for the link generation.

Is there a way to do this without basically re-implementing the `denote` function for my journal entries? Or if someone has any other ideas for how to accomplish this, I would appreciate it.

**Comment by protesilaos** [comment]
> From: Bassam Saeed ***@***.***>
> Date: Tue, 26 Sep 2023 08:46:50 -0700
>
> From what I can tell the `denote-id-format` is a single constant
> that's used for all new notes creation.

Indeed.

> I would like my journal entries identifier to have just the date and
> not the time. Mostly it's so I can programmatically link the
> _yesterday_ and _tomorrow_ journal entries without having to worry
> about determining the time as well for the link generation.
>
> Is there a way to do this without basically re-implementing the
> `denote` function for my journal entries? Or if someone has any other
> ideas for how to accomplish this, I would appreciate it.

I am happy yo help you with what you are asking for, though since you
can handle things programmatically, I wonder why you don't tweak the
code to match a pattern like "20230926.*_journal"?  This assumes there
is only one journal entry for that day, though you could also make the
code check for the number of results and prompt you to pick one if
needed.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by Basrandir** [comment]
Thanks for the quick response Prot.

I'm not against tweaking the code, I just wanted to first check if there was a built-in way to accomplish this that I might have overlooked. For my setup I would indeed prefer to have a single journal entry per day.

My initial idea, assuming I could easily modify the identifier format just for journals, was to utilize the `denote-journal-extras-hook` which would trigger some code to automatically insert a template that has those links for the _yesterday_ and _tomorrow_ entries. Now I probably will create my own custom version of the `denote` function for use when I'm creating a new journal entry. Do you think that's the correct way to go about it or is there some other entry point I should use when creating a journal entry?

**Comment by protesilaos** [comment]
> From: Bassam Saeed ***@***.***>
> Date: Tue, 26 Sep 2023 09:35:23 -0700
>
> Thanks for the quick response Prot.

You are welcome!

> I'm not against tweaking the code, I just wanted to first check if
> there was a built-in way to accomplish this that I might have
> overlooked.

In this case, I don't think you have overlooked something.

> For my setup I would indeed prefer to have a single journal entry per
> day.

I see.

> My initial idea, assuming I could easily modify the identifier format
> just for journals, was to utilize the `denote-journal-extras-hook`
> which would trigger some code to automatically insert a template that
> has those links for the _yesterday_ and _tomorrow_ entries. Now I
> probably will create my own custom version of the `denote` function
> for use when I'm creating a new journal entry. Do you think that's the
> correct way to go about it or is there some other entry point I should
> use when creating a journal entry?

Without looking at any code, you can 'let' bind the 'denote-id-format'
and then call 'denote' the usual way.  This will create a note with the
format you specify.  Then use the hook (or 'let' bind 'denote-templates')
to insert what you need afterwards.

Using 'let':

    (let ((denote-id-format "SAMPLE-%Y"))
      (denote "test"))

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by Basrandir** [comment]
Thanks Prot! Everything works as expected. Appreciate your insight.

**Comment by protesilaos** [comment]
> From: Bassam Saeed ***@***.***>
> Date: Sat,  7 Oct 2023 10:31:00 -0700
>
> Thanks Prot! Everything works as expected. Appreciate your insight.

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
