### ISSUE TITLE
Request for Adding a Functionality Similar to ':if-new' Keyword in org-roam Capture Templates

### ISSUE THREAD

**Issue by LuciusChen** [protesilaos/denote#170]
I Need This Feature for My Workflow as It's Essential. This Would Allow Me to Customize Different Modules in My Daily Log or Achieve Similar Goals with Existing Functionality. To Be More Precise, I Want to Utilize org-capture to Easily Append Content to Different Headings. If the Heading Doesn't Exist, It Should Create One. If the Entire File Doesn't Exist, It Should Create a New File. That's the Logic I'm Describing, and I Hope It's Clear.

**Comment by protesilaos** [comment]
> From: Lucius ***@***.***>
> Date: Sat, 30 Sep 2023 19:16:56 -0700
>
> I Need This Feature for My Workflow as It's Essential. This Would
> Allow Me to Customize Different Modules in My Daily Log or Achieve
> Similar Goals with Existing Functionality. To Be More Precise, I Want
> to Utilize org-capture to Easily Append Content to Different
> Headings. If the Heading Doesn't Exist, It Should Create One. If the
> Entire File Doesn't Exist, It Should Create a New File. That's the
> Logic I'm Describing, and I Hope It's Clear.

I don't think we can achieve this with Denote because (i) it is not an
Org extension and must be able to provide features for all file types,
(ii) it does not keep track of the contents of files.

-- 
Protesilaos Stavrou
https://protesilaos.com
