### ISSUE TITLE
Journal template

### ISSUE THREAD

**Issue by kandread** [protesilaos/denote#171]
Hi Prot, 

I was thinking of adapting some ideas from [this workflow](https://youtu.be/D8CRNuuBkoU?si=LQWYNEM78Kviyv3G) for a daily journal. Part of it is defining a template for your journal entries, and I noticed that you have a TODO comment about that. I think what you describe is probably the best option ("the user is prompted for a template only if one exists.  Otherwise, no template is used.") with the addition that if there is an entry `journal` in the templates just use that one without prompting. I have code that seems to be doing that so happy to create a pull request if this is a direction that you'd like to go towards.
Thanks!

**Comment by protesilaos** [comment]
> From: Kostas Andreadis ***@***.***>
> Date: Sun,  1 Oct 2023 06:38:20 -0700
>
> Hi Prot, 

Hello Kosta,

> I was thinking of adapting some ideas from [this
> workflow](https://youtu.be/D8CRNuuBkoU?si=LQWYNEM78Kviyv3G) for a
> daily journal. Part of it is defining a template for your journal
> entries, and I noticed that you have a TODO comment about that. I
> think what you describe is probably the best option ("the user is
> prompted for a template only if one exists.  Otherwise, no template is
> used.") with the addition that if there is an entry `journal` in the
> templates just use that one without prompting. I have code that seems
> to be doing that so happy to create a pull request if this is a
> direction that you'd like to go to.  Thanks!

Sounds promising!  Please go ahead and we can discuss the details there.

Have a nice day,
Prot

-- 
Protesilaos Stavrou
https://protesilaos.com
