### ISSUE TITLE
Executing `denote-keyword-add` on an encrypted file only keeps the .gpg extension

### ISSUE THREAD

**Issue by iensu** [protesilaos/denote#172]
When I run `denote-keyword-add` on an encrypted denote file (for instance `20221114T142453--some-note__work.org.gpg`) the keyword is added correctly, but the `.org` extension is removed. I can work around it by manually changing the extension to `.org.gpg`, but it would be great if Denote handled this use-case as well. 

In order to support encrypted Org files I added the following file type. 

```
(add-to-list 'denote-file-types
               '(org-gpg 
                        :extension ".org.gpg"
                         :date-function denote-date-org-timestamp
                         :front-matter denote-org-front-matter
                         :title-key-regexp "^#\\+title\\s-*:"
                         :title-value-function identity
                         :title-value-reverse-function denote-trim-whitespace
                         :keywords-key-regexp "^#\\+filetags\\s-*:"
                         :keywords-value-function denote-format-keywords-for-org-front-matter
                         :keywords-value-reverse-function denote-extract-keywords-from-front-matter
                         :link denote-org-link-format
                         :link-in-context-regexp denote-org-link-in-context-regexp))
```

I noticed in the source code that `denote-keywords-add` calls `denote-filetype-heuristics` to figure out the file type and that function in turn relies on `file-name-extension` to figure out the extension. This function only takes the part after the final `.` into account. It might be better to look at the extensions in `denote-file-types` first, and then fall back to `file-name-extension`, but I'm not sure what other consequences that would have. 

Anyway, thank you very much for a great package. I use it daily and I feel it has really helped me improve my note taking.

**Comment by iensu** [comment]
I fixed it locally by applying the changes below. It got a bit messy though and I haven't looked into how a change like this would affect other functionality.

```diff
diff --git denote.el denote.el
index 9bc9f5c..179843e 100644
--- denote.el
+++ denote.el
@@ -2123,11 +2123,11 @@ the new front matter, per `denote-rename-file-using-front-matter'."
 
 ;;;;; Common helpers for note modifications
 
-(defun denote--file-types-with-extension (extension)
-  "Return only the entries of `denote-file-types' with EXTENSION.
+(defun denote--file-types-with-extension (file)
+  "Return only the entries of `denote-file-types' with extension of FILE.
 See the format of `denote-file-types'."
   (seq-filter (lambda (type)
-                (string-equal (plist-get (cdr type) :extension) extension))
+                (string-suffix-p (plist-get (cdr type) :extension) file))
               denote-file-types))
 
 (defun denote-filetype-heuristics (file)
@@ -2142,8 +2142,7 @@ extension in `denote-file-type'.
 If no file types in `denote-file-types' has the file extension,
 the file type is assumed to be the first of `denote-file-types'."
   (let* ((file-type)
-         (extension (file-name-extension file t))
-         (types (denote--file-types-with-extension extension)))
+         (types (denote--file-types-with-extension file)))
     (cond ((not types)
            (setq file-type (caar denote-file-types)))
           ((= (length types) 1)
@@ -2556,7 +2555,10 @@ proceed with the renaming."
     (user-error "The file is not writable or does not have a supported file extension"))
   (if-let* ((file-type (denote-filetype-heuristics file))
             (title (denote-retrieve-title-value file file-type))
-            (extension (file-name-extension file t))
+            (extension (let ((ftype (assoc file-type denote-file-types)))
+                         (if ftype
+                             (plist-get (cdr ftype) :extension)
+                           (file-name-extension file t))))
             (id (denote-retrieve-or-create-file-identifier file))
             (dir (file-name-directory file))
             (new-name (denote-format-file-name
```

**Comment by protesilaos** [comment]
Hello Jens,

> From: Jens Östlund ***@***.***>
> Date: Sun,  8 Oct 2023 13:37:23 -0700
>
> When I run `denote-keyword-add` on an encrypted denote file (for
> instance `20221114T142453--some-note__work.org.gpg`) the keyword is
> added correctly, but the `.org` extension is removed. I can work
> around it by manually changing the extension to `.org.gpg`, but it
> would be great if Denote handled this use-case as well.

Oh, this is bad!  Yes, we want to handle it properly.

> Thank you very much for a great package. I use it daily and I feel it
> has really helped me improve my note taking.

You are welcome!

> From: Jens Östlund ***@***.***>
> Date: Sun,  8 Oct 2023 14:40:05 -0700
>
> I fixed it locally by applying the changes below. It got a bit messy
> though and I haven't looked into how a change like this would affect
> other functionality.

> [... 43 lines elided]

I will take a look at it this noon.  Local time is 08:30.  Is there
anything else I need to consider or is it just the gpg extension?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by iensu** [comment]
Hello Prot! Thank you for your swift response!

>  Is there anything else I need to consider or is it just the gpg extension?

Not on my account. I think taking the declared denote-file-types extensions into account when identifying the actual extension will make the solution rather flexible. What are your thoughts?

**Comment by iensu** [comment]
Come to think of it, it might be good to also take `age` encrypted files into account ([age](https://github.com/FiloSottile/age)). Looking at the examples files seem to be suffixed with `.age` similarly to `.gpg`.

**Comment by iensu** [comment]
> The diff you sent me identifies the .org part in a file with .org.gpg though the renaming operation leaves it without the .gpg extension

That's odd, it does work for me. Does your  `denote-file-types` list contain an entry with `:extension ".org.gpg"`? I did add one as stated above. 

> Yes, sure! Though I expect we can have a generic approach that will work with all denote-encryption-file-extensions in the future.

That definitely sounds preferable! :)

**Comment by protesilaos** [comment]
> From: Jens Östlund ***@***.***>
> Date: Mon,  9 Oct 2023 14:45:46 -0700
>
>> The diff you sent me identifies the .org part in a file with .org.gpg
>> though the renaming operation leaves it without the .gpg extension
>
> That's odd, it does work for me. Does your `denote-file-types` list
> contain an entry with `:extension ".org.gpg"`? I did add one as stated
> above.

Oh, right!  I did not.  Anyhow, the idea is to fix this without
registering more file types.

>> Yes, sure! Though I expect we can have a generic approach that will
>> work with all denote-encryption-file-extensions in the future.
>
> That definitely sounds preferable! :) 

Okay, more to follow!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
What do you think about this?

```elisp
(defun denote--get-file-extension (file)
  "Return extension of FILE, accounting for `denote-encryption-file-extensions'."
  (let ((outer-extension (file-name-extension file :period)))
    (if-let (((member outer-extension denote-encryption-file-extensions))
             (file (file-name-sans-extension file))
             (inner-extension (file-name-extension file :period)))
        (concat inner-extension outer-extension)
      outer-extension)))
```

It seems to always return the right thing, but maybe I missed some case.  This is the test I wrote for it:

```elisp
(defun denote-test--denote--get-file-extension ()
  "Test that `denote--get-file-extension' gets the correct file extension."
  (should (and (equal (denote--get-file-extension "20231010T105034--some-test-file__denote_testing") "")
               (equal (denote--get-file-extension "20231010T105034--some-test-file__denote_testing.org") ".org")
               (equal (denote--get-file-extension "20231010T105034--some-test-file__denote_testing.org.gpg") ".org.gpg")
               (equal (denote--get-file-extension "20231010T105034--some-test-file__denote_testing.org.age") ".org.age"))))
```

If you think it is sufficient, we can go ahead to add it in the right places.

**Comment by iensu** [comment]
That looks good to me! 😄

**Comment by protesilaos** [comment]
Hi @iensu!  I made the changes.  I had to make some more adjustments.  Please let me know if it works for you.

**Comment by iensu** [comment]
@protesilaos Fantastic! I just tried the latest `main` branch locally and all works as expected! I even tried `denote-keywords-remove` just to be sure ;) 

Thanks for solving this so quickly, and thanks again for yet another great package! (I'm also a dedicated user of modus-themes)

**Comment by iensu** [comment]
Btw, another question: the Denote info manual is not getting installed on my machine for some reason. I'm using `straight.el` to install Denote, pointing to this repository. Any advice on how to get the manual installed?

**Comment by protesilaos** [comment]
> From: Jens Östlund ***@***.***>
> Date: Wed, 11 Oct 2023 10:13:12 -0700
>
> @protesilaos Fantastic! I just tried the latest `main` branch locally
> and all works as expected! I even tried `denote-keywords-remove` just
> to be sure ;)

Very well!

> Thanks for solving this so quickly, and thanks again for yet another
> great package! (I'm also a dedicated user of modus-themes)

You are welcome!

> Btw, another question: the Denote info manual is not getting installed
> on my machine for some reason. I'm using `straight.el` to install
> Denote, pointing to this repository. Any advice on how to get the
> manual installed?

I believe this is how straight handles things by default, meaning that
it does not convert the README.org into an Info manual the way the GNU
ELPA machinery does.  Perhaps there is a user option to enable this
functionality, though I am not familiar with straight.

On this note, Emacs 29 provides the 'package-vc-install' command and
there even is a use-package ':vc' keyword for it.  It fetches packages
directly from their source (Git or any other version control system
supported by VC) and installs it as if it had come from GNU ELPA.  This
means that you get the manual as well.

Granted, I do not know what sort of features straight provides which are
not part of package-vc, though it is something worth considering.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by iensu** [comment]
Thanks! I'll have a look at it!

**Comment by protesilaos** [comment]
Closing now since we fixed this. Thanks again!
