### ISSUE TITLE
Return new path from `denote-rename-file` please?

### ISSUE THREAD

**Issue by mentalisttraceur** [protesilaos/denote#183]
It would be helpful to programmatic use if `denote-rename-file` returned the path of the new file. (Basically I'd just add one line to have it return `new-name` at the end.)

For a practical example, in a couple of my keybinds, I'd like Dired to leave point on the renamed file after running `denote-rename-file`. The most intuitive thing would've been `(dired-goto-file (denote-rename-file ...))`, but alas.

More abstractly, I think this is a perfect example of a principle I like to summarize as: "tell callers what they can't already know (especially if your code is uniquely positioned to know it)". `denote-rename-file` does all the work to get a new name, then just doesn't share that information. Its result is a new name, possibly an opened/edited buffer, and a file-system side-effect. Since side-effects don't exist in a form that can be passed around, and the buffer can be gotten trivially from the name, returning the name is the most natural choice.

**Comment by protesilaos** [comment]
Hello @mentalisttraceur! Does this diff work for you?

```diff
 denote.el | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/denote.el b/denote.el
index 9ac3d37..6ab699c 100644
--- a/denote.el
+++ b/denote.el
@@ -2359,7 +2359,8 @@ (defun denote--rename-file-subr (file identifier title keywords signature &optio
       (when (denote-file-is-writable-and-supported-p new-name)
         (if (denote--edit-front-matter-p new-name file-type)
             (denote-rewrite-front-matter new-name title keywords file-type no-confirm)
-          (denote--add-front-matter new-name title keywords id file-type))))))
+          (denote--add-front-matter new-name title keywords id file-type)))
+      new-name)))
 
 ;;;###autoload
 (defun denote-rename-file (file title keywords signature &optional ask-date)
```

Note that we are discussing a pull request that will change the renaming commands, so some things will change: <https://github.com/protesilaos/denote/pull/182>.

**Comment by mentalisttraceur** [comment]
@protesilaos yep, that's exactly what I had in mind! Thanks!

**Comment by protesilaos** [comment]
The changes to the "rename" commands are done. I thus added this feature. Please let me know how it works for you and if we need to do something more with it.

**Comment by protesilaos** [comment]
Forgot to close this... It is done. Doing it now. Thanks!
