### ISSUE TITLE
denote-keywords-{add|remove} a note under version control throws a vc.el error

### ISSUE THREAD

**Issue by willydeliege** [protesilaos/denote#185]
Hello,

When trying to add or remove keywords on a file under vc-control, the following error is thrown: 
`vc-rename-file: please save files before moving them`
stopping the add/remove keywords - rename process
My configuration emacs 29.1 ubuntu package
Tested with denote 2.0 and the last development one

**Comment by protesilaos** [comment]
Thank you @willydeliege! I removed the `vc-rename-file` operation for now. It requires the buffer to be saved. Maybe there is an alternative, but I am not seeing it right now.

**Comment by willydeliege** [comment]
> Thank you @willydeliege! I removed the `vc-rename-file` operation for now. It requires the buffer to be saved. Maybe there is an alternative, but I am not seeing it right now.
Thank you for you speednes @protesilaos.

**Comment by protesilaos** [comment]
You are welcome! And thank you for taking the time to report the bug. We can safely close this now.
