### ISSUE TITLE
Unable to insert denote links in a capture buffer

### ISSUE THREAD

**Issue by psmith1303** [protesilaos/denote#186]
When I am capturing an idea using `org-capture`, I sometimes want to link to a denote file by using `denote-link`. In other words, I use **C-c n l** whilst in a capture buffer.

If I do that I get an error saying "Wrong type argument: stringp, nil". The full error in the message buffer is:

`denote-filetype-heuristics: Wrong type argument: stringp, nil
`
This only happens in capture buffers.

Is it just me (and my config) or do other people get that problem too?

**Comment by protesilaos** [comment]
Thank you @psmith1303 for taking the time to report this!

> Is it just me (and my config) or do other people get that problem too?

It was a bug. I just fixed it.

**Comment by psmith1303** [comment]
Thanks again.

**Comment by protesilaos** [comment]
> From: Peter Smith ***@***.***>
> Date: Sat,  4 Nov 2023 12:19:23 -0700
>
> Closed #186 as completed.

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
