### ISSUE TITLE
call-interactively 'denote-region

### ISSUE THREAD

**Issue by rbenit68** [protesilaos/denote#188]
I would like to use `(call-interactively 'denote-region ...)`

I have tested the following:

`(call-interactively 'denote-region t ["Title" "key1"]) `

or

`(call-interactively 'denote-region t (vector "Title" "key1")) `

but no luck.

Am I doing something wrong?

**Comment by rbenit68** [comment]
I have modified `denote-region`

```
(defun my/denote-region (title key)
  (interactive)
  (if-let (((region-active-p))
           ;; We capture the text early, otherwise it will be empty
           ;; the moment `insert' is called.
           (text (buffer-substring-no-properties (region-beginning) (region-end))))
      (progn
        (denote title key)
        (push-mark (point))
        (insert text)
        (run-hook-with-args 'denote-region-after-new-note-functions (mark) (point)))
    (call-interactively 'denote)))
```

I can call `('my/denote-region "Title" '("key"))` successfully. 

Sorry for the noise.

**Comment by protesilaos** [comment]
> From: rbenit68 ***@***.***>
> Date: Mon,  6 Nov 2023 09:48:03 -0800
>
> I would like to use `(call-interactively 'denote-region ...)`
>
> I have tested the following:
>
> `(call-interactively 'denote-region t ["Title" "key1"]) `
>
> or
>
> `(call-interactively 'denote-region t (vector "Title" "key1")) `
>
> but no luck.
>
> Am I doing something wrong?

Note that 'call-interactively' does not accept further arguments. If you
want to pass this from Lisp but still count the call as an "interactive"
one, then use 'funcall-interactively'.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
> From: rbenit68 ***@***.***>
> Date: Mon,  6 Nov 2023 13:05:01 -0800
>
> I have modified `denote-region`
>
> ```
> (defun my/denote-region (title key)
>   (interactive)
>   (if-let (((region-active-p))
>            ;; We capture the text early, otherwise it will be empty
>            ;; the moment `insert' is called.
>            (text (buffer-substring-no-properties (region-beginning) (region-end))))
>       (progn
>         (denote title key)
>         (push-mark (point))
>         (insert text)
>         (run-hook-with-args 'denote-region-after-new-note-functions (mark) (point)))
>     (call-interactively 'denote)))
> ```
>
> I can call `('my/denote-region "Title" '("key"))` successfully. 
>
> Sorry for the noise.

All good, no worries!

-- 
Protesilaos Stavrou
https://protesilaos.com
