### ISSUE TITLE
Include subdirectories in `denote-dired-directories`

### ISSUE THREAD

**Issue by leinfink** [protesilaos/denote#190]
Hi! For my purposes, I want `denote-dired-mode` to be active in all folders within my personal folder. (This is not the same as the denote-directories where I want my notes to be stored, as sometimes I may also want to denote-ify other files such as PDFs etc.) Currently, `denote-dired-mode-in-directories` only checks if the current directory is a member of the list `denote-dired-directories`, but that means that if the current directory is a subdirectory, it will not activate.

I think adding a customizable option for this behavior would be unobtrusive.

I already have a working implementation. If this behavior is desired, I can already submit a pull request.

**Comment by protesilaos** [comment]
> From: Henrik ***@***.***>
> Date: Mon, 13 Nov 2023 04:53:34 -0800
>
> Hi!

Hello there!

> For my purposes, I want `denote-dired-mode` to be active in all
> folders within my personal folder. (This is not the same as the
> denote-directories where I want my notes to be stored, as sometimes I
> may also want to denote-ify other files such as PDFs etc.) Currently,
> `denote-dired-mode-in-directories` only checks if the current
> directory is a member of the list `denote-dired-directories`, but that
> means that if the current directory is a subdirectory, it will not
> activate.

Yes, this is useful

> I think adding a customizable option for this behavior would be
> unobtrusive.
>
> I already have a working implementation. If this behavior is desired,
> I can already submit a pull request.

Sounds good. Please proceed and we will take it from there.

-- 
Protesilaos Stavrou
https://protesilaos.com
