### ISSUE TITLE
Fontify modeline

### ISSUE THREAD

**Issue by leinfink** [protesilaos/denote#192]
I like the fontification in denote-dired-mode, simply because the different parts of the filename carry different kinds of information and it makes it easy to get the information I want from a quick glance.

Just an idea: What about enabling the same colours for the filename in the modeline? At the moment, that is just a super long monochrome string for me. Would that be too hard to achieve and/or depend too much on people's custom modelines to be generally useful?

**Comment by protesilaos** [comment]
This is probably possible but will be complicated. There will be lots of edge cases to consider and I don't think we should go down that path.

**Comment by leinfink** [comment]
Right, that's kinda what I assumed. Not a big deal anyway, I guess I'll close this as wont-fix.
