### ISSUE TITLE
Links with signature for files without a title put the filename into the description

### ISSUE THREAD

**Issue by leinfink** [protesilaos/denote#194]
Hi! `denote-link-with-signature` is supposed to do the following:

> The description of the link includes the signature followed by
the file's title, if any.  For this case, the signature is
assumed present.

However, this uses `denote--link-get-description-with-signature`, which in turn uses `denote--link-get-description` to get the description, which unfortunately in turn uses `denote--retrieve-title-or-filename` -- so when there is no title, the filename gets inserted instead (alongside the signature). This is, I presume, the intended behavior only for description-links without signatures. Links with signatures to files without a title should only insert the signature into the description.

I guess in theory it's a matter of replacing the call to `denote--retrieve-title-or-filename` with a call to `denote-retrieve-title-value`, but that would of course also change the behavior for links without signatures.

**Comment by protesilaos** [comment]
Hello @leinfink! I am fine to change this behaviour specifically for `denote-link-with-signature`. In general with signatures, I am trying to be conservative so as to implement only what users of them actually need.

Since you checked the functions, do you want to prepare a patch or pull request to not return a generic title? No worries if you cannot: I will do it instead.

**Comment by jeanphilippegg** [comment]
This is an old issue and the user has not replied, but with the new variable `denote-link-description-function`, I think this issue can be closed.

`denote-link-description-function` can be set to behave as desired by the user. This controls the description used by all link creation functions. If, however, the user wants a special link description function for `denote-link-with-signature`, here is the way to go by let binding `denote-link-description-function`:

```
(defun my-denote-link-with-signature ()
  (let ((denote-link-description-function #'my-link-description-function-with-signature))
    (call-interactively #'denote-link-with-signature)))
```
