### ISSUE TITLE
Script to convert org-roam notes to denote

### ISSUE THREAD

**Issue by juh2** [protesilaos/denote#196]
I found two scripts on github to convert org-roam notes to denote.
https://github.com/mkesslerct/roam_to_denote
https://github.com/bitspook/notes-migrator

The first does not support links and the second fails with my current emacs 29 while it kind of worked with 28 but not on all notes.

If there was a good script to convert org-roam files to denote – ideally without sqlite support – I would be very happy as I have 10.000+ notes.

Due to random problems with emacs+sqlite I would like to switch to a non-database Zettelkasten workflow and denote seems to be the best candidate.

**Comment by protesilaos** [comment]
Hello @juh2! I am not familiar with the requirements and cannot help you with this. Maybe someone who has used org-roam in earnest can comment here.

**Comment by protesilaos** [comment]
I am closing this folks, because I am not familiar with the requirements of such a conversion.
