### ISSUE TITLE
denote-org-capture doesn't obey denote-prompts.

### ISSUE THREAD

**Issue by Cerebus** [protesilaos/denote#197]
I have `signature` set in `denote-prompts`, and it works correctly in `denote-open-or-create`.  With `denote-org-capture`, signature is not prompted.  In fact, `denote-org-capture` only prompts for title and keywords:

https://github.com/protesilaos/denote/blob/90ff0dec954f12160f20ed9b5c015e2582fc2438/denote.el#L3825-L3826

**Comment by protesilaos** [comment]
Hello @Cerebus! Did you check the `denote-org-capture-with-prompts`? I think it does what you need. The manual's entry about it: <https://protesilaos.com/emacs/denote#h:95b78582-9086-47e8-967f-62373e2369a0>

**Comment by protesilaos** [comment]
We have since fixed this issue (thanks @jeanphilippegg) and it will be available in the next version of `denote`.
