### ISSUE TITLE
denote-link: `delete-line` is not known to be defined

### ISSUE THREAD

**Issue by kaushalmodi** [protesilaos/denote#2]
When I try to compile `denote-link.el` (Emacs 28.1.50), I get this warning

> In end of data:
denote-link.el:136:12: Warning: the function ‘delete-line’ is not known to be
    defined.

**Comment by protesilaos** [comment]
Oh, sorry about that @kaushalmodi.  The compiler does not issue a warning about it.

How about this?

```elisp
(defun denote-link-clear-stale-backlinks ()
  "Delete backlinks that no longer point to files."
  (interactive)
  (let ((default-directory (denote-directory)))
    (save-excursion
      (goto-char (point-min))
      (when (re-search-forward denote-link-backlink-heading nil t))
      (while (re-search-forward denote-link--backlink-regexp nil t)
        (unless (file-exists-p (match-string-no-properties 1))
          ;; (delete-line)
          (delete-region (point-at-bol) (point-at-bol 2)))))))
```

**Comment by protesilaos** [comment]
> What emacs version are you running?

Emacs 29.

> +1 That compiles cleanly. Thanks!

Very well!  Pushed the change per commit 0e65f05

**Comment by protesilaos** [comment]
Gotcha!
