### ISSUE TITLE
denote-link shows backup files

### ISSUE THREAD

**Issue by babusri** [protesilaos/denote#200]
Watched your video and installed denote. Created a couple of entries.
I created a link from one to another and vice-versa.
denote-link shows backup files (ending with ~).
I think given that ~ files are temporary, they should be excluded.

Thanks for all your emacs packages.

**Comment by protesilaos** [comment]
Thank you @babusri! I just made a change that should cover this case.

**Comment by babusri** [comment]
That was fast. Thanks.

**Comment by protesilaos** [comment]
> From: babusri ***@***.***>
> Date: Mon, 11 Dec 2023 01:31:52 -0800
>
> That was fast. Thanks.

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
