### ISSUE TITLE
denote-rename-buffer-mode option produces error

### ISSUE THREAD

**Issue by umbrellaid** [protesilaos/denote#201]
https://github.com/protesilaos/denote/blob/3dce4a7b5d8eb058c48145b32da2e399a9567043/README.org?plain=1#L2296C16-L2296C16

I was using your sample setup as a starting point to start to learn your denote for emacs. This line gave me the error: "Symbol's function definition is void: denote-rename-buffer-mode". I am running GNU Emacs 29.1. I downloaded denote from multiple sources and tried on more than one computer it still generated the error. I tried to read (I am slowly reading the documentation, thank you for writing all of the documentation so we can learn this is awesome) about this feature and I do NOT need this feature, I am just sharing this error so you are aware of it. I commented it out and now everything works with no errors so far. Thank you for all of the amazing work you do for the community. Take care and be well. (If I did something wrong or if I misunderstand something, I apologize.) Thank you again.

**Comment by Jousimies** [comment]
I thought it may be caused by https://github.com/protesilaos/denote/blob/3dce4a7b5d8eb058c48145b32da2e399a9567043/denote-rename-buffer.el#L151

Just try modified `(provide 'denote-rename-buffer-with-title)`  to `(provide 'denote-rename-buffer)`, and reload this file.

Is this a typo ? @protesilaos

**Comment by protesilaos** [comment]
Hello folks!

@umbrellaid it is what @Jousimies correctly points out. Somehow I changed that (a `query-replace` most probably) and it results in not loading the relevant code.

I just made the change. The new package will take a few hours to build. Please update Denote and try again.

**Comment by umbrellaid** [comment]
That fixed it, thank you.

**Comment by protesilaos** [comment]
You are welcome!
