### ISSUE TITLE
denote-rename-file: renamed file disappears from dired-buffer. Need to refresh

### ISSUE THREAD

**Issue by babusri** [protesilaos/denote#203]
This is a minor issue.
I created a note outside of denote.
I renamed it using denote-rename-file.
The file disappears from dired buffer.
I have to type a 'g' to refresh the buffer.
Is this expected behavior?

Gnu emacs 29.1 on Windows 11.

**Comment by protesilaos** [comment]
Thank you @babusri! I just applied the change.

**Comment by babusri** [comment]
Thanks

**Comment by protesilaos** [comment]
> From: babusri ***@***.***>
> Date: Fri, 15 Dec 2023 06:54:27 -0800
>
> Thanks

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
