### ISSUE TITLE
`denote-link` issue with intervening directory starting with a dot

### ISSUE THREAD

**Issue by wlharvey4** [protesilaos/denote#209]
From the Manual:

> 6 Linking Notes
> … Further, the files need to be inside the `denote-directory` **or one of its subdirectories.**. No other file is recognized.
> 

If a user’s Denote Directory `denote-directory` contains a dotted file (for example `/Users/wlh4/.local/denote/notes`), and the `notes` directory contains a subdirectory (for example `/supporting`), then the user command `denote-link` will not display any notes in the `/supporting` directory during the selection process.   This appears to be caused by `denote-file-prompt` calling, indirectly, `directory-files-recursively` with a lambda function that excludes anything that matches a file name that contains a dot:

- `denote-file-prompt` => `denote-directory-files` => `denote—directory-get-files` => 
- `denote--directory-all-files-recursively` => 
- `directory-files-recursively (denote-directory) directory-files-no-dot-files-regexp :include-directories (lambda (f) (cond`
- `…`
-  `((string-match-p “/\\.” f) nil)`  <== this matches `/.local` in the `denote-directory` as defined above and so returns `nil`, preventing that file from being added to the list of files for selection.

This appears to be a bug based upon the Manual.

**Comment by protesilaos** [comment]
Hello @wlharvey4! I just merged [pull request 212](https://github.com/protesilaos/denote/pull/212) by @jeanphilippegg. Please let me know if all is good on your end.

**Comment by l-o-l-h** [comment]
@protesilaos All good here!  Thank you.

**Comment by protesilaos** [comment]
Very well! Closing this now.
