### ISSUE TITLE
Weird buffer name for a denote file

### ISSUE THREAD

**Issue by babusri** [protesilaos/denote#214]
I created the following denote file 20231230T185805--history-of-ssh__ssh.md.
It shows up correctly in dired.

When I open the file, I see that the buffer name is #("History of ssh" 0 14 (ivy-index 0))

The front matter has
+++
title      = #("History of ssh" 0 14 (ivy-index 0))

**Comment by protesilaos** [comment]
This is strange. It seems that the minibuffer history, including the text properties, was somehow taken literally and inserted there. Have you been able to reproduce this?

**Comment by protesilaos** [comment]
As of commit `ef71032`, we no longer use minibuffer completion in those prompts. While I could not reproduce this specific issue, I recognise that completion user interfaces may do their own thing with the history, which makes our reliance on it problematic.
