### ISSUE TITLE
Use RET to answer yes-or-no prompts (was: Defaults for denote-sort-dired)

### ISSUE THREAD

**Issue by psmith1303** [protesilaos/denote#215]
I really like the new functionality you've added via `denote-sort-dired`. It solves a number of use cases I have. Thanks.

One little thing.  Both the REGEX and the Sort components have effective defaults (I can merely press enter). But the "Reverse sort (y or n)" has no default. 

It would be good if there was a default action of "y" :)

**Comment by protesilaos** [comment]
Hello @psmith1303! I am not aware of an option to make RET be interpreted as "yes" (or the previous choice) in those prompts. The Emacs function we use is `y-or-n-p`.

**Comment by Jousimies** [comment]
You can wrap a func like this:

```
(defun my/denote-sort-with-sigature ()
	(interactive)
	(denote-sort-dired (denote-files-matching-regexp-prompt) 'signature nil))
```
