### ISSUE TITLE
`denote-silo-extras` manual addition

### ISSUE THREAD

**Issue by l-o-l-h** [protesilaos/denote#216]
The manual **Section 2.5.2 The `denote-silo-extras.el`** introduces the three commands:

1. `denote-silo-extras-create-note`
2. `denote-silo-extras-open-or-create`
3. `denote-silo-extras-select-silo-then-command`

The first two commands are set up to work interactively only with a prefix argument `C-u`, but this requirement is not made known by the manual.  If a prefix argument is not provided, then the command runs the wrapped command (e.g., `denote` or `denote-open-or-create`) using the default denote directory or a previously used silo directory.   The manual could be improved by including the prefix requirement to choose a silo directory.

**Comment by protesilaos** [comment]
Hello @l-o-l-h! The commands are wrong. They should not require a `C-u` for that. I will update them now.

**Comment by l-o-l-h** [comment]
@protesilaos 
Thank you.  The new code resolves this issue beautifully.  This issue can be closed as resolved.
