### ISSUE TITLE
Wrong behavior of the letter casing of file names

### ISSUE THREAD

**Issue by Jousimies** [protesilaos/denote#220]
I know recent there is a re-construct of denote.el with sluggify keywords.

But It cannot keep keywords as camel casing after rename file, all keywords downcase instead. 

with below configuration:

```
(setopt denote-file-name-deslug-functions 
'((title . denote-desluggify-title) 
(signature . denote-desluggify-signature) 
(keyword . denote-desluggify-keyword)))
```

I do not know how to debug this problem, any help?

**Comment by jeanphilippegg** [comment]
You should use the `denote-file-name-slug-functions` variable. Try this:

```
(setq denote-file-name-slug-functions
    '((title . denote-sluggify-title)
      (signature . denote-sluggify-signature)
      (keyword . identity)))
```

This way you can have any character and casing in your
keywords. Camel case is preserved on rename. Just make
sure to avoid underscores in your keywords.

**Comment by pqks** [comment]
Hi.

I have denote (v.2.2.4) from melpa. I can't applied this solution. I copy/paste the code and nothing happens. Jousimies tell us if you emacs works.

**Comment by jeanphilippegg** [comment]
It will be part of version 2.3.0 (or 3.0.0) of Denote.
