### ISSUE TITLE
`denote-rename-buffer-mode` and `nov.el`

### ISSUE THREAD

**Issue by arsaber101** [protesilaos/denote#229]
Hi Prot,

First, thanks for your packages, and most of all thanks for your wonderful
documentation, a life saving for illiterates in programming languages like
me.

I stumble upon something that might be a bug with `denote-rename-buffer-mode`
when i am visiting `.epub` files in emacs with the `nov.el` library.

My setup :

-   emacs 29.2
-   denote 2.2.4
-   nov 0.4.0
-   All my `epub` files are stored outside my `denote-directory` and none of them
    have a `denote-filename`.
    
        (add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
        (denote-rename-buffer-mode 1)
    
    When I use `find-file` (or all the functions that call `find-file` such as
    `consult-locate`, `dired-find-file`, etc.) to open an `epub` file, the file is
    visited but instead of being displayed the buffer is buried, with
    a message in the echo area : `Wrong type argument: stringp, nil`. The
    Messages buffer shows this :
    
        denote-file-has-identifier-p: Wrong type argument: stringp, nil
    
    After 
    
        M-x  toggle-debug-on-error
    
    Here the backtrace :
    
        Debugger entered--Lisp error: (wrong-type-argument stringp nil)
        file-name-nondirectory(nil)
        denote-file-has-identifier-p(nil)
        denote-rename-buffer()
        denote-rename-buffer-rename-function-or-fallback()
        run-hooks(find-file-hook)
        after-find-file(nil t)
        find-file-noselect-1(#<buffer L'innommable - Samuel Beckett.epub> "~/L'innommable - Samuel Beckett.epub" nil nil "~/L'innommable - Samuel Beckett.epub" (4598741 2050))
        find-file-noselect("~/L'innommable - Samuel Beckett.epub" nil nil t)
        find-file("~/L'innommable - Samuel Beckett.epub" t)
        funcall-interactively(find-file "~/L'innommable - Samuel Beckett.epub" t)
        call-interactively(find-file nil nil)
        command-execute(find-file)
    
    Indeed, if I set 
    
        (denote-rename-buffer-mode 0)

The issue disappears.

So my question is, far out my comfort zone : might it be possible for the
user to disable the hook to `denote-rename-buffer` functions for some
file-types ?

Thanks again,
Bernard

**Comment by protesilaos** [comment]
Hello @arsaber101!

I just pushed a change. Can you evaluate the following and then try to open an epub file?

```elisp
(defun denote-rename-buffer (&optional buffer)
  "Rename current buffer or optional BUFFER with `denote-rename-buffer-format'.
The symbol of this function is the default value of the user
option `denote-rename-buffer-function' and is thus used by the
`denote-rename-buffer-mode'."
  (when-let ((file (buffer-file-name buffer))
             ((denote-file-has-identifier-p file))
             (new-name (denote-rename-buffer--format (or buffer (current-buffer))))
             ((not (string-blank-p new-name))))
    (rename-buffer new-name :unique)))
```

**Comment by arsaber101** [comment]
It works. Perfect. Thanks again.

**Comment by protesilaos** [comment]
You are welcome! Closing now.
