### ISSUE TITLE
Migrating from org-roam (code snippet)

### ISSUE THREAD

**Issue by papercatlol** [protesilaos/denote#23]
Hey!
I've been using org-roam for taking notes, but I've always wanted something more lightweight and simple, so I'm quite excited to try denote.

For those that are in the same boat, I'd like to share the hack that I wrote for migrating my notes from org-roam to denote (mark files that you want to convert in Dired and do M-x org-roam-convert-to-denote):

```
(defun org-roam-convert-to-denote (files dir)
  "Convert org-roam notes to denote format and insert them into
`denote-directory'. Works in Dired."
  (interactive
   (list (dired-get-marked-files t current-prefix-arg nil nil t)
         (read-directory-name "Denote directory: " (denote-directory))))
  (unless (file-exists-p dir) (error "Directory does not exist: %s" dir))

  (dolist (file files)
    (let* ((filename (file-name-base file))
           (org-roam-filename-regex
             (rx
              ;; date: YYYY-MM-DD
              (group (= 4 digit) "-" (= 2 digit) "-" (= 2 digit))
              "_"
              ;; time: HH:MM
              (group (= 2 digit) ":" (= 2 digit))
              "-"
              ;; title
              (group (* any))))
           (match? (string-match org-roam-filename-regex filename)))
      (unless match?
        (warn "Filename doesn't match org-roam-filename-regex: %s" filename))

      (let* ((date (match-string 1 filename))
             (time (match-string 2 filename))
             (title (or ;; Try to get title with spaces.
                        (denote-retrieve--value-title file)
                        (replace-regexp-in-string "_" " " (match-string 3 filename))))
             (decoded-time (date-to-time (concat date "T" time)))
             (id (format-time-string denote--id-format decoded-time))
             ;; Code from `org-roam-tag-add'.
             (keywords (with-temp-buffer (insert-file-contents file nil 0 1024)
                         (split-string (or (cadr (assoc "FILETAGS"
                                                        (org-collect-keywords '("filetags"))))
                                           "")
                                       ":" 'omit-nulls)))
             (keywords (denote--sluggify-keywords
                        (if (cdr keywords) keywords (car keywords))))
             (new-name (denote--format-file
                        (denote-directory)
                        id
                        keywords
                        (denote--sluggify title)
                        (denote--file-extension))))
        ;; Ask for confirmation when overwriting, but don't throw an error if
        ;; the user declines.
        (ignore-errors (copy-file file new-name 1))

        (with-current-buffer (find-file-noselect new-name t)
          (save-excursion
           (goto-char (point-min))
           (org-set-property "ID" id)
           ;; Fix keywords: org-roam uses default org :tag1:tag2: format, denote
           ;; uses space-separated format.
           ;; Code from `org-roam-set-keyword'.
           (org-roam-set-keyword "filetags" (string-join (ensure-list keywords) " "))
           (org-roam-set-keyword "date" (denote--date decoded-time))

           ;; Ensure newline before first heading as this is how denote looks
           ;; for front matter ending.
           (goto-char (point-min))
           (outline-next-visible-heading 1)
           (unless (looking-back "\n\n")
             (insert "\n"))

           (let ((inhibit-message t))
             (save-buffer))))
        (message "Converted %s -> %s" file new-name))))
  (denote-dired-update-dired-buffers))
```

**Comment by protesilaos** [comment]
Hello @papercatlol!

> I've been using org-roam for taking notes, but I've always wanted
> something more lightweight and simple, so I'm quite excited to try
> denote.

Just curious to know: what are the main differences between the two
packages?

[ I have not used org-roam and do not mean to start an argument here. ]

> For those that are in the same boat, I'd like to share the hack that I
> wrote for migrating my notes from org-roam to denote (mark files that
> you want to convert in Dired and do M-x org-roam-convert-to-denote)

Thanks for sharing!  If others try this and have any further comments on
it, we can create a space to collect these Do-It-Yourself snippets.  Or
just add them to the manual.

For now I add a tag for visibility.

**Comment by papercatlol** [comment]
> Just curious to know: what are the main differences between the two packages?
> [ I have not used org-roam and do not mean to start an argument here. ]

I'm pretty sure org-roam can do everything denote can at the moment, as well as caching and completion for note ids, various backlink buffers/graphs, citations, templates, external apps support and a million other features and extensions. It tracks everything via a sqlite database and I've heard people say that it can handle thousands of notes (never tested this myself). This is a very powerful package, which is kind of my issue with it - I only need to keep track of a hundred odd notes and a simpler solution that I can tailor to my needs will be much comfier.

> 
> Thanks for sharing! If others try this and have any further comments on it, we can create a space to collect these Do-It-Yourself snippets. Or just add them to the manual.
> 
> For now I add a tag for visibility.

Cool!

**Comment by protesilaos** [comment]
I see.  Thanks for the explanation!

**Comment by shrysr** [comment]
Just adding a quick comment here as an org-roam user in case it helps with Prot's curiosity. I've seen org-roam to work fine for between 1-2000 notes which is all I have :).  I may try the conversion snippet above down the line. One aspect that attracted me to denote, i think, is that it is not dependent only on Org files, or rather there is potential to mix + switch between formats. I've surely not leveraged  even a fraction of org-roam's capabilities and probably do not even know them all either, but based on a recent experience trying to setup Emacs on Windows - I think that most org-roam users are Mac/Linux or Windows WSL users, and have to necessarily be so due to the sqlite dependencies. Denote would or should work, directly with the official GNU Emacs windows binaries. This being said - I suppose anything beyond basic text editing with Emacs on Windows would need  MSYS2 or WSL and the like on Windows anyway <shrug>.

**Comment by protesilaos** [comment]
Thank you @shrysr for taking the time to write this!

**Comment by protesilaos** [comment]
Helo again!

I will close this issue as there have been breaking changes since then: we no longer support the `org-id` method of linking notes.  Further information in the release notes for version `0.2.0`: https://protesilaos.com/codelog/2022-07-04-denote-0-2-0/

Thank you for your time.
