### ISSUE TITLE
Include full file name in the links

### ISSUE THREAD

**Issue by teotenn** [protesilaos/denote#232]
Hi, is there a way to insert the links with the file's full name and the path relative to the denote directory instead of only the ID?

The default denote links are something like this:

```
[[denote:20240126T142743][Basic Elisp]]
```

And I'd like to achieve something like this:

```
[[emacs/20240126T142743--Basic-Elisp__emacs_code.org][Basic Elisp]]
```

So, the full file name, including the subfolder (in this case "emacs" folder) which exists inside my denote folder. Or if the relative path is not possible, at least the full file name, and then I could keep all my notes in one same directory. The reason is that I'd like to use denote system outside of emacs in my mobile. So far denote is the best system to organize my notes both, in emacs and my mobile, but without this links I can't really use it outside of emacs.

I have been playing with the variables `denote-org-link-format` and `denote-org-link-in-context-regexp` but I cannot figure it out. I would really appreciate your support. Thanks in advance.

**Comment by jeanphilippegg** [comment]
This left part of the link is what allows links to work in Denote (and org), ie you can click on them or have a `backlinks` buffer. Normally, it is not visible to the user. The right part is the description and is meant to be controlled by the users.

By default, the description is the file's title (and signature if present). This can be controlled by the variable `denote-link-description`. It is not yet released on gnu elpa. It will be available in Denote 3.0.0. If you have the latest code, you can try this:

```
(defun my-link-description-function (file region-text)
  (denote-get-file-name-relative-to-denote-directory file))

(setq denote-link-description-function #'my-link-description-function)
```
Your links would look like `[[denote:20240126T142743][emacs/20240126T142743--Basic-Elisp__emacs_code.org]]`. Would this be an acceptable solution?

Have a look at the default value of `denote-link-description-function` if you want your link descriptions to include the file's title or the region content.

**Comment by teotenn** [comment]
Hi, no I need rather the oposite, the left side modified so that I can use the links outside of emacs:

```
[[emacs/20240126T142743--Basic-Elisp__emacs_code.org][Basic Elisp]]
```

OR

```
[[20240126T142743--Basic-Elisp__emacs_code.org][Basic Elisp]]
```

Is this possible?

But then I guess that the part of `denote:` is what it actually opens the link right?

**Comment by protesilaos** [comment]
> From: Manuel Teodoro ***@***.***>
> Date: Sat, 27 Jan 2024 18:30:23 -0800
>
> Hi, no I need rather the oposite, the left side modified so that I can use the links outside of emacs:
>
> ```
> [[emacs/20240126T142743--Basic-Elisp__emacs_code.org][Basic Elisp]]
> ```
>
> OR
>
> ```
> [[20240126T142743--Basic-Elisp__emacs_code.org][Basic Elisp]]
> ```
>
> Is this possible?

I don't think we can achieve a universal linking system. What we do is Emacs-specific.

> But then I guess that the part of `denote:` is what it actually opens the link right?

The 'denote:' part behaves like the 'file:' link type in Org buffers, if
you have ever used that. In other words, it finds the file whose
identifier is the one specified. This link type can then be extended
with an in-file search, to determine where the cursor jumps to after
opening the file. By default, it goes to the top of the file, but there
are other options, as documented in the Org manual. Evaluate:

    (info "(org) Search Options")

With the 'denote:' link type, we have a new (in development) mechanism
to link to a heading inside the given file, by using this mechanism.

Again though, this is all Emacs-specific. Maybe there is some
system-wide method to define a link handler, but I am not aware of it
(and it would not be part of this package, anyway).

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by teotenn** [comment]
Thanks for the explanation, I'm closing the issue then and will try to find some solution for my particular case.
