### ISSUE TITLE
Hide `denote-directory` Part in Path for `denote-open-or-create`

### ISSUE THREAD

**Issue by VicZz** [protesilaos/denote#233]
Hi, 
Is there a way to hide the `denote-directory` part of the path in the candidates displayed when using the `denote-open-or-create` command? The full path is quite long, making it difficult to see the latter part of it. I am also using Vertico.

**Comment by protesilaos** [comment]
> From: Vick ***@***.***>
> Date: Sat, 27 Jan 2024 17:17:54 -0800
>
> Is there a way to hide the `denote-directory` part of the path in the
> candidates displayed when using the `denote-open-or-create` command?
> The full path is quite long, making it difficult to see the latter
> part of it. I am also using Vertico.

This is a good idea. But I do not know how to achieve this in a "visual"
way without having to remove the prefix from the underlying candidates.
What I mean by that is that the input received will still be the full
path, without us having to perform pre- and post- selection
transformations.

If you or anybody reading this has any ideas on how to achieve something
like this, I am happy to see it done.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jeanphilippegg** [comment]
I think it makes sense to actually remove the prefix from the underlying candidates and add it back in the calling functions. I have done that pull request #238.

**Comment by VicZz** [comment]
Thank you jeanphilippegg! @jeanphilippegg 

I don't quite understand how to read and understand Github pull request. Can I use it after denote is updated? Or do I need to set a variable to hide denote-directory?

**Comment by VicZz** [comment]
Thank you protesilaos & jeanphilippegg! !

@jeanphilippegg 
I don't quite understand how to read and understand Github pull request. Can I use it after denote is updated? Or do I need to set a variable to hide denote-directory?

**Comment by protesilaos** [comment]
Hello @VicZz! This change or a variant of it will be widely available in the next version of `denote`. I don't have an expected date for it, though it will likely be after February as I can barely type now.

**Comment by protesilaos** [comment]
Note that [the technical discussion is here](https://github.com/protesilaos/denote/pull/239). My question is if we can do this only as a visual effect, without affecting the actual file paths.

**Comment by VicZz** [comment]
Hello @protesilaos. Thank you very much for your reply! Or it would be nice if the `denote-open-or-create` command could be modified to only display the file name without showing the path, just like Org roam.

**Comment by protesilaos** [comment]
Hello again!

I am working on a new version of the `denote-file-prompt`. The idea is to show relative file names in all relevant commands. This is still a work-in-progress. Do you want to test it? If yes, evaluate the following and try `denote-open-or-create`:

```elisp
;; NOTE 2024-02-29 08:09:42 +0200: Based on
;; `project--read-file-cpd-relative' from the built-in project.el
(defun denote-file-prompt (&optional files-matching-regexp)
  "Prompt for file with identifier in variable `denote-directory'.
With optional FILES-MATCHING-REGEXP, filter the candidates per
the given regular expression."
  (let* ((all-files (denote-directory-files files-matching-regexp :omit-current))
         (common-parent-directory
          (let ((common-prefix (try-completion "" all-files)))
            (if (> (length common-prefix) 0)
                (file-name-directory common-prefix))))
         (cpd-length (length common-parent-directory))
         (prompt (if (zerop cpd-length)
                     "Select note: "
                   (format "Select note in %s: " common-parent-directory)))
         (included-cpd (when (member common-parent-directory all-files)
                         (setq all-files
                               (delete common-parent-directory all-files))
                         t))
         (substrings (mapcar (lambda (s) (substring s cpd-length)) all-files))
         (_ (when included-cpd
              (setq substrings (cons "./" substrings))))
         (new-collection (project--file-completion-table substrings))
         (abs-cpd (expand-file-name common-parent-directory))
         (abs-cpd-length (length abs-cpd))
         (relname (cl-letf* ((non-essential t) ;Avoid new Tramp connections.
                             ((symbol-value 'denote-file-history)
                              (mapcan
                               (lambda (s)
                                 (setq s (expand-file-name s))
                                 (and (string-prefix-p abs-cpd s)
                                      (not (eq abs-cpd-length (length s)))
                                      (list (substring s abs-cpd-length))))
                               (symbol-value 'denote-file-history))))
                    (completing-read prompt new-collection nil nil nil 'denote-file-history)))
         (absname (expand-file-name relname common-parent-directory)))
    (add-to-history 'denote-file-history absname)
    absname))
```

**Comment by protesilaos** [comment]
I am closing this now. If there is a problem, please re-open the issue. Thank you!
