### ISSUE TITLE
denote-journal feature proposal: `denote-journal-extras-link-or-create-entry`

### ISSUE THREAD

**Issue by brabalan** [protesilaos/denote#234]
Here is the proposed code for a function that links to a journal entry, creating it if necessary. It is a mix of `denote-journal-extras-new-or-existing-entry` and `denote-link-or-create`.

```emacs-lisp
(defun denote-journal-extras-link-or-create-entry (&optional date id-only)
  "Use `denote-link' on journal entry, creating it if necessary.
A journal entry is one that has `denote-journal-extras-keyword' as
part of its file name.

If there are multiple journal entries for the current date,
prompt for one using minibuffer completion.  If there is only
one, link to it outright.  If there is no journal entry, create one
by calling `denote-journal-extra-new-entry' and link to it.

With optional DATE as a prefix argument, prompt for a date.  If
`denote-date-prompt-use-org-read-date' is non-nil, use the Org
date selection module.

When called from Lisp, DATE is a string and has the same format
as that covered in the documentation of the `denote' function.
It is internally processed by `denote-journal-extras--get-date'.

With optional ID-ONLY as a prefix argument create a link that
consists of just the identifier.  Else try to also include the
file's title.  This has the same meaning as in `denote-link'."
  (interactive
   (pcase current-prefix-arg
     ('(16) (list (denote-date-prompt) :id-only))
     ('(4) (list (denote-date-prompt)))))
  (let* ((internal-date (denote-journal-extras--get-date date))
         (files (denote-journal-extras--entry-today internal-date))
         (path))
    (cond
     ((length> files 1)
      (setq path (completing-read "Select journal entry: " files nil :require-match)))
     (files
      (setq path (car files)))
     (t
      (save-window-excursion
        (denote-journal-extras-new-entry date)
        (save-buffer)
        (setq path (buffer-file-name)))))
    (denote-link path
                 (denote-filetype-heuristics (buffer-file-name))
                 (denote--link-get-description path)
                 id-only)))
```

**Comment by protesilaos** [comment]
Thank you @brabalan! Do you want to send this either as a patch or a pull request? This way your contribution is recorded in the Git history.

**Comment by brabalan** [comment]
done as #243

**Comment by DivineDominion** [comment]
Sorry to hijack: I've fiddled with save-excursion as well to get to the filename. What do you think about extracting a function that just returns the path? Then rewire the creation and link functions to use that internally.

It's a bit backwards maybe because underlying it all is a side effect function `denote-journal-extras-new-entry` that does all the work relying on the original `denote` function which figures out the file name, does everything necessary for a new file, and visits it.

If side effect and path finding were separate, composition could be improved a lot. If I understand the code correctly, it's not a trivial refactoring, then please ignore :)

**Comment by brabalan** [comment]
A denote function that creates a note could return the path to that note, but I think this is quite a big change indeed.

**Comment by protesilaos** [comment]
Hello @DivineDominion! Do you want to send the relevant code? If we can make it more flexible, I am happy to do so. In the meantime, I am closing this to keep things organised (I merged the pull request from @brabalan). Thank you!
