### ISSUE TITLE
denote requires links to be inserted in notes

### ISSUE THREAD

**Issue by brabalan** [protesilaos/denote#235]
When creating a denote link to a target file, the source file (where the link is inserted) is checked to be a note using `denote-file-is-note-p`. The reason for this restriction is not clear and it breaks some workflows where one refers to notes from files that are not notes, such as todo files.

(See https://lists.sr.ht/~protesilaos/denote/%3C324298a6-4742-4f9b-916e-e26fd6949373%40ziazoo.co.uk%3E for some context.)

**Comment by pprevos** [comment]
Removing this restriction is useful when I am Writing books and I add links to my notes in sections I don't export. So would be great in my workflow.

**Comment by jeanphilippegg** [comment]
I will create a pull request soon to remove this check. I added it as part of the development in #222, but I had not though about this use case. Sorry about that!

**Comment by protesilaos** [comment]
I just merged the PR from @jeanphilippegg. I thought we already had this in place at some point. But maybe we discussed it but never implemented it...

**Comment by pprevos** [comment]
Works great, thanks Prot.
