### ISSUE TITLE
Setting denote-directory in .dir-locals.el doesn't override denote-directory, but is a silo flag

### ISSUE THREAD

**Issue by d-qoi** [protesilaos/denote#244]
Hello!

I've found that denote uses denote-directory defined in .dir-locals differently than how it uses it globally. 

It uses any non-nil binding of denote-directory as a flag that the directory the .dir-locals is defined in should be the root of a silo, rather than the value that denote-directory is bound to.

I've got what may not be the most common use case, in which I want to keep notes for each project in a dedicated folder in the project root. I use a .dir-locals.el in the project root for some project specific customization, style settings and such, and as it's a project root. I'd rather not have my project roots cluttered further with my notes, all things considered.

I noticed in the code that when using denote in a directory with a .dir-locals in the root, denote will always use that parent folder as the root directory.
It all seems to be this due to this specific check.
```
(defun denote--default-directory-is-silo-p ()
  "Return path to silo if `default-directory' is a silo."
  (when-let ((dir-locals (dir-locals-find-file default-directory))
             ((alist-get 'denote-directory dir-local-variables-alist)))
    (cond
     ((listp dir-locals)
      (car dir-locals))
     ((stringp dir-locals)
      dir-locals))))
```
The specific value of the locally set denote-directory is grabbed, but never used beyond just a check to see if it's bound at all.
I ended up modifying this function to get the behavior I wanted: the ability to set the denote-directory value explicitly with .dir-locals, and retain the behavior of checking to see if it's bound so denote knows to use the root at a silo. 

```
(defun denote--default-directory-is-silo-p ()
  "Return path to silo if `default-directory' is a silo."
  (when-let ((dir-locals (dir-locals-find-file default-directory))
             (local-val (alist-get 'denote-directory dir-local-variables-alist)))
    (cond
     ((and (stringp local-val)
           (file-directory-p local-val))
      local-val)
      ((listp dir-locals)
       (car dir-locals))
      ((stringp dir-locals)
       dir-locals))))
 ```
 
 I know I could have gotten around this by setting user-enforced-denote-directory in my dir-locals, but that doesn't seem to be what the variable is for, looking at the docs.
 
 The docs also specify that a path should be specified for the denote-directory in some circumstances, subdirs in silos, which may cause confusion for others if they specify a path that is not strictly to the parent directory of the .dir-locals. I not attempted to do that yet.

**Comment by MirkoHernandez** [comment]
I believe I had similar issues, I started modifying the original denote functions to get the desired functionality but this stopped working when the denote-directory functions changed (I guess after version 2.0 ). Anyway `denote-user-enforced-denote-directory` provides everything for the workflow I'm using -  two custom functions for creating the notes and for everything else (renaming, keywords) the regular denote functions.

``` emacs-lisp
(defun my/denote-here ()
 (interactive)
 "Creates a note in default-directory."
 (let ((denote-user-enforced-denote-directory default-directory )) 
   (call-interactively 'denote)))
```

**Comment by jeanphilippegg** [comment]
I have made a pull request that removes `denote-user-enforced-denote-directory`. Working with `denote-directory` should behave like other user options, meaning you can `let` bind it as you did, or use it in a `.dir-locals.el`.

See pull request #246.

**Comment by d-qoi** [comment]
Yup, that would make Denote support what I'm trying to do!

**Comment by MirkoHernandez** [comment]
@jeanphilippegg  The problem with that approach is that it will break links that point outside the default directory (unless you are in the root of the silo -  try linking, or finding a note from a nested directory to a parent directory). I've been using  `denote-user-enforced-denote-directory` without any issue for months, it is a very simple  way  to accomplish @d-qoi intended workflow. 

A more general solution would probably be the possibility of setting different silo types. But currently (as I understand it) the linking  and the note creation  functionality is intertwined,  `denote-directory` and  `denote--default-directory-is-silo-p` work a similar way no matter the intended action.

**Comment by jeanphilippegg** [comment]
After verification, we mostly never use the variable `denote-directory`, but instead rely on the function `(denote-directory)` which uses `denote-user-enforced-directory` or `denote-directory` in the end.

I think your current setup will not be affected by the changes in #246. If you are able to give it a try and confirm if everything still works, that would be ideal.

**Comment by MirkoHernandez** [comment]
Sorry, maybe I misunderstood the proposed changes to `denote--default-directory-is-silo-p`. That function or  some other similar one was used to get the directory of the silo, in older versions of denote it used the value set by denote-directory (in my use case the actual value of  `default-directory`) now it defaults to the location of  .dir-locals.el, which works great for finding links. 

If `denote--default-directory-is-silo-p` were to return the `default-directory` value (I though this was @d-qoi suggested change) then some of the  link functions would stop working, they start looking for matches from the `default-directory` and not the entire silo.

**Comment by jeanphilippegg** [comment]
I see. This is all confusing and it is the kind of confusion that I hoped to remove with my pull request. :)

I am still unsure as to what is your specific usage of Denote. I could make a few tests on my side, but my guess is that it would not be broken. Let me know if you would like me to try some setups (the directories, the locations of `.dir-locals.el`s and their content) just to be sure!

**Comment by MirkoHernandez** [comment]
@jeanphilippegg  I think `denote-user-enforced-denote-directory`  works great, it covers @d-qoi (I'm not sure why you would not want use that variable)  use case and I guess it should support almost any workflow. I  never call `denote` directly tho,  this can be confusing for new users who want a specific workflow and find out that setting up dirs.locals.el is not enough.

This version of denote works extremely well for me. In the old version  I used to tinker with `directory-is-silo-p`
and `denote-link-ol-follow `  to get the desired results, now I just use a simple wrapper to denote and everything works.

**Comment by d-qoi** [comment]
I would rather not bind to `denote-user-enforced-denote-directory` in .dir-locals as the docs call it out specifically for let binding, which is not my use case.

The behavior change of how denote-directory is used in global config and local config with .dir-locals is not well enough explained in the docs, in my opinion, and the reason for that behavior change seems to mostly be a design decision, that is not currently explained in the docs, and not an implementation restriction.

The issue I am calling out is that the expected behavior of binding a variable called `denote-directory` locally doesn't actually change the value of `denote-directory` to the local value, which is not consistent.
The local value bound to the correct path *is already needed* if we are using through sub directories in a silo.
From the docs:
`
IMPORTANT If your silo contains sub-directories of notes, you should replace default-directory in the above examples with an absolute path to your silo directory, otherwise links from files within the sub-directories cannot be made to files in the parent directory. For example: 
`

The behavior is inconsistent within denote already, which is confusing in my opinion. The suggested change I put in initially would make it consistent without breaking existing behaviors.

**Comment by MirkoHernandez** [comment]
I agree that the silo behavior is confusing when using `default-directory`  but for your particular use case @d-qoi  using  `denote-user-enforced-denote-directory` in a function that wraps denote should work, please try this approach, and confirm if it works or what is missing.

> The behavior is inconsistent within denote already, which is confusing in my opinion. The suggested change I put in initially would make it consistent without breaking existing behaviors.

It is confusing but I tried your exact approach about a year a go and it breaks the link functions for the reasons mentioned above.

A possible  solution: separate the behavior of  `denote--default-directory-is-silo-p`  and `denote-directory` when it is called for link usage and when it is called for creating notes. This was my approach, until `denote-directory` changed and it became unnecessary.

**Comment by d-qoi** [comment]
That approach will work. I can wrap entry points for denote that I want to use to force a value for `denote-directory` using `denote-user-enforced-denote-directory`.  However, I'm not sure how wrapping a function to let-bind `denote-user-enforced-denote-directory` for entry points, in my use case, would be different than binding it in a .dir-locals file, which is something I am trying explicitly to avoid.

How does what I suggested initially break links? I have not seen any issues with links so far, even between silos?

**Comment by MirkoHernandez** [comment]
@d-qoi I initially read the code and assumed that you were using the local-value (this is what I did, reading the value of `default-directory` if set) but  trying  the suggested function it turns out that  the  stringp test ignores the `default-directory`  variable and the functions uses the root of the silo (the default behavior).

Those changes seem to improve the default behavior when using a **string** as a directory ( links would not break) . All the notes created  would go into the specified directory,  is the expected result ?.
I guess most users are using that approach but I'm using  `default-directory` for note creation, using it in `denote--default-directory-is-silo-p`  breaks the linking functionality.

**Comment by d-qoi** [comment]
Ah, assuming you mean `denote-directory` instead of `default-directory` that is correct. 

If I define `denote-directory` as a string, and as a valid directory path, in .dir-locals then `denote--default-directory-is-silo-p` returns that local value. If it is not a string or valid path, `denote--default-directory-is-silo-p` returns the parent dir of the .dir-locals file found in the `default-directory` or a parent, the original behavior of the function.

From the example in the docs, setting `((nil . ((denote-directory . default-directory))))` in the .dir-locals will fail the stringp check, as the alist-get will return the symbol `'default-directory` rather than the value `default-directory` holds.

**Comment by jeanphilippegg** [comment]
`default-directory` is never actually evaluated if `denote-directory` is set to it.

Anyway, I think this might all be overengineered at this point. I still think that the changes I proposed will not break any current setup, while allowing the setup that you explained in your inital post to work. It would help if you gave a setup that could be tested, something like a directory structure with the `.dir-locals.el` used. I could test if it breaks. I am still confused as to what could break.

I think that if we have `denote-directory` behave like any other Emacs variable, all this complexity would go away.
