### ISSUE TITLE
Make denote-journal-extras--entry-today file name format customizable 

### ISSUE THREAD

**Issue by DivineDominion** [protesilaos/denote#245]
For context, I have date stamps like 202402062310 without a "T" in the middle and accuracy to the minute.

```elisp
(setq denote-id-format "%Y%m%d%H%M"
      denote-id-regexp "\\([0-9]\\{8\\}\\)\\([0-9]\\{4,6\\}\\)")
```

I found out that `denote-journal-extras--entry-today` has to be overridden in my init.el because the format string is hard-coded. The version I'm using now is:

    (defun denote-journal-extras--entry-today (&optional date)
      (denote-directory-files
       (format "%s[0-9]\\{4,6\\}.*_%s"
               (format-time-string "%Y%m%d" date)
               denote-journal-extras-keyword)))

Finding existing notes work with that.

I wanted to propose a customizable variable setting, but not sure how to best approach this:

- introduce `denote-journal-extras-format` for `"%s[0-9]\\{4,6\\}.*_%s"` sounds like it's not enough of an abstraction;
- introducing a new function with just the `(format ...)` part doesn't help with customizability; so maybe that plus
- adding a function reference as a customization point?

```elisp
(defun denote-journal-extras--title (&optional date)
  (format "%s[0-9]\\{4,6\\}.*_%s"
           (format-time-string "%Y%m%d" date)
           denote-journal-extras-keyword))

(defcustom denote-journal-extras-title-format-function #'denote-journal-extras--title
  "Function to create today's journal file."
  :type '(choice (function-item :tag "Default journal title" denote-journal-extras--title)
                 function)
  :group 'shell-maker)

(defun denote-journal-extras--entry-today (&optional date)
  "Return list of files matching a journal for today or optional DATE.
DATE has the same format as that returned by `denote-journal-extras--get-date'."
  (denote-directory-files
   (funcall denote-journal-extras-title-format-function date))

;; customization:
(defun ct/denote-journal-title (&optional date)
  "YMDHM title format"
  (format "%s[0-9]\\{4,6\\}.*_%s"
         (format-time-string "%Y%m%d" date)
         denote-journal-extras-keyword)))
(setq denote-journal-extras-title-format-function #'ct/denote-journal-title)
```

**Comment by protesilaos** [comment]
Hello @DivineDominion! In principle, I am fine with making `denote-journal-extras--entry-today` more flexible. Though I wonder what you think about how this impacts the `denote-journal-extras-title-format`.

Providing the option for a custom function does seem like the best abstraction.

**Comment by protesilaos** [comment]
If this is still ongoing, please let me know. Closing it in the meantime. Thank you!
