### ISSUE TITLE
All commands must honour `denote-prompts`, mutatis mutandis

### ISSUE THREAD

**Issue by protesilaos** [protesilaos/denote#247]
I just pushed this:

```
commit 9a764923bca526d8e4c611dcce7f3f88b682d824
Author: Protesilaos Stavrou <info@protesilaos.com>
Date:   Sun Feb 11 10:49:14 2024 +0200

  Add WORK-IN-PROGRESS implementation of 'denote-rename-file' that honours 'denote-prompts'
  
  I have to stop because my hand is in pain... But this is already
  looking promising. Putting it in a new branch for now to pick it up
  later.

 denote.el | 62 +++++++++++++++++++++++++++++++++++++++-----------------------
 1 file changed, 39 insertions(+), 23 deletions(-)
```

The branch is `rename-honours-denote-prompts`. The idea is to make all rename commands do the right thing (i) according to their specificities while (ii) respecting the `denote-prompts` where necessary.

Long-term, we want all commands to honour the `denote-prompts` if it makes sense. But let's start with these.

CC @jeanphilippegg @vedang who may be interested (the former because of the implication on duplicate IDs, the latter because we recently did the same for `denote-org-extras-extract-org-subtree`).

**Comment by vedang** [comment]
This is so cool @protesilaos ! I looked at the code and tested the following scenarios successfully:

- Rename a note with `M-x denote-rename-file`
- Rename a note with point on filename Dired buffer
- Rename a note with using front-matter (check that `denote-prompts` is not invoked)

Post that, I checked to see which code-paths could be changed to respect `denote-prompts`.

The following paths already call `denote` or other commands interactively and therefore respect `denote-prompts` correctly:
- `denote-region`
- `denote-open-or-create`
- `denote-link-or-create`
- `denote-link-after-creating`

The following commands use a fixed list, and therefore overwrite `denote-prompts`:
- `denote-type`
- `denote-date`
- `denote-subdirectory`
- `denote-template`
- `denote-signature`

All of these can be modified to use `denote-prompts`, which is a change I am submitting on top of the current commit (see #248).

Finally, `denote-org-capture` uses `denote-prompts`, but I didn't look at this bit of the code deeply.

**Comment by protesilaos** [comment]
Thank you @vedang! I will merge your PR, subject to a stylistic change noted there.

> Finally, `denote-org-capture` uses `denote-prompts`, but I didn't look at this bit of the code deeply.

I have not tested it lately, but I believe everything is okay with it.

If we have any other cases, let's discuss them here and proceed accordingly.

I will continue work on the `rename-honours-denote-prompts` branch as soon as possible. Then merge everything into `main`.

**Comment by protesilaos** [comment]
I just merged everything into `main`. I made lots of changes/refinements to ancillary functions as well.

**Comment by protesilaos** [comment]
I think we are done with this for now. If there is any command we missed, we can always update it later. Thanks!
