### ISSUE TITLE
denote-directory : possible problem with symbolic links

### ISSUE THREAD

**Issue by jf7t2gd1n** [protesilaos/denote#254]
When I include a link, such as in, for example:
(setq denote-directory "~/link_to_a_directory")
then
M-x denote
does not seem to work. After entering something at the prompt
File title: ttt
it seems it does not finish.

Thanks. Best regards.

**Comment by protesilaos** [comment]
I cannot reproduce this with Emacs 30. I am not sure what is affecting this.

Can anyone else reproduce what @jf7t2gd1n reports?
