### ISSUE TITLE
Support using id and title in backlinks

### ISSUE THREAD

**Issue by kostajh** [protesilaos/denote#255]
When inserting backlinks into a file, we have an option to use `:id-only nil` or `:id-only t`. I'd like to have another option like `:include-id` so that the linked item includes both the id and the title. 

My motivation is that I have a bunch of notes that use the same title (e.g. "1-1 Someone"). I link these in a notes document specific to "Someone". I'd really like to be able to easily see the date for the note, along with the title of the note.

**Comment by jeanphilippegg** [comment]
Configuring the link descriptions will be available through the variable `denote-link-description-function` in version 3.0.0. If you are using the latest code, you can put this in your configuration:

```
(defun my-denote-link-description-with-id-and-title (file _region-text)
  (let* ((file-type (denote-filetype-heuristics file))
         (identifier (denote-retrieve-filename-identifier file))
         (title (denote--retrieve-title-or-filename file file-type)))
    (concat identifier ": " title)))

(setq denote-link-description-function #'my-denote-link-description-with-id-and-title)
```

Have a look at the documentation of `denote-link-description-function` and its default value.

**Comment by kostajh** [comment]
Ah, cool. Thanks for the information and the code.

**Comment by protesilaos** [comment]
@jeanphilippegg I notice there is no mention of `denote-link-description-function` in the manual. Do you want to add something, or shall I do it?

Closing this now, since we can consider it done. Thank you!

**Comment by jeanphilippegg** [comment]
You can do it! I did not document it in the manual because I did not know where it would go. `denote-link-description-function` is also just a `defvar` instead of a `defcustom`. We can change this as I think it is useful as an option to users.
