### ISSUE TITLE
Suggestion to put Denote's power forward and ease its maintenance

### ISSUE THREAD

**Issue by jeanphilippegg** [protesilaos/denote#257]
There has been a lot issues lately of users wanting support for their
specific use cases. I think they are all valid and should be supported.
However, I think that the convenience functions/mechanisms that are
provided hide the real hackability/composability of Denote.

As a concrete example, let's say someone needs the following three
functions:

```
(defun my-denote-journal-command ()
  (let ((denote-prompts '(title)
         (denote-forced-keywords '("journal"))))
     (call-interactively #'denote)))

(defun my-denote-command-for-work ()
  (let ((denote-directory "~/work/")
         (denote-prompts '(title signature)))
     (call-interactively #'denote)))

(defun my-denote-link-command-for-work ()
  (let ((denote-directory "~/work/")
         (denote-link-description-function #'function-that-includes-sig-and-title)))
     (call-interactively #'denote-link)))
```

As can be seen, Denote really can be configured "easily" by a user for
very specific use cases. Commands can be defined by users, as above, and
arranged in transient, prefix keymaps, hydras, etc.

Right now, there are various convenience commands that try to handle
many specific needs. These include: the convenience functions
(`denote-signature`, `denote-date`, etc.), the `*-with-command`
functions, functions in `denote-silos-extras.el` and
`denote-journal-extras.el`, `denote-link-with-signature`, etc.

These convenience commands do not cover all the possibilities and they
are easily replaced by simple user configurations.

Maybe it would be benefic to focus on providing a set of core
functionalities from which users can build a note-taking system adapted
to their personal needs. I think this is in line with Denote's
philosophy. Various use cases would be listed in the manual.

The benefits would be:
- The power of Denote would be put forward, highlighting all the
  possibilities.
- All current use cases would still be supported.
- The maintainance would be easier.

What do you think?

**Comment by protesilaos** [comment]
Hello @jeanphilippegg and thank you for starting this discussion!

> Maybe it would be benefic to focus on providing a set of core
functionalities from which users can build a note-taking system adapted
to their personal needs. I think this is in line with Denote's
philosophy. Various use cases would be listed in the manual.

I agree with this approach and am happy to slim down or streamline parts of what we have.

I think it is helpful to have some examples built in to our code base, not just the documentation. This way, users can try existing code to see how it works before committing fully to their custom variants.

I note this because I know from private exchanges that even these "easy" functions can be tricky for beginners.

**Comment by jeanphilippegg** [comment]
Ok, I will create a lot of changes on my fork of Denote's code (from where I do my pull requests). I will push them in 1-2 weeks. This will not be meant as code to be directly merged into Denote, but it will serve as a more concrete example of what I have in mind. Then, we can check what is desirable for Denote and bring it back.

**Comment by jeanphilippegg** [comment]
Just letting you know that I will not be able to make substantial contributions (such as this one) until mid-march, so a few more weeks.

Here's what I have planned for Denote:

- Suggest the above changes where some mechanisms are removed and examples on how to configure Denote are presented in the manual.
- Some final touches to the file naming scheme: Remove the remaining limitations (the dot character that is not allowed and the underscore that is not allowed in keywords) and allow reordering the file name components as per an item in your wishlist. I have some ideas for all this.
- Implement what was discussed in #256 to allow setting some values for `denote` commands.
- Streamline the specification of `denote-file-types`. My goal here is to be able to "deconstruct" a note (with its front matter) easily with a precise specification. For example, retrieve a note's content as well as any information in the front matter. This could be useful for someone that wants to create an org-roam converter or Denote's own functions. For example, you currently look for two "newlines" as a way to retrieve the content of a note in a dblock function.

**Comment by protesilaos** [comment]
> Just letting you know that I will not be able to make substantial contributions (such as this one) until mid-march, so a few more weeks.

That's fine, no pressure!

Given the scope of this plan, I think it is better to release the new version beforehand as `2.3.0`. Then we can push for `3.0.0` and make these more ambitious changes there.

What do you think?

**Comment by jeanphilippegg** [comment]
The current changes are already quite big (file names are less restricted, linking is more flexible, reworked sluggification, removed `denote-user-enforced-denote-directory`). They are both big sets of changes.

It depends on when you intend to make a release. I am fine with what you will decide!

**Comment by protesilaos** [comment]
> It depends on when you intend to make a release. I am fine with what you will decide!

Thank you! I will try to cut a release before mid-March. But I cannot promise because typing at length is not feasible and it will be hard to produce the change log (which is naturally going to be long). Though I will try.

If I cannot make it, then we can discuss how best to handle the changes. Maybe they can live in a separate branch for a little while. Either way, I do not want this to be a block for us. The intent is to proceed with your plan and consider the technicalities as we go.

**Comment by jeanphilippegg** [comment]
I am closing this as I have no immediate proposals.

What I had in mind was:
- Reorganize the code to separate the "core" from the extra commands.
- Have better names for the extra functions.
- Update the manual to put more focus on the customizability of Denote.

But what we have now is good and I have no concrete code to show.
