### ISSUE TITLE
Use `package-lint-main-file` variable to allow symbols to not be prefixed by the file's name

### ISSUE THREAD

**Issue by jeanphilippegg** [protesilaos/denote#259]
There is a variable `package-lint-main-file` that allows a package to be split into multiple files without having to prefix all symbols with the new file's name. This means that we only need to make sure that symbols start with `denote-`. This would allow for more user-friendly names in files like `denote-org-extras.el` and `denote-silo-extras.el`.

I also want to point out that `package-lint` checks are currently disabled in all files but `denote.el` because checks are only enabled in files with a `Package-Version:` or `Package-Require:` header. This means that we could already not prefix the symbols with the file's name. It would probably be better to enable `package-lint` on those files and make use of the `package-lint-main-file` variable though.

See this [link](https://github.com/purcell/package-lint/pull/173) for more information.

**Comment by protesilaos** [comment]
Good to know! This solves the linting issue, though having some pseudo-namespacing can be helpful as well. Especially when the user tries to find a command with `M-x`, where adding a prefix like `denote-org-extras-` will help them find what they are looking for.

**Comment by jeanphilippegg** [comment]
I agree. It is more the `-extras` part that seemed less user-friendly.

**Comment by protesilaos** [comment]
The reason I added the `-extras` was to indicate that those are "optional" features. For example, there are users who do not do anything fancy with Org, so the "Org extras" are probably not useful to them. Though, yes, I am happy to tweak things.

An alternative we may consider for long symbols is the built-in shorthands feature. Have you ever seen it? Basically, we can use something like `doe` as a prefix to stand for `denote-org-extras`.

Evaluate:

```elisp
(info "(elisp) Shorthands")
```

**Comment by protesilaos** [comment]
I have thought about this again. I say we keep it as-is because it may create other issues with prefixing names in files.

**Comment by jeanphilippegg** [comment]
Sorry, I forgot to respond to this.

> An alternative we may consider for long symbols is the built-in shorthands feature. Have you ever seen it? Basically, we can use something like `doe` as a prefix to stand for `denote-org-extras`.

No, I had never seen it! This is nice and may be useful, though I don't think we need it for Denote.

That's okay if there is nothing changed for now. I just intended to bring awareness to this variable. If we develop new code, it is not necessary to have the file name used as a prefix for its commands. We just need to prefix everything with `denote-` and choose good names without other restrictions.

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Mon, 18 Mar 2024 17:54:50 -0700
>
> Sorry, I forgot to respond to this.

No worries!

>> An alternative we may consider for long symbols is the built-in
>> shorthands feature. Have you ever seen it? Basically, we can use
>> something like `doe` as a prefix to stand for `denote-org-extras`.
>
> No, I had never seen it! This is nice and may be useful, though I
> don't think we need it for Denote.
>
> That's okay if there is nothing changed for now. I just intended to
> bring awareness to this variable. If we develop new code, it is not
> necessary to have the file name used as a prefix for its commands. We
> just need to prefix everything with `denote-` and choose good names
> without other restrictions.

Fine, we keep this in mind. I think this is especially useful for
internal stuff and/or for symbols that are meant for developers. We can
revisit this if we have a good use-case.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jeanphilippegg** [comment]
Actually, I would have said the opposite: it is more useful for
user-facing commands.

But maybe we are not talking about the same thing. What I meant is that
users do not need to know how files are organized. Say we were to split
`denote.el` into multiple files (just to change the organization). It would
be less user-friendly to have `denote-renaming-commands-rename-file`,
`denote-org-org-capture`, `denote-lib-directory`,
`denote-core-known-keywords`, etc.

For the same reason, `denote-silo-extras-create-note` seems less
user-friendly than `denote-silo-create-note` or
`denote-create-note-in-silo`. The file name is still
`denote-silo-extras.el`, but the symbols can be anything (starting with
`denote-`).

This is not so bad in the current state because we mostly develop in
`denote.el`. We can keep this in mind if we want to rearrange files later.
We don't have to prefix symbols with the file name.
