### ISSUE TITLE
Proposing to remove Denote extension "modules" from the source

### ISSUE THREAD

**Issue by nobiot** [protesilaos/denote#264]
Regarding this comment in [the source](
https://github.com/protesilaos/denote/blob/main/denote.el#L4468C1-L4471C36)

```emacs-lisp
;; TODO 2024-02-25: I think these do not belong in denote.el.  We
;; should have another file, like "denote-modules.el" for users who
;; want to opt into these features.
```

I agree with this comment. I wrote this part while ago when Denote development was still in an early stage.I propose that the part be entirely removed from the source.

I suspect I am the only user for the modules, and I have factored out what I need from them, so there is no impact for me.

There was not much discussion on it in the SourceHut mailing list when it was in use. I think it is a technical debt now and I would not like it become your maintenance burden.

I will leave it to you for the timing of the removal.

**Comment by protesilaos** [comment]
Hello @nobiot!

> I propose that the part be entirely removed from the source.

You mean to remove it completely?

I know that the project.el parts are probably not useful anymore because we do not use the project file prompt (it did not support all the features we need). The rest I am not sure.

> I will leave it to you for the timing of the removal.

I think the coming days are suitable for this, because I will try to publish a new version within the coming weeks. But I do not mind if we do it later and then bundle it with the new series of changes, such as those outlined by @jeanphilippegg here: https://github.com/protesilaos/denote/issues/257.

**Comment by nobiot** [comment]
Hi @protesilaos Prot :)
> You mean to remove it completely?

Yes, that's my proposal, but I have no objection if you decide to keep it in a separate .el file. Your call.

> I know that the project.el parts are probably not useful anymore because we do not use the project file prompt (it did not support all the features we need). The rest I am not sure.

The project module was originally intended for those who do not use `git` or other tool, perhaps it's no longer necessary.

> I think the coming days are suitable for this, because I will try to publish a new version within the coming weeks. But I do not mind if we do it later and then bundle it with the new series of changes, such as those outlined by @jeanphilippegg here: #257.

I don't think I will be able to support these modules much; this is also a reason for my proposal. If they are not used, why do we keep them? It would be a maintenance burden for you and me. This was the thought I had when I proposed the removal.

**Comment by protesilaos** [comment]
Thank you @nobiot!

I will take a closer look at them and act accordingly. I have the impression they are still useful, if not in full then at least in part. I am, in particular, interested in the project.el integration because the file prompt we have now does not show relative file paths.

**Comment by protesilaos** [comment]
Okay, I removed them. The project-like file prompt can be done on its own. I updated it. Thank you!

**Comment by nobiot** [comment]
@protesilaos Thank you!
