### ISSUE TITLE
savehist mode doesnt work anymore

### ISSUE THREAD

**Issue by mahmoodsheikh36** [protesilaos/denote#265]
after i updated the package, it seems savehist-mode doesnt work anymore with denote's menus like the one for creating new files, as the menu isnt sorted anymore and last entered prompts also dont affect future prompts, after a brief look at the commit history im suspecting this could be related to https://github.com/protesilaos/denote/commit/a0796ef2d365728e9c28cc8704bb41cbcb381230?

**Comment by protesilaos** [comment]
Hello @mahmoodsheikh36!

You mean that you do not get your previous inputs in the title prompt? If so, this is by design, per commit `ef71032`. The reason is that we cannot rely on that data to be correct. I had one case where the input "some text" was turned into a file system path. Plus, it confuses users who mistake it for an "open file" prompt.

**Comment by mahmoodsheikh36** [comment]
> Hello @mahmoodsheikh36!
> 
> You mean that you do not get your previous inputs in the title prompt? If so, this is by design, per commit `ef71032`. The reason is that we cannot rely on that data to be correct. I had one case where the input "some text" was turned into a file system path. Plus, it confuses users who mistake it for an "open file" prompt.
 
hey there!
i see, that was what i meant indeed, and i do use it as a prompt to open notes, i thought that was the whole purpose of the `denote-open-or-create` function.
for reference of anyone who stumbles upon this, i might aswell state that i got the behavior i used to have by pinning it to an older commit that i picked randomly (kinda):
```lisp
(use-package denote
  :elpaca ( :fetcher github :repo "protesilaos/denote" :ref "55dcf23")
  :config
  ...
```
on another note, this encouraged me to implement the functionality that i was missing from org-roam, that allows for the usage of aliases and gives a prompt for the titles of notes to open (only for org files), this may be worthy of its own issue/pull request but im hesitant about it because the code is a little hacky as it greps for the patterns rather than using the org api:
```lisp
(defun my-notes-open-by-title ()
  "open an org file in `denote-directory' by grepping for its name, either by the #+title keyword or by the #+alias keyword."
  (interactive)
  (let* ((grep-results
          (split-string
           (shell-command-to-string
            (format "grep '#+title:\\|#+alias:' %s/*.org" denote-directory))
           "\n"))
         (titles (mapcar (lambda (line) (cadr (split-string line ":[ ]+")))
                         grep-results))
         (picked-title (completing-read "title: " titles))
         (picked-title-index (cl-position picked-title titles :test #'equal)))
    (if picked-title-index
        (let* ((entry (elt grep-results picked-title-index))
               (filepath (if entry (car (split-string entry ":")) nil)))
          (find-file filepath))
      (denote picked-title))))
```
this works wonderfully with savehist-mode and is instantaneous even though i have more than ~1.5k org files, so the fact that it opens all files and searches them may not be as problematic as it may seem at first.

**Comment by protesilaos** [comment]
> i got the behavior i used to have by pinning it to an older commit that i picked randomly (kinda)

Maybe it is better to review the change I made? I could be wrong and it is fine to keep it. Or we can mention it in the manual. Or we can have a user option to pick a style of prompt between simple and completion-powered. I am open to ideas. Pinning to a specific commit works short-term, but you will not get any updates.

> this may be worthy of its own issue/pull request but im hesitant about it because the code is a little hacky as it greps for the patterns rather than using the org api

The idea is good, though yes it needs to read the file contents. The constraint for us is that we want, in principle, to have core functionality that works for any file type. Though we do have the `denote-org-extras.el` for stuff that definitely cannot be in the core (and must be provided as an optional feature).

**Comment by protesilaos** [comment]
I have decided to bring back history completion. It is now subject to a user option. See [commit `334f567`](https://github.com/protesilaos/denote/commit/334f5675f7194ffc7f087ae0f9558cf6ab9af858).
