### ISSUE TITLE
`org-capture` creates CUSTOM_ID property when `denote-org-store-link-to-heading` is non-nil

### ISSUE THREAD

**Issue by krisbalintona** [protesilaos/denote#267]
Hello, I am reporting behavior that I believe is an issue, though I am not entirely sure if change is called for within denote or not.

The behavior is this: when calling `org-capture` in an org file, if `denote-org-store-link-to-heading` is non-nil, then denote will create a new CUSTOM_ID (assuming there isn't already one). This is undesirable, since most times I am calling `org-capture` from a file, I do not want a new CUSTOM_ID to be created.

After some debugging, I realized this was because `org-capture` calls `org-store-link`:
```
...
(annotation (if (and (boundp 'org-capture-link-is-already-stored)
				org-capture-link-is-already-stored)
			   (plist-get org-store-link-plist :annotation)
			 (ignore-errors (org-store-link nil))))
...
```
And `denote-link-ol-store` creates a CUSTOM_ID if one isn't already present (via `denote-link-ol-get-id`).

I'm not sure if this is idiosyncratic behavior or not. In my experience, I've tried no other packages that have produced this unintended behavior. As such, I'm not sure if this calls for a change in my configuration or in denote. Perhaps denote should adhere to the value of `org-id-link-to-org-use-id`? But again, I'm not sure what the proper interaction is to begin with. (I also don't recall, off the top of my head, other packages that implement an equivalent feature, so I can't refer to other existing codebases.)

Also, regarding the versions of these packages, I am on the master branch for both Org and Denote.

**Comment by protesilaos** [comment]
Hello @krisbalintona and thank you for taking the time to report this!

> This is undesirable, since most times I am calling `org-capture` from a file, I do not want a new CUSTOM_ID to be created.

Are these files Denote files or does this happen with all Org files? Is setting `denote-org-store-link-to-heading` to nil a solution?

> I'm not sure if this is idiosyncratic behavior or not. In my experience, I've tried no other packages that have produced this unintended behavior. As such, I'm not sure if this calls for a change in my configuration or in denote. Perhaps denote should adhere to the value of `org-id-link-to-org-use-id`?

If I am reading this correctly, the `org-id-link-to-org-use-id` applies to the `ID` property and only checks the `CUSTOM_ID` if necessary. We are not touching the `ID` here: we only do the `CUSTOM_ID`. To your point though, having one user option depend on the value of another (in another package) makes things more complex. A user needs to update one variable and then update the other as well for changes to take effect. Whereas now they can toggle the behaviour with `denote-org-store-link-to-heading`.

As for whether this is idiosyncratic, I am not sure. I have not encountered another case where the `CUSTOM_ID` is used. I am happy to conform to whatever best practice. What we have here should work for `denote:` links, so we are not modifying the global Org state. If we do modify Org at-large, it is a bug.

**Comment by krisbalintona** [comment]
I apologize for taking a while to get back to you @protesilaos.

> Hello @krisbalintona and thank you for taking the time to report this!

No problem! Thank you for your incredible work on the package. The composability of the internal functions makes for easy user-end customization. In particular, I've been using denote to craft a Zettelkasten workflow personalized for my needs.

> > This is undesirable, since most times I am calling `org-capture` from a file, I do not want a new CUSTOM_ID to be created.
> 
> Are these files Denote files or does this happen with all Org files? Is setting `denote-org-store-link-to-heading` to nil a solution?

According to my testing, just denote files. (Which makes sense since `denote-link-ol-store` checks for this.)

Yes, setting `denote-org-store-link-to-heading` to nil prevents CUSTOM_IDs from being made.

> > I'm not sure if this is idiosyncratic behavior or not. In my experience, I've tried no other packages that have produced this unintended behavior. As such, I'm not sure if this calls for a change in my configuration or in denote. Perhaps denote should adhere to the value of `org-id-link-to-org-use-id`?
> 
> If I am reading this correctly, the `org-id-link-to-org-use-id` applies to the `ID` property and only checks the `CUSTOM_ID` if necessary. We are not touching the `ID` here: we only do the `CUSTOM_ID`. To your point though, having one user option depend on the value of another (in another package) makes things more complex. A user needs to update one variable and then update the other as well for changes to take effect. Whereas now they can toggle the behaviour with `denote-org-store-link-to-heading`.

I agree with what you wrote here about my initial suggestion.

To repeat, I'm on the master branch of org and I haven't tested this on previous versions. As for resolving the issue, I tried to debug the issue again with emacs -Q, and just the following configuration reproduces the bug if I navigate to any org-mode denote file and `org-capture`:
```
(use-package denote
  :load-path "/home/krisbalintona/.emacs.d/elpa/denote/denote.el"
  :custom
  (denote-directory "/home/krisbalintona/Documents/org-database/notes"))
```

**Comment by protesilaos** [comment]
I updated the documentation to note that `org-capture` is affected by this user option. Thank you!
