### ISSUE TITLE
Org mode dates

### ISSUE THREAD

**Issue by pprevos** [protesilaos/denote#27]
The default for org mode headers is now:

`#+date:       2022-06-10`

The Org mode data format is that the numbers are between square brackets. Formatting dates this way provides entry to other Org functionality.

`#+date:       [2022-06-10]`

Is that possible to implement?

**Comment by protesilaos** [comment]
Hello @pprevos!

You are right.  The user option `denote-front-matter-date-format`
provides the possibility to use an Org timestamp or a custom format.

Perhaps we should review the default value here.  It is better if we do
the right thing out-of-the-box.

What do you think?

[I'll keep this open for a little while in case someone else wants to
join the discussion ]

**Comment by kaushalmodi** [comment]
Related: 

https://github.com/protesilaos/denote/blob/879f9e1613d1f38cfca8a3b57788f562f495bb59/denote.el#L189

I set that defcustom to `org-timestamp` as I like to record both date and time (helps sort the notes in chronological order if more than one note is written in a day).

**Comment by kaushalmodi** [comment]
> What do you think about changing the defaults? Kind of how
the default for Markdown is different. It seems appropriate to use a
file-specific format for each case. 

I like that approach. Thanks.

**Comment by protesilaos** [comment]
> Thanks! Now my denote config is down to just one setting 😃

Hehe!  I am fine with this.  In general, I believe we should strive to
have good defaults so that things "just work" out-of-the-box.

Should we start a new thread about it?  Ideally, we can get feedback
from a few users before making any changes.  Just to learn how they
approach the issue.

**Comment by protesilaos** [comment]
> No, let's see if there's a real need for that [...]

Okay.

> Thanks for all your work.

You're welcome!

**Comment by pprevos** [comment]
Nice to see that when I wake up in Australia, all this work has been done. 

By the way, I am an Org Roam experimenting with using both systems side-by-side for now. The denote header is fully compatible with Org roam, which will register any file with an ID tag.

**Comment by protesilaos** [comment]
> By the way, I am an Org Roam experimenting with using both systems
> side-by-side for now. The denote header is fully compatible with Org
> roam, which will register any file with an ID tag.

Good to know!  This suggests that you might also want to opt in to links
between Denote's notes that use the standard `id:` hyperlink type
instead of `denote`.  The variable is `denote-link-use-org-id` and must
be set to t.

**Comment by protesilaos** [comment]
I changed the default value of `denote-link-use-org-id` to `t`.  I think
compatibility with the wider Org ecosystem is important and is one of
our goals to be a good Emacs citizen.

```
  commit 2193501cef4e91bb7b8d4d436484ea429ddd2084
  Author: Protesilaos Stavrou <info@protesilaos.com>
  Date:   Fri Jul 1 06:53:01 2022 +0300

      Change default value of denote-link-use-org-id

      This ensures that we provide the best experience for Org users
      out-of-the-box.  The 'id:' hyperlink type is standard, making our notes
      interoperable.

      This change should not have negative implications for existing users.
      We have already taken care to ensure that links from Org notes to other
      file type notes (e.g. Markdown) use the 'denote:' hyperlink type.  In
      other words, we apply the standard when appropriate, else fall back to
      our own mechanism.

      Thanks to Kaushal Modi and Peter Prevos for the feedback in issue 27
      over at the GitHub mirror: <https://github.com/protesilaos/denote/issues/27>.

   README.org     | 7 +++++--
   denote-link.el | 8 ++++----
   2 files changed, 9 insertions(+), 6 deletions(-)
```
