### ISSUE TITLE
`denote-retrieve-filename-title` body vs docstring

### ISSUE THREAD

**Issue by mentalisttraceur** [protesilaos/denote#275]
The docstring says "else return an empty string" but function returns nil if there's no match.

I think returning nil is on balance a bit better than returning the empty string, if you're going to do just one or the other, so personally I'd *probably* change the docstring, but I could see compelling arguments either way.

However, I think it's maybe even better to return nil if the file name doesn't look like a Denote name at all, and the empty string if the file looks valid but doesn't have a title.

Ultimately I don't think it's a big deal either wayz I just nerd-sniped myself into thinking about it. Point being, behavior doesn't match docstring.

**Comment by protesilaos** [comment]
Updated it. Thank you!
