### ISSUE TITLE
A `denote-filetype-heuristics` variant to help other code

### ISSUE THREAD

**Issue by mentalisttraceur** [protesilaos/denote#284]
As I was trying to generalize some of my code to share in #280 (so that it's not narrowly limited to just my use cases) I found myself wanting to check if a file path was one of the types that Denote recognizes.

I found/remembered `denote-filetype-heuristics` and thought "yes! this is what I-"

```lisp
(denote-filetype-heuristics "~/test.png")
;;  returns 'org
```

"...huh."

I then looked closer and I guess it's intended for when you already know that you are treating a file as a note, and you just need to decide on the type.

But external code might sometimes want to reuse these heuristics to ask "is this file of a type that Denote recognizes as a possible note? (and if so, which type?)", and in that case, it's more helpful if we had a function that:

1. in the absence of a match, returned `nil` rather than using the first entry of `denote-file-types`, and

2. that only ever operates on the file given, regardless of what buffer is current when it's called.

So I propose either a separate function, or a boolean parameter to `denote-filetype-heuristics`:

```diff
-(defun denote-filetype-heuristics (file)
+(defun denote-filetype-heuristics (file &optional match-only)
-  (if (denote--file-type-org-capture-p)
+  (if (and (not match-only)
+           (denote--file-type-org-capture-p))
       'org
     (let* ((extension (denote-get-file-extension-sans-encryption file))
            (types (denote--file-types-with-extension extension)))
       (cond ((not types)
-             (caar denote-file-types)))
+             (unless match-only
+                 (caar denote-file-types)))
-            ((= (length types) 1)
-             (caar types))
             (t
              (or (car (seq-find
                        (lambda (type)
                          (denote--regexp-in-file-p (plist-get (cdr type) :title-key-regexp) file))
                        types))
-                 (caar types)))))))
+                 (unless match-only
+                     (caar types)))))))
```

(I just eliminated the length= 1 case to the cond because when `match-only` is true, we'd still need to check if that sole element matches - falling through to the `(or (seq-find ...) ...)` works in all cases.)

**Comment by mentalisttraceur** [comment]
Another way to look at this is as an a complement (and for some uses, a better fitting alternative) to `denote-file-is-note-p`.

Because given that this file type heuristic matching both checks the extension and looks inside the file if the extension matches, in some ways it does more to determine if a file actually looks like a Denote note.

**Comment by mentalisttraceur** [comment]
Taking the separate function alternative in my own config for now (actually might be better this way! I think it turned out a lot easier to follow):

```lisp
    (defun denote-file-note-type (path)
        (when-let ((extension (denote-get-file-extension-sans-encryption path))
                   (types (denote--file-types-with-extension extension)))
            (car (seq-find
                     (lambda-let (path) (type)
                         (denote--regexp-in-file-p
                             (plist-get (cdr type) :title-key-regexp)
                             path))
                     types))))
```

(`lambda-let` is just my macro for explicit lexical scoping - those using lexical scope can just delete the `-let (path)` string and it'll work the same.)

**Comment by protesilaos** [comment]
> Taking the separate function alternative in my own config for now (actually might be better this way! I think it turned out a lot easier to follow):

I am inclined to go with this approach. If we change the `denote-filetype-heuristics`, we need to check all the places where it is called. What I did for now is to tweak its doc string for some minor stylistic issues.

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Mon, 25 Mar 2024 19:26:48 -0700
>
> I also agree with with Prot here. I have reviewed where
> `denote-filetype-heuristics` is used and I think we do not need to
> return the first entry of `denote-types` when nothing is found. It is
> better to return nil.
>
> I will still review this and include it in the set of changes for
> 3.0.0.

Thank you! Looking forward to it!

-- 
Protesilaos Stavrou
https://protesilaos.com
