### ISSUE TITLE
sort by title outside of denote-directory

### ISSUE THREAD

**Issue by fhansen42** [protesilaos/denote#285]
Is there any way to sort by title outside of the denote-directory? I'm aware of `denote-sort-dired `but I'm looking for something different. I'd like to be able to sort any directory (not just `denote-directory`) and I want all files in the directory to be sorted. Put differently, I'd like to be able to sort "as if" the denote DATE field did not exist. I would not necessary assume that this functionality would live within denote, but I am curious if there is dired functionality that might be able to accomplish this?

**Comment by mentalisttraceur** [comment]
What about `let`-binding `denote-directory` for one call? For example, define this:

```list
(defun sort-like-denote (directory)
    (interactive (list dired-directory))
    (let ((denote-direcotry directory))
        (denote-sort-dired nil 'title nil)))
```

and then just call `M-x sort-like-denote` while in a Dired buffer.

Not *exactly* "sort 'as if' the denote DATE field did not exist", and it creates a new buffer instead of sorting the one you're in, but it's a quick-and-dirty most-of-the-way solution.

**Comment by fhansen42** [comment]
@mentalisttraceur thanks for the suggestion. This will only sort denote formatted files, however. Others are ignored. Also, it seems to include denote formatted files from subdirectories. I'm looking to sort all/only files within the current directory.

**Comment by protesilaos** [comment]
@fhansen42 You are probably looking for something along the lines of `dired-virtual-mode`. We have an example in the manual: https://protesilaos.com/emacs/denote#h:d35d8d41-f51b-4139-af8f-9c8cc508e35b

**Comment by fhansen42** [comment]
@protesilaos thanks. I'll give that a try.

**Comment by protesilaos** [comment]
> From: fhansen42 ***@***.***>
> Date: Mon, 11 Mar 2024 08:26:43 -0700
>
> @protesilaos thanks. I'll give that a try.

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
