### ISSUE TITLE
I use `denote-rename-file` as my main file renaming UI

### ISSUE THREAD

**Issue by mentalisttraceur** [protesilaos/denote#287]
This issue just describes a big part of how I use Denote.

I'm using `denote-rename-file`\* as my primary file renaming interface, across *all* my files (and directories).

\* actually, a similar but more flexible function, implemented using a mix of other Denote functions, a couple functions+patches I've suggested in other Denote issues, and a few of my own helpers.

`whatever.txt` or `foo.c`? With #280, that's a Denoted file with just a title, so if I want to rename it I just hit my 'change title' keybind.

I have a separate keybind for each of:

* changing title,
* changing datetime,
* changing signature,
* adding tags (keywords), and
* removing tags.

If I'm in a Dired buffer, those keybinds act on `(dired-get-filename)`; if I'm in a file-visiting buffer, they act on that file.

What I really like about this is the orthogonality. I have the same keybinds and versatile Denoted naming for everything. With #279, it's strictly superior to Emacs' out-of-the-box rename commands:

* it prompts for confirmation in a nice way (but can be told to not with a `let` form in specific cases),
* if the file exists it renames it (but it works even if there's no file and just a visiting buffer),
* if a visiting buffer exists it updates the visited path and buffer name (but it works even if the file isn't open so long as the file exists),
* it refreshes any Dired buffers of that file's directory (in my function, I use `let` around the `denote-update-dired-buffers` call to set `denote-directory` to the file's directory, to benefit from the Dired updates upon rename in all directories),
* if I am calling it in Dired, my cursor stays on the renamed file after the Dired buffers get updated (thanks to #183).

The only file name changes I can't cover this way are changing the extension and names which must be incompatible with Denoted naming (`__init__.py`, files whose name start with a `.`, and so on). *...or can't I?*

I have a final sixth keybind prompts for the full name and uses that exactly as I typed it for the actual rename. If the file is a Denote note, it still updates the front matter according to the Denoted fields in the new file name.

Edit: I also have logic to handle one leading ".", so I can use all this with Unix hidden files.

So that way I achieve a 100% consistent interface for all file rename operations. The happy common case is structured renaming of Denoted file names, and there's a general fallback to handle the uncommon cases. There's no predication or data dependency on either the file type or if the file exists or is open in a buffer or both, or if I'm in the file's buffer or on it in Dired - the path from intent to muscle memory is uniform and purely depends on how I want to change the name. It all works on any file, and if the file looks like a note it also does the right thing with the front matter.

**Comment by mentalisttraceur** [comment]
Since there's nothing to *do* for this issue, y'all can just close it once you've read it.

I believe based on https://github.com/protesilaos/denote/issues/280#issuecomment-1987332243 that the public interfaces + specific proposals in other issues are enough to implement this without calling `denote-rename-file` with advice on its innards.

**Comment by mentalisttraceur** [comment]
For anyone looking to replicate, my full Emacs "config" (more like 2-3k lines of software with some config-like choices mixed in) is always public. In particular,

1. here's [the core function around which the first five keybinds are based](https://github.com/mentalisttraceur/home/blob/2f7e23513c2633164e17ae79d4940f22dc869611/.emacs.el#L3463-L3487) (note the `denoted-` prefix instead of `denote-`), and

2. here's [the other function used by the sixth keybind](https://github.com/mentalisttraceur/home/blob/2f7e23513c2633164e17ae79d4940f22dc869611/.emacs.el#L3561-L3571).

Note that some of the code is only there because I have preferences that deviate from Denote's defaults (for example, the `denoted-*-slug` functions), how extensions are detected, and the naming of the fields (keywords->tags; signature->prefix).

**Comment by jeanphilippegg** [comment]
> Note that some of the code is only there because I have preferences that deviate from Denote's defaults (for example, the `denoted-*-slug` functions), how extensions are detected, and the naming of the fields (keywords->tags; signature->prefix).

In the latest code, all the sluggification is controlled by the variable `denote-file-name-slug-functions`. This may help simply some of your config.

**Comment by jeanphilippegg** [comment]
In my fork of the code, I made a big refactor of the renaming commands and I think most (if not all) of your use cases are handled.

I will make it public this weekend.

If Prot reads this comment, the renaming commands in my fork have just been reworked to remove all code duplication (similar to what was attempted with `denote-rename-file-subr` a few months ago). I think I have found the right abstractions to make this possible. In addition, we gain a lot of flexibility to create custom renaming commands to handle many use cases.

It will be mostly a transparent change for users, but one that will greatly reduce code duplication and provide a uniform experience overall.

**Comment by velppa** [comment]
I do the same, the denote package is installed only to have denote-rename-file.

some things that bother me, I even tried to strip unnecessary bits from denote-rename-file but the code is pretty convoluted and uses lots of internal variables/functions.

they are:
- signature, need a way to disable prompting for it
- Frontmatter in files - don’t touch file content ever, just rename
- allow removing menu entry
- allow customizing datetime format - I rarely need minute-seconds, even date is in question.


looking forward for your implementation!

**Comment by mentalisttraceur** [comment]
@velppa I used to feel the code was a bit convoluted too, but then I realized most of what we need is actually pretty cleanly pulled out into nice functions that we can reuse. For example, you could just implement your own rename function by reusing `denoted-rename-file-prompt`, `denote-rename-file-and-buffer`, and `denote-update-dired-buffers`. Here's a very simple version:

```lisp
(defun my-denote-rename-file (path new-path title tags)
    (when (or denote-rename-no-confirm
              (denote-rename-file-prompt path new-path))
        (unwind-protect
            (progn
                (advice-add 'rename-file :around 'rename-file-advice-ignore-missing)
                (denote-rename-file-and-buffer path new-path))
            (advice-remove 'rename-file 'rename-file-advice-ignore-missing))
        (let ((denote-directory (file-name-directory new-path)))
            (denote-update-dired-buffers))))
                
(defun rename-file-advice-ignore-missing (rename-file &rest arguments)
    (condition-case _error
        (apply rename-file arguments)
        (file-missing)))
```

I'm doing [something similar](https://github.com/mentalisttraceur/home/blob/1135d1be3e71e6844ed9fa0b71cb8be6c56b0fb5/.emacs.el#L3862-L3872).

That said:

* signature: I think in the latest release (or upcoming, if I'm misremembering) `denote-rename-file` will prompt or not according to  `denote-prompts` (see release notes). If you're on an older version try `(advice-add 'denote-signature-prompt :override (lambda (&rest _) ""))`.

* frontmatter: try `(advice-add 'denote-rewrite-front-matter :override 'ignore)` and `(advice-add 'denote--add-front-matter :override 'ignore)`.

* Does toggling `denote-menu-bar-mode` do what you want?

* you can adapt the hack I shared in #278 to have full control over the datetime string... or just remove the datetime entirely like in #280 and put the information you want into f.e. the title.

**Comment by jeanphilippegg** [comment]
@mentalisttraceur

I think that the current renaming commands are now close to what you describe
in your initial post. Take a look at:

- `denote-rename-file`
- `denote-rename-file-title`
- `denote-rename-file-keywords`
- `denote-rename-file-signature`
- `denote-dired-rename-files`
- `denote-dired-rename-marked-files-with-keywords`
- `denote-dired-rename-marked-files-{add/remove}-keywords`

Most will obey these options:

- `denote-prompts`
- `denote-rename-confirmations`
- `denote-save-buffers`

If you want a renaming command to change the keywords + signature, it is very
easy to adapt `denote-rename-file-keywords` to get this new command.

However, for now, we still keep the delimiter of titles even if they are the
first component of a file name. We may change this later.

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Sun, 19 May 2024 22:13:49 -0700

> [... 23 lines elided]

> However, for now, we still keep the delimiter of titles even if they are the
> first component of a file name. We may change this later.

I think this is worth doing before version 3. The file names do not look
nice right now. Though we have the problem of ambiguity... Perhaps we
can resolve that ambiguity dynamically by consulting the 'car' of
'denote-file-name-components-order'.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jeanphilippegg** [comment]
It is important that we keep the ability to determine what are the different
components of a file name just by looking at it. For example, if we have a
note "some-word.org", we want to be able to tell (visually and
programmatically) if "some-word" is a title or a signature.

If we were to require that we look at the `car` of
`denote-file-name-components-order`, than our notes would not be portable
anymore. Only Emacs would be able to tell what "some-word" is.

And even if we did it anyway, we would still have issues because a user can
change the value `denote-file-name-components-order`. Looking at past notes,
we would not be able to tell if "some-word" were a signature or a title at
that time.

We also cannot rely on the front matter because it does not always exists.

The only thing I think we can do is to decide which of the component can drop
its delimiter in first position and stick to this decision. However, I am not
sure we have to make this decision by version 3.0.0. We could wait and see how
users use this in practice? This decision would be hard to reverse.

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Mon, 20 May 2024 19:26:07 -0700
>
> It is important that we keep the ability to determine what are the different
> components of a file name just by looking at it. For example, if we have a
> note "some-word.org", we want to be able to tell (visually and
> programmatically) if "some-word" is a title or a signature.
>
> If we were to require that we look at the `car` of
> `denote-file-name-components-order`, than our notes would not be portable
> anymore. Only Emacs would be able to tell what "some-word" is.
>
> And even if we did it anyway, we would still have issues because a user can
> change the value `denote-file-name-components-order`. Looking at past notes,
> we would not be able to tell if "some-word" were a signature or a title at
> that time.

Excellent points!

> We also cannot rely on the front matter because it does not always exists.

Indeed. The front matter is there for convenience, but the file name is
the source of truth.

> The only thing I think we can do is to decide which of the component can drop
> its delimiter in first position and stick to this decision. However, I am not
> sure we have to make this decision by version 3.0.0. We could wait and see how
> users use this in practice? This decision would be hard to reverse.

In that case it is better to keep things as they are. Whichever we pick
is bound to displease someone. Plus, we already have this for the
identifier, so no need to add more exceptions.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by mentalisttraceur** [comment]
Re: ambiguity: so, in my own files, my approach is

1. if the start of the file looks like `[0-9]{8}T[0-9]{6}`, it's an identifier,
2. if the start of the file looks like one of denoted naming part prefixes, it's that part\*,
3. otherwise it's a title.

The value I get from using the same UX for almost all filesystem renaming without having to prefix `--` to almost everything is big, immediate, and predictably forever.

The value I get from... titles which look like `YYYYMMDDTHHMMSS`? Zero, with some small probability of non-zero-but-still-probably-small value someday within my lifetime.

(I also fontify all instances of `[0-9]{8}T[0-9]{6}` in the name as datetimes, regardless of where they occur - to me this seems very likely to be useful in a variety of ways, and very unlikely to ever do something I don't want: if it's intentionally a datetime I want to see it, and if it's unintentionally a datetime that's neat/funny so I want to see it.)

That said, I appreciate the work that's been done to accommodate what I've described here, and I look forward to seeing if I can replace some of my code with reuse of some of these new Denote improvements (not sure how soon I'll be able to do that though).

**Comment by mentalisttraceur** [comment]
(Similarly, identifiers/links that don't look like `YYYYMMDDTHHMMSS` seem potentially valuable to me, but not nearly as valuable as omitting the `--` prefix in the common/general case, so I'll end up making other tradeoffs to cross that bridge if/when I get to it.)

**Comment by jeanphilippegg** [comment]
I don't think it would be hard to allow titles to drop their delimiters. I had some code to support this, but I removed it before the final pull request. We can see how this is used in practice and let things stabilize.

> (Similarly, identifiers/links that don't look like `YYYYMMDDTHHMMSS` seem potentially valuable to me, but not nearly as valuable as omitting the `--` prefix in the common/general case, so I'll end up making other tradeoffs to cross that bridge if/when I get to it.)

This is actually easy to solve. We just have to say that the identifier in first position drops its delimiter **only if is has the format `YYYYMMDDTHHMMSS`**. Otherwise, the delimiter is present even in first position, e.g. `@@2024-05-24--a-note.org`.

**Comment by mentalisttraceur** [comment]
> This is actually easy to solve. We just have to say that the identifier in first position drops its delimiter only if is has the format `YYYYMMDDTHHMMSS`. Otherwise, the delimiter is present even in first position, e.g. `@@2024-05-24--a-note.org`.

Yep, exactly. That's one of the things I had in mind under "other tradeoffs".

Another thought I had was that my number-one likely use-case for non-datetime linkable identifiers would naturally reuse title (sluggified) as the globally unique string, and in that case I'd start looking at how to implement "if there's no identifier part in the name, fall back to using the title as link".

**Comment by jeanphilippegg** [comment]
I don't think relying on the file name for linking would end up being a good
idea. It would impose too much rigidity on the file name. Whenever you want to
modify it, you would have to update various files as well. This may lead to a
lot of issues.

I think that an ID-filename association is necessary. However, this
association does not need to be recorded in the file name. At some point, we
may offer the option to save it externally, in some variable for example.

**Comment by mentalisttraceur** [comment]
As a general rule you're absolutely right.

For example, I would never link to a typical note by title, because the title might be temporary or liable to change as my thoughts or needs for it change.

The reason why it might end up one day making sense in certain cases for me is that I have a small body of blog posts which have a canonical 1-3 word title which hasn't changed for years and in most cases I can forecast with high likelihood won't ever change.

But that's pretty specific to me, and even for me it's not a high enough priority for me to implement yet.
