### ISSUE TITLE
Possible to create a denote file outside denote-directory?

### ISSUE THREAD

**Issue by AnabasisXu** [protesilaos/denote#289]
I want to use the `denote` command to create files outside of my denote-directory, for these notes may have to be renamed according to the naming scheme of denote anyway. 

But I could not find any such function in the follwing list created by M-x `denote create`:

```elisp
denote-create-note-in-subdirectory             Alias for ‘denote-subdirectory’ command.                         
denote-create-note                             Alias for ‘denote’ command.                                      
denote-link-or-create                       (C-c n i)    Use ‘denote-link’ on TARGET file, creating it if necessary.      
denote-open-or-create                       (C-c n o)    Visit TARGET file in variable ‘denote-directory’.                
denote-create-note-using-date                  Alias for ‘denote-date’ command.                                 
denote-create-note-using-type                  Alias for ‘denote-type’ command.                                 
denote-silo-extras-create-note                 Select SILO and run ‘denote’ in it.                              
denote-create-note-with-template               Alias for ‘denote-template’ command.                             
denote-silo-extras-open-or-create              Select SILO and run ‘denote-open-or-create’ in it.               
denote-create-note-using-signature             Alias for ‘denote-signature’ command.                            
denote-open-or-create-with-command             Visit TARGET file in variable ‘denote-directory’.                
denote-journal-extras-link-or-create-entry     Use ‘denote-link’ on journal entry, creating it if necessary.    
```

I tried `denote-silo-extras-open-or-create` and was prompted to choose a directory. But I could not just type the current directory in which I wanted to run `denote-create-note`.

**Comment by protesilaos** [comment]
> From: Zhenxu Xu ***@***.***>
> Date: Wed, 13 Mar 2024 02:16:14 -0700
>
> I want to use the `denote` command to create files outside of my
> denote-directory, for these notes may have to be renamed according to
> the naming scheme of denote anyway.

Can you describe the use-case for this? We put new notes in the
'denote-directory' because we can then link to them if needed.

Perhaps we can mention some custom code in the manual to do what you are
asking for, though I am curious to understand the workflow better.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by AnabasisXu** [comment]
Hi @protesilaos ! I just want to use denote as much as possible and not confined to `denote-directory`, for it streamlines trouble of naming files properly. I am going to `denote-rename-file` all my notes outside of the `denote-directory`, and need to create new ones, so it would be great if there is a `denote-create-note-current-dir` function.

I believe this will be of general interest.

**Comment by protesilaos** [comment]
How about this?

```elisp
(defun denote-create-note-in-any-directory ()
  "Create new Denote note in any directory.
Prompt for the directory using minibuffer completion."
  (declare (interactive-only t))
  (interactive)
  (let ((denote-directory (read-directory-name "New note in: " nil nil :must-match)))
    (call-interactively 'denote)))
```

**Comment by AnabasisXu** [comment]
@protesilaos  Thank you so much! This works perfectly for me.

**Comment by protesilaos** [comment]
You are welcome!

I documented this in the manual: https://protesilaos.com/emacs/denote#h:c9d7c157-85a6-4bb7-bd21-d00bccf5e799

If others find it useful, we may add it to `denote.el`.
