### ISSUE TITLE
Commit 232bd90 does not only apply to signatures

### ISSUE THREAD

**Issue by jeanphilippegg** [protesilaos/denote#292]
This is a comment on commit 232bd90 where signatures are treated specially in renaming commands.

The issue this commit is trying to fix does not only apply to the signature component of the file name. For example, if `denote-prompts` does not contain `title`, then `denote-rename-file` will suppress the title. This is also undesirable.

I suggest instead that the renaming commands keep obeying `denote-prompts` and that `denote-rename-file` only modify the file name components for which we are being prompted and keep the others untouched. This would make it work with all components and the experience would be consistent and intuitive.

**Comment by jeanphilippegg** [comment]
I think it also defeats the intention of making them obey `denote-prompts`. Someone that has configured multiple renaming commands with different values of `denote-prompts` tailored to its need in the moment will now always be prompted for a signature (assuming all his notes have signatures). I think this is undesirable.

**Comment by jeanphilippegg** [comment]
By the way, I think `denote-keywords-add`, `denote-keywords-remove`, `denote-signature-add` and `denote-signature-remove` can all be implemented by let binding `denote-prompts` appropriately. So it may be better to leave users to decide which commands they want in their configuration and explain how Denote can be configured in such a way in the manual. We can also provide them as convenience functions.

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Sat, 16 Mar 2024 06:46:59 -0700
>
> I think it also defeats the intention of making them obey
> `denote-prompts`. Someone that has configured multiple renaming
> commands with different values of `denote-prompts` tailored to its
> need in the moment will now always be prompted for a signature
> (assuming all his notes have signatures). I think this is undesirable.

You are right! I did not think it through. Your suggestion of ignoring
them instead of deleting them is better. Do you want to send a patch or
shall I do it?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jeanphilippegg** [comment]
I can do it. I'll send the patch in 1-2 hours.

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Sat, 16 Mar 2024 07:00:07 -0700
>
> By the way, I think `denote-keywords-add`, `denote-keywords-remove`,
> `denote-signature-add` and `denote-signature-remove` can all be
> implemented by let binding `denote-prompts` appropriately. So it may
> be better to leave users to decide which commands they want in their
> configuration and explain how Denote can be configured in such a way
> in the manual. We can also provide them as convenience functions.

I agree in principle. But let's leave these bigger changes (and the
others you have proposed) for version 3 of Denote. Then we will have
plenty of time to break what we think is necessary.

My idea now is to try to prepare version 2.3.0 in the coming week. Then
we can work on the other projects.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jeanphilippegg** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***> Date: Sat, 16 Mar 2024 07:00:07 -0700 By the way, I think `denote-keywords-add`, `denote-keywords-remove`, `denote-signature-add` and `denote-signature-remove` can all be implemented by let binding `denote-prompts` appropriately. So it may be better to leave users to decide which commands they want in their configuration and explain how Denote can be configured in such a way in the manual. We can also provide them as convenience functions.
> I agree in principle. But let's leave these bigger changes (and the others you have proposed) for version 3 of Denote. Then we will have plenty of time to break what we think is necessary. My idea now is to try to prepare version 2.3.0 in the coming week. Then we can work on the other projects.
> […](#)
> -- Protesilaos Stavrou https://protesilaos.com

I agree! I will only make the changes relative to the current issue in my next pull request.

**Comment by jeanphilippegg** [comment]
I will take a couple more hours. I will fix this and may include other minor cleanups (no new functionalities) ahead of version 2.3.0. I will do the pull request today.

**Comment by protesilaos** [comment]
I merged that change and made some further tweaks. Thank you!

What we do now is not touch a file name component that is not covered by `denote-prompts`. This is better than before, as we are not deleting file name components outright.

I think the behaviour should be to prompt for the file name component if it is present regardless of `denote-prompts`. The reason is that a user may use some file name components only on occasion (e.g. with `denote-signature`) and when renaming those files they may want to review that component.

If they want to keep it as-is, they simply type `RET` at the prompt. If they want to remove it, they input an empty string. Or they rewrite it as they see fit.

If we do not do this, then we will have to ask the user to write a wrapper command that `let` binds the `denote-prompts` such that the given file name component is covered. But if those files are not the common case (think about the occasional signature, for example), such an addition is cumbersome.

**Comment by jeanphilippegg** [comment]
Ok, yes, I understand the issue.

Do you mean to remove obedience to `denote-prompts` completely and have
renaming commands prompt for existing components only? If so, I agree.
It would probably be better than the current version. (It is also not
yet part of a released version.) And there are commands to add/remove
keywords and signatures.

-----------

If you want to keep some form of obedience to `denote-prompts`, I have
the following idea. Though it can be kept for a later version.

What about we keep `denote-rename-file` as it is (strictly obey
`denote-prompts`) and provide the convenience command
`denote-rename-file-dwim` that does the above? Its implementation would
be as follow:

```
(defun denote-rename-file-dwim ()
  (declare (interactive-only t))
  (interactive)
  (let* ((file (denote--rename-dired-file-or-prompt))
         (has-title-p (denote-retrieve-filename-title file))
         (has-keywords-p (denote-retrieve-filename-keywords file))
         (has-signature-p (denote-retrieve-filename-signature file))
         (prompts denote-prompts))
    (when (and has-signature-p (not (memq 'signature prompts)))
      (push 'signature prompts))
    (when (and has-keywords-p (not (memq 'title prompts)))
      (push 'keywords prompts))
    (when (and has-title-p (not (memq 'title prompts)))
      (push 'title prompts))
    (let ((denote-prompts prompts))
      (call-interactively #'denote-rename-file))))
```

The idea is to have a general command that obeys `denote-prompts` from
which many convenience commands can be derived.
`denote-rename-file-dwim` is one of them, but we can imagine
`denote-rename-title`, `denote-rename-keywords` and the like for
specific use-cases. (Their implementation would be simpler than
`denote-rename-file-dwim` above.)

`denote-rename-file` would already be usable as it is, but it would
serve as a building block for other renaming commands. In a release
note, in addition to mentionning that `denote-rename-file` now obeys
`denote-prompts`, we would point to `denote-rename-file-dwim` as an
alternative.

But, as I said, this can be deferred to a later version.

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Mon, 18 Mar 2024 18:37:28 -0700

> [... 11 lines elided]

> If you want to keep some form of obedience to `denote-prompts`, I have
> the following idea. Though it can be kept for a later version.
>
> What about we keep `denote-rename-file` as it is (strictly obey
> `denote-prompts`) and provide the convenience command
> `denote-rename-file-dwim` that does the above? Its implementation would
> be as follow:

> [... 33 lines elided]

Even better! I think following the 'denote-prompts' is a good default.
Then the DWIM takes care of the other cases.

> But, as I said, this can be deferred to a later version.

We can squeeze it in now. It will fit with the theme of this release of
polisihing the interactivity of those renaming commands.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by jeanphilippegg** [comment]
Ok! I will do a pull request in the coming days if you have not already modified the code.

**Comment by protesilaos** [comment]
When I wrote the previous comment, I forgot that I added commands to add/remove a signature. A DWIM command is not a pressing requirement anymore, but you can go ahead if you are already working on it. Otherwise, don't bother.
