### ISSUE TITLE
is it possible to create single tag with multiple words seperated by delimter? 

### ISSUE THREAD

**Issue by rootid** [protesilaos/denote#294]
Trying to add tag Productivity-Hacks but it always convert to productivityhacks

**Comment by jeanphilippegg** [comment]
If you don't want your tags to be downcased or have "-" removed, you can disable sluggification of keywords like this : 

```
(setq denote-file-name-slug-functions
      '((title . denote-sluggify-title)
        (keyword . identity)
        (signature . denote-sluggify-signature)))
```

This is available in the latest code and will be available in the next version of Denote.

With the above config, the only thing disallowed in keywords are underscores and "--", "__" or "==".

**Comment by protesilaos** [comment]
This is now covered at greater length in the manual: https://protesilaos.com/emacs/denote#h:d375c6d2-92c7-425f-9d9d-219ff47ed2a3

**Comment by protesilaos** [comment]
I have included this, because I think it is important:

> Remember that deviating from the default file-naming scheme of Denote will make things harder to search in the future, as files can/will have permutations that create uncertainty. The sluggification scheme and concomitant restrictions we impose by default are there for a very good reason: they are the distillation of years of experience. Here we give you what you wish, but bear in mind it may not be what you need. You have been warned.
