### ISSUE TITLE
Backlink buffer aware of org heading 

### ISSUE THREAD

**Issue by h-oll** [protesilaos/denote#297]
Hi, 
Thanks for the great work on denote. The addition of links to specific orgmode heading was a must have for me. Would it also be possible to have backlinks restricted to a specific heading in the org file? I meant, have the backlinks that point to this specific heading or to any heading in the subtree.

The usecase is the following: I work partly using a giant orgmode file with many items in hierarchical format. But For some subtopics I need independent atomic notes. When writing these atomic notes I want to link to this giant orgmode file, and would like to access these notes from there. I think it corresponds to what you describe as a metanote, but having subsections that have specific content / topics. I think the same could be useful in the context of writing a book where you want to have a master plan and gather bibliographical notes but dont want to have one file per chapter.

**Comment by protesilaos** [comment]
Hello @h-oll! This is worth exploring. Since we just got the new version out, we want to wait a couple of weeks to fix any bugs. Then we can resume development work towards the new version.

**Comment by protesilaos** [comment]
I just added support for backlinks that are specific to the current Org heading. Note that this feature is still in development. If you can test it, please let me know how it goes.
