### ISSUE TITLE
Can't add link to file from within org-capture: "The current file type is not recognized by Denote"

### ISSUE THREAD

**Issue by svnsbck** [protesilaos/denote#298]
Hi Prot!

I use the `denote-link` command to add links to files within my todo's  with `org-capture` which somehow stopped working after the recent update. 

I realized your blog-post about the options the option to link to headers and set also `denote-org-store-link-to-heading`~ to `nil` but only get "The current file type is not recognized by Denote".  Adding links from within an org-file seems to work as expected.

I am sure I am missing the obvious here somewhere, but any help is appreciated!

All the best, Sven

**Comment by protesilaos** [comment]
Thank you Sven! This is a bug. I pushed two tweaks to fix it. A new version of the package will be available in a few hours.

Once you get the package, please confirm if the problem is solved on your end.

**Comment by svnsbck** [comment]
Hi Prot!

Nice, the latest update works.  I realized that the link title now includes the signature as well.  Is this expected behaviour?  I don't think Denote did this earlier.

**Comment by protesilaos** [comment]
I now realise I did not document this in the changelog... Thanks Sven! When a file has a signature, a link to it will include it. Before, we had a separate command to do this. The `denote-link-description-function` variable controls this behaviour. I am now thinking this should be a user option with a choice between:

1. Title link.
2. Signature plus title.
3. Arbitrary function.

Copying @jeanphilippegg who modified this part for any thoughts on the matter. I know adding a `defcustom` here is technically a new feature, though we really want to keep it small to basically announce the variable that is already there (makes it discoverable through the Custom UI).

**Comment by protesilaos** [comment]
The diff for what I described above (NOT TESTED YET):

```diff
 denote.el | 50 ++++++++++++++++++++++++++++++++++++++++----------
 1 file changed, 40 insertions(+), 10 deletions(-)

diff --git a/denote.el b/denote.el
index 86e8960..1f3877a 100644
--- a/denote.el
+++ b/denote.el
@@ -676,6 +676,21 @@ (make-obsolete
  'denote-file-name-slug-functions
  "2.3.0")
 
+(defcustom denote-link-description-function #'denote-link-description-with-signature-and-title
+  "Function to use to create the description of links.
+
+The function specified should take a FILE argument and should
+return the description as a string.  By default, the title of the
+file is returned as the description."
+  :group 'denote
+  :type '(choice
+          (function :tag "Link to title and include signature, if present"
+                           denote-link-description-with-signature-and-title)
+          (function :tag "Link to title only"
+                    denote-link-description-with-signature-and-title)
+          (function :tag "Custom function like `denote-link-description-with-signature-and-title'"))
+  :package-version '(denote . "2.3.0"))
+
 ;;;; Main variables
 
 ;; For character classes, evaluate: (info "(elisp) Char Classes")
@@ -3644,21 +3659,33 @@ (define-obsolete-variable-alias
 (defvar denote-link-signature-format "%s  %s"
   "Format of link description for `denote-link-with-signature'.")
 
-;; TODO 2024-02-22: Consider documenting this, such as:
-;; <https://github.com/protesilaos/denote/issues/255#issuecomment-1949634482>.
-(defvar denote-link-description-function #'denote-link-description-with-signature-and-title
-  "Function to use to create the description of links.
-
-The function specified should take a FILE argument and should
-return the description as a string.  By default, the title of the
-file is returned as the description.")
-
 (defun denote--link-get-description (file)
   "Return link description for FILE."
   (funcall
    (or denote-link-description-function #'denote-link-description-with-signature-and-title)
    file))
 
+(defun denote-link-description-with-title (file)
+  "Return link description for FILE.
+
+- If the region is active, use it as the description.
+
+- If FILE does not have a signature, then use its title as the
+  description.
+
+This is useful as the value of the user option
+`denote-link-description-function'."
+  (let* ((file-type (denote-filetype-heuristics file))
+         (signature (denote-retrieve-filename-signature file))
+         (title (denote-retrieve-title-or-filename file file-type))
+         (region-text (denote--get-active-region-content)))
+    (cond (region-text
+           region-text)
+          (signature
+           (format denote-link-signature-format signature title))
+          (t
+           (format "%s" title)))))
+
 (defun denote-link-description-with-signature-and-title (file)
   "Return link description for FILE.
 
@@ -3668,7 +3695,10 @@ (defun denote-link-description-with-signature-and-title (file)
   By default, this looks like \"signature   title\".
 
 - If FILE does not have a signature, then use its title as the
-  description."
+  description.
+
+This is useful as the value of the user option
+`denote-link-description-function'."
   (let* ((file-type (denote-filetype-heuristics file))
          (signature (denote-retrieve-filename-signature file))
          (title (denote-retrieve-title-or-filename file file-type))
```

Adding the `denote-link-description-with-title` simply restores the original behaviour and is not really a new feature.

**Comment by jeanphilippegg** [comment]
The function `denote-link-description-with-signature-and-title` is
already close to the original default because the signature part is only
visible if there actually is a signature. Otherwise, only the title is
used (as before).

Are you suggesting that `denote-link-description-with-title` becomes the
default for `denote-link-description-function`? I would think it is
better to keep the current default (with signature (if present) and
title). Otherwise, some commands will not behave as before
(`denote-link-with-signature`) and I do not think it would be good to
force any specific description format (in this command or any future
commands).

I think it is a sensible default for all commands. For any specific use
case, users can always let bind `denote-link-description-function` as
usual to create various specific commands.

Otherwise, making it a defcustom is good. Also, in your diff, you have
not removed the "signature" part in
`denote-link-description-with-title`. But since it is already very close
to the default, I am not sure it is worth adding it at all. If a user
really does not want a signature (even if present), he can write his own
function.

One thing I would do though, is remove the new user option
`denote-link-signature-format`. I think it is too specific (an option
that controls some specific case of another option), given that users
can always just customize `denote-link-description-function` if they are
unhappy with the format that we chose. It may add more confusion than be
helpful, as users will have the wrong impression that it is better to
customize `denote-link-signature-format` than
`denote-link-description-function`. This option is also quite rigid. It
does not even allow the title to come before the signature.

**Comment by protesilaos** [comment]
Fine, let's not add a new function. I agree that the current one is a sensible default. Then the custom function can do whatever it needs. This is then a matter of documenting it, which I will do separately.

What about this then?

```diff
 denote.el | 49 ++++++++++++++++++++++++-------------------------
 1 file changed, 24 insertions(+), 25 deletions(-)

diff --git a/denote.el b/denote.el
index 74125aa..112bc2d 100644
--- a/denote.el
+++ b/denote.el
@@ -676,6 +676,20 @@ (make-obsolete
  'denote-file-name-slug-functions
  "2.3.0")
 
+(defcustom denote-link-description-function #'denote-link-description-with-signature-and-title
+  "Function to create the description of links.
+
+The function specified takes a FILE argument and returns the description
+as a string.
+
+By default, the title of the file is returned as the description.  If
+the file has a signature, it is prepended to the title."
+  :group 'denote
+  :type '(choice
+          (function :tag "Link to title and include signature, if present" denote-link-description-with-signature-and-title)
+          (function :tag "Custom function like `denote-link-description-with-signature-and-title'"))
+  :package-version '(denote . "2.3.0"))
+
 ;;;; Main variables
 
 ;; For character classes, evaluate: (info "(elisp) Char Classes")
@@ -3631,27 +3645,7 @@ (defun denote-format-link (file description file-type id-only)
    description))
 
 (make-obsolete 'denote-link--format-link 'denote-format-link "2.1.0")
-
-;; NOTE 2023-12-05 04:16 +0200: This is a candidate for a user option,
-;; subject to feedback.  I think the signature should be better
-;; disambiguated in this context, although the double space is a good
-;; start.
-(define-obsolete-variable-alias
-  'denote--link-signature-format
-  'denote-link-signature-format
-  "2.3.0")
-
-(defvar denote-link-signature-format "%s  %s"
-  "Format of link description for `denote-link-with-signature'.")
-
-;; TODO 2024-02-22: Consider documenting this, such as:
-;; <https://github.com/protesilaos/denote/issues/255#issuecomment-1949634482>.
-(defvar denote-link-description-function #'denote-link-description-with-signature-and-title
-  "Function to use to create the description of links.
-
-The function specified should take a FILE argument and should
-return the description as a string.  By default, the title of the
-file is returned as the description.")
+(make-obsolete 'denote-link-signature-format nil "2.3.0")
 
 (defun denote--link-get-description (file)
   "Return link description for FILE."
@@ -3664,19 +3658,24 @@ (defun denote-link-description-with-signature-and-title (file)
 
 - If the region is active, use it as the description.
 
-- If FILE as a signature, then use the `denote-link-signature-format'.
-  By default, this looks like \"signature   title\".
+- If FILE as a signature, then format the description as a sequence of
+  the signature text and the title with two spaces between them.
 
 - If FILE does not have a signature, then use its title as the
-  description."
+  description.
+
+This is useful as the value of the user option
+`denote-link-description-function'."
   (let* ((file-type (denote-filetype-heuristics file))
          (signature (denote-retrieve-filename-signature file))
          (title (denote-retrieve-title-or-filename file file-type))
          (region-text (denote--get-active-region-content)))
     (cond (region-text
            region-text)
+          ((and signature title)
+           (format "%s %s" signature title))
           (signature
-           (format denote-link-signature-format signature title))
+           (format "%s" title))
           (t
            (format "%s" title)))))
 
```

**Comment by jeanphilippegg** [comment]
That's good!

Just a few final touches:

- The second to last condition (the one with `signature`) only formats the title. But it is never reached, so it can be removed.
- The `title` is never `nil` as it is retrieved using `denote-retrieve-title-or-filename`. The check can be removed from the second condition.
- Since we are at it, you can also replace `(format "%s" title)` with just `title` in the last condition.

**Comment by protesilaos** [comment]
Done. Thank you!

**Comment by unexistz** [comment]
So is there a way to insert a link while omitting the signature? Sorry if this is a dumb question, I'm not a programmer so I'm having a hard time following code.

**Comment by protesilaos** [comment]
> From: unexistz ***@***.***>
> Date: Thu, 20 Feb 2025 12:11:01 -0800
>
> unexistz left a comment (protesilaos/denote#298)
>
> So is there a way to insert a link while omitting the signature? Sorry
> if this is a dumb question, I'm not a programmer so I'm having a hard
> time following code.

Yes, use the 'denote-link' command. Otherwise, please tell me more about
what you are trying to do and which steps you are following.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by unexistz** [comment]
> From: unexistz ***@***.***>
>  Date: Thu, 20 Feb 2025 12:11:01 -0800
> 
>  unexistz left a comment ([protesilaos/denote#298](https://github.com/protesilaos/denote/issues/298))
> 
>  So is there a way to insert a link while omitting the signature? Sorry
>  if this is a dumb question, I'm not a programmer so I'm having a hard
>  time following code.
> Yes, use the 'denote-link' command. Otherwise, please tell me more about
> what you are trying to do and which steps you are following.
> […](#)

Hey Prot, thanks for the answer! I'm trying to link to an existing Denote note. So on another note I use the 'denote-link' command on an empty line. But it still adds the file signature to the link description.

**Comment by protesilaos** [comment]
On 2025-02-22 10:11, unexistz wrote:

> Hey Prot, thanks for the answer! I'm trying to link to an existing
> Denote note. So on another note I use the 'denote-link' command on an
> empty line. But it still adds the file signature to the link
> description.

Oh, I see. What confused me about your question is that you are posting
it under the title of an old issue about org-capture.

Anyway, check the user option 'denote-link-description-format'. It 
explains
how to customise the presentation of links.

If you only need to do this in certain cases, then you will have to 
define
a custom wrapper of the 'denote-link' command that uses the preferred 
value
of 'denote-link-description-format'. For example:

     (defun my-denote-link-with-custom-format ()
       "Link `denote-link' but with a custom 
`denote-link-description-format'."
       (interactive)
       (let ((denote-link-description-format "%t")) ; change the value 
here
         (call-interactively 'denote-link)))

**Comment by unexistz** [comment]
I see. I'd prefer all links to be without signatures (hopefully for dynamic blocks as well), so I've tried adding this code to my config:
`(setq denote-link-description-function 'denote-link-description-with-title)`

But when I try to insert a link it returns this error:
`denote--link-get-description: Symbol’s function definition is void: denote-link-description-with-title`

I also tried to define the custom function you've described like this:
```
(defun my-denote-link-with-custom-function ()
  "Link 'denote-link' but with a custom 'denote-link-description-function."
  (interactive)
  (let ((denote-link-description-function "denote-link-description-with-title")) ; change the value here
     (call-interactively 'denote-link)))
```
Which returns an 'invalid function' error. I'm probably setting the parameter incorrectly.

Thanks again for your help and sorry to take your time with such a simple issue. 😭

**Comment by protesilaos** [comment]
On 2025-02-22 12:25, unexistz wrote:

> Thanks again for your help and sorry to take your time with such a
> simple issue. 😭

Try this:

     (setq denote-link-description-format "%t") ; this is current name of 
the variable

**Comment by unexistz** [comment]
It still inserts the signature 😬 I set that paremeter seperately right? Here's my current config.

```
(use-package denote
  :ensure t
  :init
  :custom
  (denote-directory "~/projects/denote")
  (denote-known-keywords nil)
  (denote-prompts '(signature title keywords))
  (denote-backlinks-show-context t)
  :config
  (add-hook 'dired-mode-hook #'denote-dired-mode))

(setq denote-link-description-format "%t") ; this is current name of the variable

```

**Comment by protesilaos** [comment]
On 2025-02-22 12:47, unexistz wrote:
> It still inserts the signature 😬 I set that paremeter seperately
> right? Here's my current config.

Does this work for you? What I sent earlier will work with Denote 3.2.0,
which is basically what the current Git commit is.

Try this instead:

(defun my-denote-link-description-with-title (file)
   "Compatibility function for `denote-link-description-function'."
   (let* ((file-type (denote-filetype-heuristics file))
          (title (denote-retrieve-title-or-filename file file-type))
          (region-text (denote--get-active-region-content)))
     (cond
      (region-text region-text)
      (title (format "%s" title))
      (t ""))))

(setq denote-link-description-function 
'my-denote-link-description-with-title)

**Comment by unexistz** [comment]
It does! Thank you so much!

The latest version seems to be 3.1.0 in ELPA, which is what I'm using. Not sure how I can install 3.2.0. Will try the previous code you've sent when I'm able to update.

Thank you so much for the help and apologies again for taking your time.
