### ISSUE TITLE
Cannot add a denote link in `org-add-log-note`

### ISSUE THREAD

**Issue by brabalan** [protesilaos/denote#309]
When adding an org note (for instance to give a reason why a task was canceled), it is not possible because the file is not recognized as a valid type.

I tried tweaking `denote--file-type-org-capture-p`, but it seems to be tailored for org capture. Maybe one could add a predicate that does this:
```emacs-lisp
(and (derived-mode-p 'org-mode)
     (string-match-p "\\`\\*Org Note\\*" (buffer-name)))
```
(the buffer name is hard coded in `org-add-log-note`).

The drawback of this predicate is that it would be used in every place where `denote--file-type-org-capture-p` is used. Maybe this calls for some refactoring (i.e., doing both tests in the same predicate)?

**Comment by brabalan** [comment]
I propose a solution in #310.

**Comment by protesilaos** [comment]
Merged PR, thank you!
