### ISSUE TITLE
Announcement: Some upcoming features available in my fork

### ISSUE THREAD

**Issue by jeanphilippegg** [protesilaos/denote#314]
Hello Prot!

I have done almost all the modifications I had in mind for Denote in my
fork of the code. I have started to document the changes in a manual I
made for my fork.

Most of what was discussed recently is implemented there, notably:

- `denote-directory` supports a list of directories. Internally, we now
  always work with a list of directories using the new
  `(denote-directories)` function. `(denote-directory)` is retained to
  not break user code, but it only returns the first element of
  `denote-directory` and it is recommended to use the function
  `denote-directories` instead.
- Reordering of file name components. I have not pushed the changes to
  the fontification because I want to simplify it a little.
- Variables to create custom `denote` commands (the `denote-forced-*`
  discussed in #256).
- Major (internal) simplification of the renaming commands. With the
  help of the new `denote-forced-*` variables, I was able to remove all
  the code duplication between renaming commands. It is now easy to
  define custom renaming commands. The code for the current ones is
  simplified. `denote-rename-file` can also change a note's file type
  and directory.
- `denote-rename-confirmations` and `denote-save-buffers` control the
  prompts and whether to automatically save buffers or not.

You can look at the new commits I made in my fork to understand how each
of these features is implemented. There are many commits that removes
some secondary features from Denote. This is just to create a clean
canvas for me to work on. I will not make pull requests for those.

As I said in other comments, I will start making pull requests to
include the discussed features in May.

In the manual I made, the most important sections are "Differences with
the original project" and "Core of Denote" where I explain how users can
configure Denote for various use cases.

[Link to my fork](https://github.com/jeanphilippegg/denote)

Have a good day!

**Comment by protesilaos** [comment]
Thank you @jeanphilippegg! I think the best way forward is to keep working on a single project. We can do this by making Denote more modular. Let this repo be the core of the project. Then the convenience commands can still exist as a separate repo. We do not have to discard them and I do not mind maintaining those: there are users who are not fluent in Lisp and find it hard to maintain their own wrappers. Whenever we have some new feature, we can discuss where it belongs: in core or the extras. Then we take it from there.

**Comment by jeanphilippegg** [comment]
Yes, this is my intention as well! I do not intent to make pull requests for their removal. This is just to work on a simpler version where extra features are not in the way. In time, I will make the necessary adjustment for inclusion of all the discussed features in Denote (while retaining what we have).

In the meantime, you can have a look at the implementation of the features that are coming later.

**Comment by jeanphilippegg** [comment]
Hello Prot!

Just letting you know that I have updated the code in my fork on top of
the current code. I have renamed Renote back to Denote. If you check the
commits, you will see the pull requests that I intend to make next month
(they are prefixed with "(May)").

Here is the intention:
- Streamline the renaming commands
- Make `denote-directory` accept a list of directories
- Allow file components reordering
- After that, some minors commits to fix currently open issues

A big one is the streamlining of the renaming commands. It is not much
of a user-visible change, but the removal of the code duplication makes
them more robust and consistent. It will be easier to maintain them and
create new ones as well in the future.

Everything is done in my fork and I was intending to start making pull
requests to include these changes in an order that makes sense.

Have a good day!

**Comment by protesilaos** [comment]
Thank you @jeanphilippegg! I am looking forward to the new developments!

**Comment by x61** [comment]
Thanks gents for this work. Curios, has this been merged into the main denote.el? I have the recent commit of denote, installed version: 2.3.5 0a75608, but the `filetags` field is empty with the following template
```
 ("t" "Todo" plain
           (file denote-last-path)
           (function (lambda () (let ((denote-prompts '(title))
                                      (denote-forced-keywords '("journal"))
                                      (denote-forced-template 'journal))
                                  (denote-org-capture))))

```
<img width="773" alt="Screenshot 2024-04-27 at 04 41 08" src="https://github.com/protesilaos/denote/assets/6430853/5f37ad21-ca46-4d74-bfcc-45c067a5e38a">

**Comment by protesilaos** [comment]
> From: x61 ***@***.***>
> Date: Sat, 27 Apr 2024 01:45:40 -0700
>
> Thanks gents for this work.

You are welcome!

> Curios, has this been merged into the main denote.el?

Yes, we are in the process of changing things.

> I have the recent commit of denote, installed version: 2.3.5 0a75608, but the `filetags` field is empty with the following template
> ```
>  ("t" "Todo" plain
>            (file denote-last-path)
>            (function (lambda () (let ((denote-prompts '(title))
>                                       (denote-forced-keywords '("journal"))
>                                       (denote-forced-template 'journal))
>                                   (denote-org-capture))))
>
> ```
> <img width="773" alt="Screenshot 2024-04-27 at 04 41 08" src="https://github.com/protesilaos/denote/assets/6430853/5f37ad21-ca46-4d74-bfcc-45c067a5e38a">

Was this working before? I checked out version 2.3.0 and did a grep for
'denote-forced-keywords' but could not find anything.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by x61** [comment]
> From: x61 ***@***.***> Date: Sat, 27 Apr 2024 01:45:40 -0700 Thanks gents for this work.
> You are welcome!
> Curios, has this been merged into the main denote.el?
> Yes, we are in the process of changing things.
> I have the recent commit of denote, installed version: 2.3.5 [0a75608](https://github.com/protesilaos/denote/commit/0a7560882e3f2d9a331191cda6cc7931723e4c30), but the `filetags` field is empty with the following template ``` ("t" "Todo" plain (file denote-last-path) (function (lambda () (let ((denote-prompts '(title)) (denote-forced-keywords '("journal")) (denote-forced-template 'journal)) (denote-org-capture)))) ``` <img width="773" alt="Screenshot 2024-04-27 at 04 41 08" src="https://github.com/protesilaos/denote/assets/6430853/5f37ad21-ca46-4d74-bfcc-45c067a5e38a">
> Was this working before? I checked out version 2.3.0 and did a grep for 'denote-forced-keywords' but could not find anything.
> […](#)
> -- Protesilaos Stavrou https://protesilaos.com

Thanks for your prompt response, @protesilaos. No, this was my first time trying it. I thought it was already merged. I was just too happy to see that this feature was implemented.  I'll wait for it to be merged. Take your time. Thank you

**Comment by protesilaos** [comment]
> From: x61 ***@***.***>
> Date: Sat, 27 Apr 2024 03:18:54 -0700
>
>> From: x61 ***@***.***> Date: Sat, 27 Apr 2024 01:45:40 -0700 Thanks gents for this work.
>> You are welcome!
>> Curios, has this been merged into the main denote.el?
>> Yes, we are in the process of changing things.
>> I have the recent commit of denote, installed version: 2.3.5 [0a75608](https://github.com/protesilaos/denote/commit/0a7560882e3f2d9a331191cda6cc7931723e4c30), but the `filetags` field is empty with the following template ``` ("t" "Todo" plain (file denote-last-path) (function (lambda () (let ((denote-prompts '(title)) (denote-forced-keywords '("journal")) (denote-forced-template 'journal)) (denote-org-capture)))) ``` <img width="773" alt="Screenshot 2024-04-27 at 04 41 08" src="https://github.com/protesilaos/denote/assets/6430853/5f37ad21-ca46-4d74-bfcc-45c067a5e38a">
>> Was this working before? I checked out version 2.3.0 and did a grep for 'denote-forced-keywords' but could not find anything.
>> […](#)
>> -- Protesilaos Stavrou https://protesilaos.com
>
> Thanks for your prompt response, @protesilaos. No, this was my first
> time trying it. I thought it was already merged. I was just too happy
> to see that this feature was implemented. I'll wait for it to be
> merged. Take your time. Thank you

Oh, okay! I got confused for a moment.

In the meantime, you can achieve what you want with existing functions.
Unless you specifically want to do it the way you demonstrated.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by x61** [comment]
> From: x61 ***@***.***> Date: Sat, 27 Apr 2024 03:18:54 -0700 > From: x61 ***@***.***> Date: Sat, 27 Apr 2024 01:45:40 -0700 Thanks gents for this work. > You are welcome! > Curios, has this been merged into the main denote.el? > Yes, we are in the process of changing things. > I have the recent commit of denote, installed version: 2.3.5 [[0a75608](https://github.com/protesilaos/denote/commit/0a7560882e3f2d9a331191cda6cc7931723e4c30)]([0a75608](https://github.com/protesilaos/denote/commit/0a7560882e3f2d9a331191cda6cc7931723e4c30)), but the `filetags` field is empty with the following template ``` ("t" "Todo" plain (file denote-last-path) (function (lambda () (let ((denote-prompts '(title)) (denote-forced-keywords '("journal")) (denote-forced-template 'journal)) (denote-org-capture)))) ``` <img width="773" alt="Screenshot 2024-04-27 at 04 41 08" src="https://github.com/protesilaos/denote/assets/6430853/5f37ad21-ca46-4d74-bfcc-45c067a5e38a"> > Was this working before? I checked out version 2.3.0 and did a grep for 'denote-forced-keywords' but could not find anything. > […](#) > -- Protesilaos Stavrou https://protesilaos.com Thanks for your prompt response, @protesilaos. No, this was my first time trying it. I thought it was already merged. I was just too happy to see that this feature was implemented. I'll wait for it to be merged. Take your time. Thank you
> Oh, okay! I got confused for a moment. In the meantime, you can achieve what you want with existing functions. Unless you specifically want to do it the way you demonstrated.
> […](#)
> -- Protesilaos Stavrou https://protesilaos.com

Yeah, I saw the changes in @jeanphilippegg's fork and I just did not check the main branch to ensure it made it there. I'll wait for it is be added. Thanks again

**Comment by jeanphilippegg** [comment]
This feature is not yet here. It should be soon.

What do you (@x61  and @protesilaos) think of the name of the variables? The `forced` part? Do you have a better name before we get it here?

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Sat, 27 Apr 2024 06:57:13 -0700
>
> This feature is not yet here. It should be soon.
>
> What do you ***@***.*** and @protesilaos) think of the name of the
> variables? The `forced` part? Do you have a better name before we get
> it here?

Fine by me.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by newmedicine** [comment]
-set-?
-specify-?
-override-?

-forced- seems a bit strong!

On 27 Apr 2024, at 14:57, Jean-Philippe Gagné Guay ***@***.***> wrote:

﻿

This feature is not yet here. It should be soon.

What do you ***@***.***<https://github.com/x61> and @protesilaos<https://github.com/protesilaos>) think of the name of the variables? The forced part? Do you have a better name before we get it here?

**Comment by protesilaos** [comment]
> From: Nick Bell ***@***.***>
> Date: Sat, 27 Apr 2024 10:45:10 -0700
>
> -set-?
> -specify-?
> -override-?

Those are fine as well.

> -forced- seems a bit strong!

I see. Well, Emacs use "kill" all over the place, but I guess we can
avoid that trap.

To add to your other suggestions, how about "denote-use-keywords" and
related? Or "denote-current-keywords"? Or "denote-lexical-keywords"?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by newmedicine** [comment]
-use- is perfect

On 27 Apr 2024, at 18:57, Protesilaos Stavrou ***@***.***> wrote:


> From: Nick Bell ***@***.***>
> Date: Sat, 27 Apr 2024 10:45:10 -0700
>
> -set-?
> -specify-?
> -override-?

Those are fine as well.

> -forced- seems a bit strong!

I see. Well, Emacs use "kill" all over the place, but I guess we can
avoid that trap.

To add to your other suggestions, how about "denote-use-keywords" and
related? Or "denote-current-keywords"? Or "denote-lexical-keywords"?

--
Protesilaos Stavrou
https://protesilaos.com

**Comment by jeanphilippegg** [comment]
I am closing this now. Most features are in Denote. There is still the feature of `denote-directory` that accepts a list of directories. I am not sure about including it in v3. It is a big feature and it does not really fit the theme of the changeset that we have for v3. Maybe we should wait to see how things go with our current changes?
