### ISSUE TITLE
Allow listing backlinks for denote files that are not notes

### ISSUE THREAD

**Issue by brabalan** [protesilaos/denote#318]
Use case: I have a pdf file in my denote files (with a denote file name) that I know is linked to in one or more notes, and I would like to have a list of these links.

At the moment, calling `denote-backlinks` does not work because it first checks that the current file is `denote-file-is-writable-and-supported-p`. Looking at the code, it seems that the only reason it needs it to be a note is in `denote-link--prepare-backlinks` to get its title in the backlink buffer by calling `denote-retrieve-front-matter-title-value`.

Would you consider a PR that removes this limitation?

**Comment by jeanphilippegg** [comment]
I have already made a pull request 2 weeks ago to solve this!

Pull request #304.

**Comment by protesilaos** [comment]
I just merged @jeanphilippegg PR. Thank you!

**Comment by brabalan** [comment]
Thanks a lot!
