### ISSUE TITLE
denote-org-extras-convert-links-to-file-type ignores value of org-link-file-path-type

### ISSUE THREAD

**Issue by gamecubate** [protesilaos/denote#319]
Hello @protesilaos . I've been using denote for a few days now and I like where you are taking this. And your documentation is of course exemplary. Thanks for that.

I use denotes as a personal wiki. So far so good.

Now, I want to use it as a web site CMS as well. For this, I use keywords such as `draft`, `final`, `publish` for my notes. I wrote some code that finds those files tagged `publish`, copies them to a working directory, and configures+invokes the org-publish command.

Cross-page links are broken, as expected, and I need to convert all `denote:` type links to `file:` ones. 

For this, I use your `denote-org-extras-convert-links-to-file-type` command. This command however does not seem to take the value of the `org-link-file-path-type` into account and this causes me problems in that the absolute paths generated  -- I had set the value of `org-link-file-path-type` to `adaptive` --  will no longer function once the exported notes have been copied to my server.

I could submit a PR if you'd like, one that will use the value of `org-link-file-path-type` at link conversion -- using `denote-get-path-by-id` or `denote-get-relative-path-by-id` depending on value or arg -- time.

Let me know.

Thx.

**Comment by gamecubate** [comment]
I won't need this after all; denote: links are handled correctly by org-publish and I now have a functional setup to publish to HTML denote notes tagged with specific keywords.

**Comment by protesilaos** [comment]
Thank you @gamecubate! I have not checked the `org-link-file-path-type` before, but am happy to have our functions respect its value. Please let me know if you will send a PR, otherwise I can write the change.

**Comment by gamecubate** [comment]
Hi. I will. News apace.

**Comment by gamecubate** [comment]
Hi @protesilaos. #325 submitted for your review [and approval or request for change(s)].

**Comment by protesilaos** [comment]
I just merged your changes. Made a few stylistic tweaks on top. Thank you!

The website looks good! I want to convert mine as well, but I have a ton of posts there so I need to be extra careful with the technicalities.
