### ISSUE TITLE
Documentation missing: denote-org-extras.el

### ISSUE THREAD

**Issue by julian-hoch** [protesilaos/denote#337]
Hi,
the info-manual references an " [...] optional 'denote-org-extras.el' extension [...]". I don't know where to get this / how to activate it, this is not mentioned anywhere. 
I am fairly new to emacs, but usually I manage to install packages I am interested in, but in this case, I am at a loss.
I would suggest updating the documentation with info on how to get this extension.

**Comment by protesilaos** [comment]
> From: Julian Hoch ***@***.***>
> Date: Mon,  6 May 2024 10:50:04 -0700
>
> Hi,

Hello there!

> the info-manual references an " [...] optional 'denote-org-extras.el' extension [...]". I don't know where to get this / how to activate it, this is not mentioned anywhere. 
> I am fairly new to emacs, but usually I manage to install packages I am interested in, but in this case, I am at a loss.
> I would suggest updating the documentation with info on how to get this extension.

It is part of the Denote package you already have installed. You can
call one of its commands directly. Please let me know if that works for
you.

Though, yes, I am happy to clarify this point.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by julian-hoch** [comment]
Hi Prot!
Thanks for taking the time to respond, I love your work, big fan btw.
But I do not see the command mentioned in the documentation, in fact, I do not see any "org" related commands:
![May07::080725](https://github.com/protesilaos/denote/assets/95583314/ee657c38-89bc-42b9-bef7-f4381af7016e)
I am not sure then if my installation is broken or just severely out of date?
The manual mentions 2.3.0 (which looking at the repo should already include these functions?), and this is the output from list-packages filtered on denote:

11 matches in 6 lines for "denote" in buffer: *Packages*
    679:  citar-denote                   20240505.34    available    melpa    Minor mode integrating Citar and Denote
   1145:  denote-explore                 20240426.450   available    melpa    Explore Denote files
   1146:  denote-menu                    1.2.0          available    gnu      View denote files in a tabulated list.
   1147:  denote-menu                    1.2.0          available    elpa     View denote files in a tabulated list.
   1148:  denote-refs                    0.1.2          available    nongnu   Show links and backlinks in Denote notes
   6665:  denote                         2.3.5          installed             Simple notes with an efficient file-naming scheme

Thanks for your assistance,
Julian

**Comment by protesilaos** [comment]
Oh, this is strange! What happens if you evaluate this?

```elisp
(require 'denote-org-extras)
```

**Comment by julian-hoch** [comment]
Hi Prot! Yeah it was strange - until I reinstalled the package! Not sure what had caused this, but after reinstalling the package it now works as expected!
So I blame this on my emacs configuration - probably something about the way I set up the package manager or something, when I have a few hours that is something that I will need to understand and fix.
Julian

**Comment by protesilaos** [comment]
> From: Julian Hoch ***@***.***>
> Date: Tue,  7 May 2024 01:08:56 -0700
>
> Hi Prot! Yeah it was strange - until I reinstalled the package! Not sure what had caused this, but after reinstalling the package it now works as expected!
> So I blame this on my emacs configuration - probably something about the way I set up the package manager or something, when I have a few hours that is something that I will need to understand and fix.

Okay, no worries! This probably happens if you install the package
manually, because then you need to generate autoloads yourself.
Otherwise, the built-in package manager handles this automatically. Same
for other package managers like straight.el and elpaca.

-- 
Protesilaos Stavrou
https://protesilaos.com
