### ISSUE TITLE
denote-link creates a button for non-org files

### ISSUE THREAD

**Issue by haji-ali** [protesilaos/denote#340]
Currently, `denote-link` creates a button around the link when the major mode is not `org-mode`. This is a temporary solution as it means that if the note is closed and re-opened the button disappears.

I am writing a font-lock function to enable fontifying the link and making it clickable, but the button that denote creates will interfere with it. It would be great if this button creation is controlled with an option, though I would argue that it should not be created at all.

**Comment by protesilaos** [comment]
> From: Abdul-Lateef Haji-Ali ***@***.***>
> Date: Wed,  8 May 2024 14:40:58 -0700
>
> Currently, `denote-link` creates a button around the link when the
> major mode is not `org-mode`. This is a temporary solution as it means
> that if the note is closed and re-opened the button disappears.

Indeed, it disappears aferwards. Something like this re-enables it:

    (add-hook 'find-file-hook #'denote-link-buttonize-buffer)

> I am writing a font-lock function to enable fontifying the link and
> making it clickable, but the button that denote creates will interfere
> with it. It would be great if this button creation is controlled with
> an option, though I would argue that it should not be created at all.

Is this function going to do more than make the links clickable? In
other words, is denote-link-buttonize-buffer not suitable for your
needs?

Add an option is fine, though I am trying to understand the case better.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by haji-ali** [comment]
I think implementing this feature through font-lock is more standard (and would allow automatic formatting if the link is edited). Also, I wanted to implement folding of links similar to org-mode (using `org-fold` or overlays).

Perhaps moving the button creation and hook into a minor-mode that can be enabled or disabled is best?

**Comment by protesilaos** [comment]
> From: Abdul-Lateef Haji-Ali ***@***.***>
> Date: Thu,  9 May 2024 00:40:19 -0700
>
> I think implementing this feature through font-lock is more standard
> (and would allow automatic formatting if the link is edited). Also, I
> wanted to implement folding of links similar to org-mode (using
> `org-fold` or overlays).

Sounds good! If you do work on this, consider sending a patch or pull
request.

> Perhaps moving the button creation and hook into a minor-mode that can
> be enabled or disabled is best?

Fine by me. Though the :init-value must be non-nil to preserve the
current behaviour. But then users get the opt-out functionality.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I forgot to close this. We are done here. Thank you!
