### ISSUE TITLE
Files being renamed with "denote-rename-file" that don't have the file extension defined in denote-file-types will be turned into an org file

### ISSUE THREAD

**Issue by Kolmas225** [protesilaos/denote#343]
Steps to reproduce:

1. create a file which isn't ending in .org/.md/.txt (e.g. test.png)
2. navigate to the file in dired and `M-x denote-rename-file` and go through the prompts
3. the confirmation will show the file being renamed to an org file (e.g. Rename test.png to 20240510T230235--test__testing.org? (y or n) )

**Comment by protesilaos** [comment]
Thank you! I just pushed a change. Please let me know how it goes.

**Comment by protesilaos** [comment]
> From: Kolmas ***@***.***>
> Date: Fri, 10 May 2024 12:16:31 -0700
>
> It works as intended, thank you for the quick fix!

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
