### ISSUE TITLE
`denote-rename-file-signature` will copy DATE again.

### ISSUE THREAD

**Issue by kilesduli** [protesilaos/denote#347]
![image](https://github.com/protesilaos/denote/assets/43215593/4ad48196-cfa3-42ae-bf63-e4a744dae608)

in latest elpa mirror 427f0dd

**Comment by protesilaos** [comment]
Thank you! I just pushed a change for this. Please let me know if all is good on your end.

**Comment by kilesduli** [comment]
It looks good me. Thanks for the quick fix
