### ISSUE TITLE
Bug: `denote-org-extras-link-to-heading` generates link in wrong heading.

### ISSUE THREAD

**Issue by kilesduli** [protesilaos/denote#354]
when using this function add new heading level link, It will generate link after the level.
For example: select 1a1 and actually insert 1a1a.

![image](https://github.com/protesilaos/denote/assets/43215593/eacd8591-fa43-4a70-ac1f-82a58f55b123)
![image](https://github.com/protesilaos/denote/assets/43215593/3af279a0-94a9-469c-8f93-ee4fd29f89a8)

**Comment by protesilaos** [comment]
I just pushed the change. Please let me know if it works for you.

**Comment by kilesduli** [comment]
> I just pushed the change. Please let me know if it works for you.

Looks good to me. Thank you for the fix.

**Comment by protesilaos** [comment]
> From: duli ***@***.***>
> Date: Sat, 18 May 2024 08:14:32 -0700
>
>> I just pushed the change. Please let me know if it works for you.
>
> Looks good to me. Thank you for the fix.

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
