### ISSUE TITLE
Problem when creating new notes

### ISSUE THREAD

**Issue by Kolmas225** [protesilaos/denote#357]
After calling `denote` to create new note, and going through all the prompt,
the following error shows up
`denote: Wrong type argument: stringp, #<buffer 20240518T010559--aien__testing.org>`
And the resulting file was lacking frontmatter and not being saved despite having `denote-save-buffers` set to `t` 

The problem stops after reverting bce7778

**Comment by jeanphilippegg** [comment]
Oh, sorry. I will make a pull request to fix this.
