### ISSUE TITLE
Support doing buttonization, and inserting links, in unrecognized file types (e.g. source code?)

### ISSUE THREAD

**Issue by alexispurslane** [protesilaos/denote#364]
When I saw that Denote supported buttonization in non-org modes like Markdown and plain text, it occurred to me that this could be used to link to Denote notes from basically any file, including the comments of source code, which could be extremely useful.

Additionally, there's no reason you couldn't insert a Denote link in any file type, even if it isn't recognized, right? There would just need to be a variable set to tell it how to format that link by default, since it wouldn't be able to tell what markup to use based on the filetype. Maybe the `denote-file-type` variable could do double duty for that?

Or, hell, you could do in unrecognized text files what you already do in plain text files and just default to org format!

If you're interested I'd be willing to attempt to make a PR to do this.

**Comment by alexispurslane** [comment]
I just adviced denote's function to test whether a file type is supported to always return true, and links between denote notes and code files worked beautifully, as did buttonization.

**Comment by protesilaos** [comment]
One way to handle this is to always format links using the Org syntax. Then use `M-x org-open-at-point-global` on it.

**Comment by alexispurslane** [comment]
> One way to handle this is to always format links using the Org syntax. Then use `M-x org-open-at-point-global` on it.

That would work to open a note link, but it wouldn't allow inserting the note link, despite all the information necessary to do so being at hand, and it also wouldn't highlight any available links. The solution I went with was this:

```lisp
(advice-add 'denote-file-has-supported-extension-p :filter-return (lambda (x) t))
```

And then relying on `(add-hook 'find-file-hook #'denote-link-buttonize-buffer)` from the manual — that made link inserting, link clicking, and link buttonization all work.

**Comment by protesilaos** [comment]
I just added this to the manual, which is probably safer:

```elisp
(defun my-denote-link-global (file file-type description &optional id-only)
  "Like the `denote-link', but works in any buffer.
The FILE, FILE-TYPE, DESCRIPTION, and ID-ONLY have the same meaning as
in `denote-link'."
  (interactive
   (let* ((file (denote-file-prompt nil "Link to FILE"))
          (file-type (denote-filetype-heuristics buffer-file-name))
          (description (when (file-exists-p file)
                         (denote--link-get-description file))))
     (list file file-type description current-prefix-arg)))
  (unless (file-exists-p file)
    (user-error "The linked file does not exists"))
  (let ((beg (point)))
    (denote--delete-active-region-content)
    (insert (denote-format-link file description file-type id-only))
    (unless (derived-mode-p 'org-mode)
      (make-button beg (point) 'type 'denote-link-button))))
```

I am open to having something like this in denote.el though it is just that nobody asked for it before. In such cases, we keep the code in the manual and think what to do about it once we have more feedback.

Note that if you are tracking denote.git, this depends on commit `bd14d37`.  If you do try it, please let me know if it works for you.

**Comment by alexispurslane** [comment]
Thank you so much! I'll try it out

**Comment by protesilaos** [comment]
> From: Alexis Purslane ***@***.***>
> Date: Mon, 20 May 2024 03:38:13 -0700
>
> Thank you so much! I'll try it out

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by alexispurslane** [comment]
> If you do try it, please let me know if it works for you.

FYI, I put this in my config and gave it a spin and it seems to work great! I haven't used it in anger yet, but I don't see why it would stop working.

**Comment by protesilaos** [comment]
> From: Alexis Purslane ***@***.***>
> Date: Mon, 20 May 2024 18:13:45 -0700
>
>> If you do try it, please let me know if it works for you.
>
> FYI, I put this in my config and gave it a spin and it seems to work
> great! I haven't used it in anger yet, but I don't see why it would
> stop working.

Sounds good! I say we close this issue then and if a problem arises then
we reopen it.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by alexispurslane** [comment]
Oh, I did find an issue with your more surgical code (as opposed to my sledgehammer approach): with the original file-type-recognized function intact, denote-link-buttonize-buffer now only works on file types it considers "safe", so buttonization only works in e.g. code comments the first time you insert it, and not subsequently. I don't know how I missed that the first time around. I guess I don't restart emacs that often.
