### ISSUE TITLE
Version in tar file differs from latest tagged release

### ISSUE THREAD

**Issue by doolio** [protesilaos/denote#370]
FYI, at the time of writing the version in the tar file (v2.3.5) visible on `elpa` differs from latest tagged release (v.2.3.0). The date too but perhaps that just reflects the upload to `elpa` date.

![image](https://github.com/protesilaos/denote/assets/13859009/0e168125-bd20-4f04-9e64-7db8fca624d8)

**Comment by protesilaos** [comment]
Hello @doolio! This is because I do not tag the `x.y.Z` releases. Those are meant to rebuild the package on GNU ELPA.

Have you encountered a problem with this?

**Comment by doolio** [comment]
I see. Thanks for the clarification. No problems encountered. Sorry for the noise.

**Comment by protesilaos** [comment]
Well, it turns out [we have problem with Guix](https://github.com/protesilaos/denote/issues/371), so I pushed the new tag. Thanks!
