### ISSUE TITLE
Identifier showing up in keyword section when creating/renaming denote files

### ISSUE THREAD

**Issue by Kolmas225** [protesilaos/denote#375]
if `denote-file-name-components-order` was set in a order that keyword is immediately followed by the identifier
e.g.: `(denote-file-name-components-order '(title signature keywords identifier))`
then the last keyword will be shown along with identifier instead of the keyword alone: `keyword@@identifier` when creating new notes / modifying keywords with `denote-rename-files`
![Screenshot from 2024-06-08 16-55-39](https://github.com/protesilaos/denote/assets/169401425/f8cc64b0-112c-4836-a5c4-00d9cbfc7353)

**Comment by protesilaos** [comment]
Thank you! I just pushed a change. Please let me know if it works for you.
