### ISSUE TITLE
Ignored Files Regexp

### ISSUE THREAD

**Issue by swflint** [protesilaos/denote#376]
Similar to how completion, in general, has `completion-ignored-extensions`, would it be possible to define a regular expression to ignore files in the output of `denote-directory-files`?  That way, this option could be set once by a user (e.g., to ignore TeX output files), to make it so that downstream tools do not misinterpret these files.

**Comment by protesilaos** [comment]
> From: "Samuel W. Flint" ***@***.***>
> Date: Fri, 14 Jun 2024 13:35:26 -0700
>
> Similar to how completion, in general, has
> `completion-ignored-extensions`, would it be possible to define a
> regular expression to ignore files in the output of
> `denote-directory-files`? That way, this option could be set once by a
> user (e.g., to ignore TeX output files), to make it so that downstream
> tools do not misinterpret these files.

Our relevant function is this one:

(defun denote--directory-all-files-recursively ()
  "Return list of all files in variable `denote-directory'.
Avoids traversing dotfiles (unconditionally) and whatever matches
`denote-excluded-directories-regexp'."
  (directory-files-recursively
   (denote-directory)
   directory-files-no-dot-files-regexp
   :include-directories
   #'denote--directory-files-recursively-predicate
   :follow-symlinks))

The 'directory-files-recursively' accepts a REGEXP argument. Right now
we use the built-in 'directory-files-no-dot-files-regexp'. We can
replace it with a 'defvar' that (i) retains the current value while (ii)
allows the user to configure what files are returned.

What do you think?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
> From: "Samuel W. Flint" ***@***.***>
> Date: Sat, 15 Jun 2024 06:10:01 -0700
>
> Other than a concern about it being `defvar` over `defcustom`, that
> seems like it would do what I want.

We can have a defcustom eventually. Though I suggest we start with a
defvar so that only experienced users discover it. This way we can
experiment with it more and decide how best to implement it (if we need
more than just a variable that holds the regexp).

To the point though, please try to run 'denote--directory-all-files-recursively'
with the change to the part where it uses 'directory-files-no-dot-files-regexp'.
My quick test suggests this is enough.

We may need to write a doc string that recommends how to extend
'directory-files-no-dot-files-regexp' rather than override it, but that
is another issue.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
Hello again @swflint! Have you had the chance to experiment with this?

> To the point though, please try to run 'denote--directory-all-files-recursively'
with the change to the part where it uses 'directory-files-no-dot-files-regexp'.
My quick test suggests this is enough.

If that works for you, then we can introduce the relevant variable.

**Comment by swflint** [comment]
That seems to work, though it feels like it may require more configuration than I had hoped (I already customize `completion-ignored-extensions`, and it seems that that would be a reasonable variable to obey).

**Comment by protesilaos** [comment]
The doc string of `completion-ignored-extensions` mentions that the matches are not always excluded. Anyway, we do not have any special code for this in Denote. Whatever behaviour you see should be the default.

That aside, I have created a new branch called `excluded-files-regexp`, which provides a user option to exclude files that match a regular expression. If you can test it, please let me know if it works for you.

**Comment by protesilaos** [comment]
I have now merged that branch. Will prepare for the release of Denote version `3.0.0`. Thanks!

**Comment by swflint** [comment]
Much appreciated!  Thank you!

**Comment by protesilaos** [comment]
> From: "Samuel W. Flint" ***@***.***>
> Date: Mon,  1 Jul 2024 09:10:55 -0700
>
> Much appreciated!  Thank you!

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
