### ISSUE TITLE
Dynamic block is not working 

### ISSUE THREAD

**Issue by rootid** [protesilaos/denote#379]
I'm using denote 2.3.0 
I added below snippet in org mode 
```
#+BEGIN: denote-links :regexp "emacs" :id-only nil

#+END:
```
But when I run org-update-dblock I get an error 

org-update-dblock: Symbol’s function definition is void: org-dblock-write:denote-links

However,  If I use denote-add-link and use same regexp it works fine.

**Comment by bryanrinders** [comment]
From the error I am assuming you typed the dynamic block out by hand. Try `M-x denote-org-extras-dblock-insert-links` to generate the dblock instead, it should fix your problem.

**Comment by rootid** [comment]
Thanks it's working now
