### ISSUE TITLE
denote-journal-extras-new-or-existing-entry creates new file every time

### ISSUE THREAD

**Issue by elge70** [protesilaos/denote#381]
For denote-journal, In the manual it is given as 
_"The command denote-journal-extras-new-or-existing-entry locates an existing journal entry or creates a new one. A journal entry is one that has denote-journal-extras-keyword as part of its file name. If there are multiple journal entries for the current date, it prompts for one among them using minibuffer completion. If there is only one, it visits it outright. If there is no journal entry, it creates one by calling denote-journal-extra-new-entry (as described above)."

For a given day, whenever I call denote-journal-extras-new-or-existing-entry, it creates a new file due to different timestamp. Could this function open the journal file created for the day if nothing has changed (eg. keyword) ? Is it possible to get similar behavior as "denote-open-or-create" where I can browse and select the file or open the journal file already created for the day?

**Comment by protesilaos** [comment]
> From: elge70 ***@***.***>
> Date: Fri, 21 Jun 2024 05:15:44 -0700

> [... 10 lines elided]

> For a given day, whenever I call
> denote-journal-extras-new-or-existing-entry, it creates a new file due
> to different timestamp. Could this function open the journal file
> created for the day if nothing has changed (eg. keyword) ? Is it
> possible to get similar behavior as "denote-open-or-create" where I
> can browse and select the file or open the journal file already
> created for the day?

Can you tell me more about the "different timestamp" part? What settings
do you use and/or what workflow do you follow?

The 'denote-journal-extras-new-or-existing-entry' seems to work fine on
my end, so I need to be able to reproduce your problem.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by elge70** [comment]
My Config for denote is as follows
```
(use-package denote
  :defer 2
  :config
  (require 'denote-silo-extras)
  (require 'denote-org-extras)
  (require 'denote-journal-extras)
  (setq denote-directory (expand-file-name "~/Repo/MyNotes"))
  (setq denote-known-keywords '("Home" "Office" "Finance" "Stocks" "Info" "Tech" ))
  (setq denote-infer-keywords t)
  (setq denote-sort-keywords t)
  (setq denote-file-type nil)
  (setq denote-prompts '(title keywords))
  (setq denote-excluded-directories-regexp nil)
  (setq denote-excluded-keywords-regexp nil)
  (setq denote-date-prompt-use-org-read-date t)
  (setq denote-allow-multi-word-keywords t)
  (setq denote-date-format nil)
  (add-hook 'find-file-hook #'denote-link-buttonize-buffer)
  (add-hook 'dired-mode-hook #'denote-dired-mode)
  (setq denote-journal-extras-directory "/Users/XX/OneDrive/Tasks/Journal")
  (setq denote-journal-extras-title-format 'day-date-month-year)
  (setq denote-journal-extras-keyword "GZJournal")
  (setq denote-silo-extras-directories `("/Users/XX/OneDrive/Tasks"
                                         ,denote-directory)))

(add-hook 'org-mode-hook 'denote-link-buttonize-buffer)
(add-hook 'dired-mode-hook #'denote-dired-mode)
```

timestamp:- Whenever file is created , the name is prefixed with timestamp  "20240621T173256--friday-21-june-2024__gzjournal.org". When I call this function again I get another file " 20240621T191446--friday-21-june-2024__gzjournal.org". Since file name is different in both cases, it may create different files each time. ( I am not sure how lisp code works)

**Comment by elge70** [comment]
I have saved the files all the time.  I have created new files as shown below whenever I call "denote-journal-extras-new-or-existing-entry"

```
la---        21-06-2024     19:55            165   20240621T195531--friday-21-june-2024__gzjournal.org
la---        21-06-2024     19:56            159   20240621T195625--friday-21-june-2024__gzjournal.org
```

I am using Emacs 29.3 on Windows 11. Org version 9.6.15 and denote version 2.3.5. My Journal directory is inside a silos directory and not in regular denote-directory. Is that could be the issue?

**Comment by protesilaos** [comment]
> From: elge70 ***@***.***>
> Date: Fri, 21 Jun 2024 07:38:22 -0700

> [... 11 lines elided]

> My Journal directory is inside a silos directory and not in regular
> denote-directory. Is that could be the issue?

Good idea! I tried it, though I could not reproduce the problem.

What I did:

- Created a silo.
- Called the 'denote-journal-extras-new-or-existing-entry' command.
- Wrote some text in the buffer, just to be sure.
- Saved the buffer.
- Killed the buffer.
- Then inside the same directory, I re-run the command.
- It brought me back to the original file it created.

The only way to recreate the problem, is to call the command once inside
and then once outside the silo. But this would then be the expected
behaviour.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by elge70** [comment]
Thanks. I can bring back the old file if I am in silos directory. But since I have set "denote-journal-extras-directory" to a directory inside silos, denote could search in that directory when we call 'denote-journal-extras-new-or-existing-entry' command? Now the issue is that I must open another file inside silos to get the correct behavior. Is there any shortcut to get the right file without opening a file in Silos ?

**Comment by protesilaos** [comment]
> From: elge70 ***@***.***>
> Date: Fri, 21 Jun 2024 08:15:25 -0700
>
> Thanks. I can bring back the old file if I am in silos directory. But
> since I have set "denote-journal-extras-directory" to a directory
> inside silos, denote could search in that directory when we call
> 'denote-journal-extras-new-or-existing-entry' command? Now the issue
> is that I must open another file inside silos to get the correct
> behavior. Is there any shortcut to get the right file without opening
> a file in Silos ?

Evaluate this, while replacing the path to the silo:

(defun my-denote-journal-extras-new-or-existing-entry ()
  "Like `denote-journal-extras-new-or-existing-entry' for my silo."
  (interactive)
  (let ((denote-directory "/path/to/silo/"))
    (call-interactively 'denote-journal-extras-new-or-existing-entry)))

Then you can invoke 'my-denote-journal-extras-new-or-existing-entry'
from anywhere.

Please try it.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by elge70** [comment]
Thank you. This is working perfectly. In next release notes, this could be mentioned as a snippet. It could be useful for someone who would like to have Personal Journal and Office Journal

**Comment by protesilaos** [comment]
> From: elge70 ***@***.***>
> Date: Fri, 21 Jun 2024 09:39:40 -0700
>
> Thank you. This is working perfectly.

Very well!

> In next release notes, this could be mentioned as a snippet. It could
> be useful for someone who would like to have Personal Journal and
> Office Journal

I thought I had something like this in the manual, but I will check
again. If there is nothing, I will add it. Will mention it in the
release notes as well (though those are long too, so I do not know if it
is helpful in practice to have them there).

-- 
Protesilaos Stavrou
https://protesilaos.com
