### ISSUE TITLE
denote-file-prompt shouldn't match archive files ?

### ISSUE THREAD

**Issue by zadca123** [protesilaos/denote#384]
I tried to use `C-c $`, `org-archive-subtree` to archive tree that i already done stuff from, but i would like to keep in my notes. This creates a file with the same name as note but with `_archive` suffix. But denote still finds this file when using `denote` or `denote-open-or-create`. So filetype function shoundn't match this suffix?

**Comment by protesilaos** [comment]
I think what you suggest makes sense. We were already discussing this [in issue 376](https://github.com/protesilaos/denote/issues/376).

I have created a new branch called `excluded-files-regexp`. It includes the `denote-excluded-files-regexp` variable that you can set to a regular expression (or simply `"_archive"` if that is all you wish to omit). If you can try it, please let me know how it goes.

**Comment by zadca123** [comment]
Okay, i have tested simple `(setq denote-excluded-files-regexp "_archive$")` and it works nicely.

**Comment by protesilaos** [comment]
I have now merged that branch and will prepare for the release of Denote `3.0.0`. Thank you!
