### ISSUE TITLE
Rename existing files after changes to denote-file-name-components-order?

### ISSUE THREAD

**Issue by johkneisl** [protesilaos/denote#390]
Hi, 
I appreciate the new option to change the order of denote file name components via `denote-file-name-components-order`.

Is it possible to "rename" existing denote files after the option has been set?
Of course, rename here would mean to keep identifier, title, keywords, and extension the same, but change their order. 

Say I have a file titled 

`20240519T07345--this-is-the-title__denote_testing.org`

then I set `(setq denote-file-name-components-order '(title identifier keywords))`

now I want denote to rename that file to 

`--this-is-the-title@@20240519T07345__denote_testing.org`

The ordinary `denote-rename-file` doesn't seem to do the trick.

**Comment by protesilaos** [comment]
> From: johkneisl ***@***.***>
> Date: Tue,  9 Jul 2024 17:24:40 -0700

> [... 11 lines elided]

> then I set `(setq denote-file-name-components-order '(title identifier keywords))`
>
> now I want denote to rename that file to 
>
> `--this-is-the-title@@20240519T07345__denote_testing.org`
>
> The ordinary `denote-rename-file` doesn't seem to do the trick.

Strange... This is working on my end. At each prompt, I hit RET to
accept the default value and at the end I get the confirmation to rename
the file, showing me the rearrangement that is to happen.

Perhaps you need to evaluate the 'denote-file-name-components-order'
again because something is missing there? Also make sure you are on the
latest version of Denote.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by johkneisl** [comment]
Sorry, it does indeed work as expected now. 
I pulled the latest version of denote, but it hasn't been built because I didn't restart emacs.
This can be closed then, thanks a lot.

**Comment by protesilaos** [comment]
> From: johkneisl ***@***.***>
> Date: Wed, 10 Jul 2024 04:16:11 -0700
>
> Sorry, it does indeed work as expected now. 
> I pulled the latest version of denote, but it hasn't been built
> because I didn't restart emacs.

No worries!

> This can be closed then, thanks a lot.

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
