### ISSUE TITLE
markdown links in org files are opened in an external app

### ISSUE THREAD

**Issue by brabalan** [protesilaos/denote#391]
It seems that using `org-link-open-as-file` when following denote links in org buffers is problematic, as the file is not opened in emacs by default. Changing it to `find-file` works for me.

See https://github.com/protesilaos/denote/blob/main/denote.el#L4656

**Comment by brabalan** [comment]
As a follow-up, using `find-file` breaks denote links of the form `denote:20201113T081711::*Save all the tags`, so it is probably not the solution…

**Comment by protesilaos** [comment]
> From: Alan Schmitt ***@***.***>
> Date: Fri, 12 Jul 2024 02:25:24 -0700
>
> It seems that using `org-link-open-as-file` when following denote
> links in org buffers is problematic, as the file is not opened in
> emacs by default. Changing it to `find-file` works for me.
>
> See https://github.com/protesilaos/denote/blob/main/denote.el#L4656

There is the variable 'org-file-apps' which should control this
behaviour. Maybe this will work?

    (add-to-list 'org-file-apps '("\\.md\\'" . emacs))

Check the doc string of 'org-file-apps', as you may prefer to just use
't' instead of matching markdown files in particular.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
> From: Alan Schmitt ***@***.***>
> Date: Fri, 12 Jul 2024 02:38:33 -0700
>
> As a follow-up, using `find-file` breaks denote links of the form
> `denote:20201113T081711::*Save all the tags`, so it is probably not
> the solution…

Indeed! I will remove that comment. We want to respect what Org is doing
in this regard. If the 'org-file-apps' works, then we can recommend
using that.
 
-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by brabalan** [comment]
> There is the variable 'org-file-apps' which should control this behaviour. Maybe this will work? (add-to-list 'org-file-apps '("\\.md\\'" . emacs)) Check the doc string of 'org-file-apps', as you may prefer to just use 't' instead of matching markdown files in particular.

This works great, thanks!
