### ISSUE TITLE
`denote-rename-buffer-mode` breaks Org capture detection

### ISSUE THREAD

**Issue by skissue** [protesilaos/denote#393]
When `denote-rename-buffer-mode` is enabled, the buffers for Org capture are renamed to use the title of the Denote file. This breaks `denote--file-type-org-extra-p`, which checks for capture buffers using the regexp "`CAPTURE.*\\.org", which looks for a buffer name ending in ".org". This results in these buffers throwing a file type error when attempting to e.g. create a link.

**Comment by protesilaos** [comment]
It seems to work on my end. Anyway, I think we do not need to rename that buffer. Does evaluating this fix the problem?

```elisp
(defun denote-rename-buffer (&optional buffer)
  "Rename current buffer or optional BUFFER with `denote-rename-buffer-format'.
The symbol of this function is the default value of the user
option `denote-rename-buffer-function' and is thus used by the
`denote-rename-buffer-mode'."
  (when-let ((file (buffer-file-name buffer))
             ((not (denote--file-type-org-extra-p)))
             ((denote-file-has-identifier-p file))
             (new-name (denote-rename-buffer--format (or buffer (current-buffer))))
             ((not (string-blank-p new-name))))
    (rename-buffer new-name :unique)))
```

The diff:

```diff
 denote-rename-buffer.el | 1 +
 1 file changed, 1 insertion(+)

diff --git a/denote-rename-buffer.el b/denote-rename-buffer.el
index 1335d3a..ed07ded 100644
--- a/denote-rename-buffer.el
+++ b/denote-rename-buffer.el
@@ -112,6 +112,7 @@ (defun denote-rename-buffer (&optional buffer)
 option `denote-rename-buffer-function' and is thus used by the
 `denote-rename-buffer-mode'."
   (when-let ((file (buffer-file-name buffer))
+             ((not (denote--file-type-org-extra-p)))
              ((denote-file-has-identifier-p file))
              (new-name (denote-rename-buffer--format (or buffer (current-buffer))))
              ((not (string-blank-p new-name))))
```

**Comment by skissue** [comment]
> It seems to work on my end. 

In case it is important, here are my versions:
- Emacs: 31.0.50 (built from `900f135b68b4e9830eac5d7500b3175f160f6c34`)
- Org: 9.7.6
- Denote: 3.0.6

I did some digging, and it seems to happen because `denote-rename-buffer-mode` hooks into `find-file-hook`, and `org-capture-target-buffer` uses `find-file-noselect` to create a buffer, which results in it being renamed. `org-capture-get-indirect-buffer` then prefixes the resultant buffer with "CAPTURE-", resulting in a buffer name formatted like "CAPTURE-<title>", which is not matched by `denote--file-type-org-extra-p`.

> Does evaluating this fix the problem?

Nope, adding that line results in `denote-rename-buffer` not working on *any* Org buffer, but still being broken in capture buffers.

Personally, I'm a little confused as to the anatomy of `denote--file-type-org-extra-p`. Is there any situation where the current buffer would be derived from `org-mode`, but we *wouldn't* want to consider it as Org?

**Comment by protesilaos** [comment]
I will rebuild Emacs now and get back to you, because I cannot reproduce the problem. Then we see how to proceed.

**Comment by protesilaos** [comment]
> Personally, I'm a little confused as to the anatomy of `denote--file-type-org-extra-p`. Is there any situation where the current buffer would be derived from `org-mode`, but we _wouldn't_ want to consider it as Org?

I don't remember the specifics anymore, though we had an issue where our file type heuristics were not working in those special buffers. It must have been related to linking, since we have this in `denote-link`:

```elisp
  (unless (or (denote--file-type-org-extra-p)
              (and buffer-file-name (denote-file-has-supported-extension-p buffer-file-name)))
    (user-error "The current file type is not recognized by Denote"))
```

I now re-read your issue and realise I misunderstood it. The renaming was never a problem for creating notes, but only for breaking `denote--file-type-org-extra-p`, which in turns breaks linking from there.

As such, maybe this is enough?

```diff
 denote.el | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/denote.el b/denote.el
index 6117144..66484a4 100644
--- a/denote.el
+++ b/denote.el
@@ -2632,7 +2632,7 @@ (defun denote--file-type-org-extra-p ()
   "Return non-nil if this is an `org-capture' or Org Note buffer."
   (and (derived-mode-p 'org-mode)
        (or (and (bound-and-true-p org-capture-mode)
-                (string-match-p "\\`CAPTURE.*\\.org" (buffer-name)))
+                (string-match-p "\\`CAPTURE.*" (buffer-name)))
            (string-match-p "\\`\\*Org Note\\*" (buffer-name)))))
 
 (defun denote-filetype-heuristics (file)
```

Or is there a scenario where `CAPTURE` will not be a prefix?

**Comment by skissue** [comment]
> As such, maybe this is enough?

Yup, that seems to resolve the linking issue :+1:.

> Or is there a scenario where `CAPTURE` will not be a prefix?

Nope, seems like `org-capture-get-indirect-buffer` sets the prefix to an argument which is hardcoded as "CAPTURE" (at the calling site in `org-capture-place-template`). Notably, the prefix also includes a dash (`CAPTURE-`), so perhaps that could be added to the regexp to be slightly more accurate.

**Comment by protesilaos** [comment]
Thank you! I just pushed the change, include the `CAPTURE-` part.
