### ISSUE TITLE
Support using functions in `denote-templates`

### ISSUE THREAD

**Issue by skissue** [protesilaos/denote#394]
Would it be possible to support using arbitrary functions as the content value for `denote-templates`? I have some templates that I would like to use dynamically-generated content in, and this seems like the simplest and cleanest way to do so, since we'd just have to check the type of each value, and, if it's a function, call it to get the template string.

**Comment by protesilaos** [comment]
Hello @skissue! I think this makes total sense. I had kept this simple because I did not know how much demand there is for it. If you have some code already, I am happy to see it and merge it.

**Comment by skissue** [comment]
I went ahead and took a shot implementing the feature in https://github.com/skissue/denote/commit/80597c4f0c33a3b0d59de4dc353d6b83c928d52a. I'm not sure if this code is ideal, so I'd appreciate some feedback. If it looks good, I can submit a PR.

**Comment by protesilaos** [comment]
> From: Ad ***@***.***>
> Date: Wed, 17 Jul 2024 09:37:11 -0700
>
> I went ahead and took a shot implementing the feature in
> https://github.com/skissue/denote/commit/80597c4f0c33a3b0d59de4dc353d6b83c928d52a.
> I'm not sure if this code is ideal, so I'd appreciate some feedback.
> If it looks good, I can submit a PR.

Thank you! I will take a look tomorrow morning, as I will be out of
electricity soon.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I just took a look: it is fine; please send the PR.

I wonder if it makes sense to have the function accept arguments. Maybe users can do more with that, though I do not have a use-case in mind. Those who do not need to process the arguments, can write a function with `(&rest _args)`, where they ignore everything. If we have some examples, we can mention them in the manual.
