### ISSUE TITLE
[Suggestion] Getting the id of a denote link at point

### ISSUE THREAD

**Issue by brabalan** [protesilaos/denote#400]
I have the following code to do open the target of a denote link in dired:
```emacs-lisp
(defun my-denote-dired-jump-org-denote-link ()
  (interactive)
  (let ((id (my-denote-get-id-at-point)))
    (if id
        (let ((file (denote-get-path-by-id id)))
          (if file (dired-jump nil file)
            (user-error "Denote id %s not found" id)))
      (user-error "No link found"))))
```

It uses `my-denote-get-id-at-point`, which is custom code that used to rely on `denote-link--link-at-point-string` that was removed in https://github.com/protesilaos/denote/commit/76098aaafc13a10bbaf1df7700f0010492e46cb4. I recreated it with this piece of code:
```emacs-lisp
(defun my-denote-get-id-at-point ()
  (when (or (thing-at-point-looking-at denote-id-only-link-in-context-regexp)
            (thing-at-point-looking-at denote-md-link-in-context-regexp)
            (thing-at-point-looking-at denote-org-link-in-context-regexp))
    (match-string-no-properties 1)))
```

This relies on the fact that the regexps for the links always have the id as group number 1 (https://github.com/protesilaos/denote/blob/main/denote.el#L3804).

I have two questions: would code that gets the id of a denote link at point be a useful addition? And is this approach the right way to do so? I saw the recent addition of a `denote-link-id` text property, but it is not added in org-mode so I don’t think it can be used here…

**Comment by protesilaos** [comment]
> From: Alan Schmitt ***@***.***>
> Date: Mon, 29 Jul 2024 00:39:25 -0700

> [... 24 lines elided]

> I have two questions: would code that gets the id of a denote link at
> point be a useful addition?

Yes! This can be useful for a potential Denote+Embark integration (as a
standalone package).

> And is this approach the right way to do so? I saw the recent addition
> of a `denote-link-id` text property, but it is not added in org-mode
> so I don’t think it can be used here…

This is more tricky to tell. We do not add the text property in Org to
avoid potential conflicts. Maybe there is nothing to be concerned about
though and we could lift this restriction. But better be cautious.

I think the 'thing-at-point' we had before was problematic because the
regexp could span two lines and thus cause issues. Perhaps we can check
for the 'denote-faces-link' at point and from it extract the value we
need?

Put the cursor over a 'denote:' link and do 'M-x describe-char'. You
will get a Help buffer that lists many text properties. Then we can use
the 'get-text-property' to extract what we need.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by brabalan** [comment]
These are the text properties I’m seeing on a denote link (that happens to be inside a headline)
```
There are text properties here:
  face                 (denote-faces-link org-level-1)
  font-lock-multiline  t
  fontified            t
  help-echo            "LINK: denote:20240604T153143"
  htmlize-link         (:uri "denote:20240604T153143")
  isearch-open-invisible org-fold-core--isearch-show
  isearch-open-invisible-temporary org-fold-core--isearch-show-temporary
  keymap               [Show]
  mouse-face           highlight
  org-fold--spec-org-link-description-global org-link-description
  org-fold--spec-org-link-global org-link
```

I don’t know the one that is best to use: the `help-echo` or the `htmlize-link`?

**Comment by protesilaos** [comment]
> From: Alan Schmitt ***@***.***>
> Date: Wed, 31 Jul 2024 00:54:12 -0700

> [... 17 lines elided]

> I don’t know the one that is best to use: the `help-echo` or the `htmlize-link`?

How about this?

    (defun denote--get-identifier-at-point (&optional point)
      "Return the Denote identifier at point or optional POINT."
      (when-let ((_ (eq (get-text-property (or point (point)) 'face) 'denote-faces-link))
                 (property (get-text-property (or point (point)) 'help-echo))
                 (_ (string-match denote-id-regexp property)))
        (match-string-no-properties 0 property)))

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
> From: Protesilaos Stavrou ***@***.***>
> Date: Wed, 31 Jul 2024 11:30:59 +0300

> [... 6 lines elided]

>> I don’t know the one that is best to use: the `help-echo` or the `htmlize-link`?
>
> How about this?
>
>     (defun denote--get-identifier-at-point (&optional point)
>       "Return the Denote identifier at point or optional POINT."
>       (when-let ((_ (eq (get-text-property (or point (point)) 'face) 'denote-faces-link))
>                  (property (get-text-property (or point (point)) 'help-echo))
>                  (_ (string-match denote-id-regexp property)))
>         (match-string-no-properties 0 property)))

Minor tweak:

    (defun denote--get-identifier-at-point (&optional point)
      "Return the Denote identifier at point or optional POINT."
      (when-let ((position (or point (point)))
                 (_ (eq (get-text-property position 'face) 'denote-faces-link))
                 (property (get-text-property position 'help-echo))
                 (_ (string-match denote-id-regexp property)))
        (match-string-no-properties 0 property)))

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by brabalan** [comment]
It works great, thanks!

**Comment by protesilaos** [comment]
I just pushed a modified version to `denote.el`. It should also work outside Org files.

**Comment by brabalan** [comment]
I just had a look at the code and it’s exactly what I need. Thanks!
