### ISSUE TITLE
Backlinks buffer links not working with nested dirs

### ISSUE THREAD

**Issue by relict007** [protesilaos/denote#412]
Recently I have observed an issue. 
I have my notes in subfolders (within `denote-directory`), something like this. Excluding IDs for the simplification.
```
fun/roger_zelazny__author.org
fun/courts_of_chaos__novel.org
fun/amber__novel.org
```

Now `fun/courts_of_chaos__novel.org` and `fun/amber__novel.org` have links to `fun/roger_zelazny__author.org`.  I go to `fun/roger_zelazny__author.org` and call `denote-show-backlinks-buffer`, backlinks buffer opens up and shows the backlinks as:

```
fun/courts_of_chaos__novel.org
fun/amber__novel.org

```

However, when I click on any of the links, emacs doesn't open the correct file. It seems it is trying to open the file in `fun/fun` dir,  i.e. clicking on `fun/amber__novel.org` tries to open `fun/fun/amber__novel.org` which is actually not there. 

My env:
Emacs: `GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, cairo version 1.18.0) of 2024-05-26`
Denote: At commit eec6033. I don't use silos.

**Comment by jeanphilippegg** [comment]
This should be fixed in #415 if you want to test it.
