### ISSUE TITLE
`denote-create-note` silently

### ISSUE THREAD

**Issue by kvineet** [protesilaos/denote#413]
Thanks for your excellent package.

I wanted to do org-capture directly to the today's journal file. While this works when the  file already exists, it does not work correctly when today's journal does not exist.

Is there a way for `denote-create-note` to create file silently in background? and not open buffer for it.

Essentially on similar lines of `denote-save-buffers` but to kill buffer after saving.

**Comment by jeanphilippegg** [comment]
The current `denote` command does not have this functionality. Here is how you can get this (interactive) command for now:

```emacs-lisp
(defun denote-create-note-silently ()
  (interactive)
  (when-let ((denote-save-buffers t)
             (new-note (call-interactively #'denote))
             (buffer (find-buffer-visiting new-note)))
    (kill-buffer buffer)))
```

or this may work:

```emacs-lisp
(setq denote-save-buffers t)
(add-hook denote-after-new-note-hook #'kill-buffer)
```

I think having an option to kill a buffer automatically is a good idea. It has already been suggested for renaming commands in #273. It would be good to consider creation commands when/if we get to implementing this feature.

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Sun, 25 Aug 2024 19:35:31 -0700

> [... 19 lines elided]

> I think having an option to kill a buffer automatically is a good
> idea. It has already been suggested for renaming commands in #273. It
> would be good to consider creation commands when/if we get to
> implementing this feature.

Yes, I think this is a nice feature to have.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
Closing now that we have the new user option `denote-kill-buffers` by @jeanphilippegg.
