### ISSUE TITLE
Lisp error: (void-function denote-link-buttonize-buffer)

### ISSUE THREAD

**Issue by gour** [protesilaos/denote#422]
Hello,

I want to resume my work with Emacs/denote and settle on org-mode. Tried to create a new note and debugger launched.

Now, even when I try to launch some other command (e.g. elfeed) I get the following:

```
Debugger entered--Lisp error: (void-function denote-link-buttonize-buffer)
  denote-link-buttonize-buffer()
  run-hooks(find-file-hook)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer elfeed.org> "~/emacs/elfeed/elfeed.org" nil nil "~/emacs/elfeed/elfeed.org" (742034 40))
  #<subr find-file-noselect>("/home/gour/emacs/elfeed/elfeed.org" nil nil nil)
  apply(#<subr find-file-noselect> "/home/gour/emacs/elfeed/elfeed.org" (nil nil))
  editorconfig--advice-find-file-noselect(#<subr find-file-noselect> "/home/gour/emacs/elfeed/elfeed.org" nil nil)
  apply(editorconfig--advice-find-file-noselect #<subr find-file-noselect> ("/home/gour/emacs/elfeed/elfeed.org" nil nil))
  find-file-noselect("/home/gour/emacs/elfeed/elfeed.org" nil nil)
  ido-file-internal(raise-frame)
  ido-find-file()
  funcall-interactively(ido-find-file)
  command-execute(ido-find-file)
````

Any hint?

I'm on Debian 12 (bookworm), but using Emacs from Backports:

GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38,
 cairo version 1.16.0) of 2024-07-22, modified by Debian

Sincerely,
Gour

**Comment by protesilaos** [comment]
> From: Saša Janiška ***@***.***>
> Date: Sun,  1 Sep 2024 11:47:00 -0700

> [... 5 lines elided]

> Now, even when I try to launch some other command (e.g. elfeed) I get the following:
>
> ```
> Debugger entered--Lisp error: (void-function denote-link-buttonize-buffer)

> [... 25 lines elided]

Somewhere in your configuration you have a reference to the obsolete
function 'denote-link-buttonize-buffer'. Please remove it.

If you need to make the links clickable in non-Org files, then add this
to your configuration:

    (add-hook 'text-mode-hook #'denote-fontify-links-mode-maybe)

But my understanding is that you do not need this because you will work
with Org.

-- 
Protesilaos Stavrou
https://protesilaos.com
