### ISSUE TITLE
denote-rename-file and real-auto-save

### ISSUE THREAD

**Issue by juh2** [protesilaos/denote#427]
I am not sure if this is a denote issue or a real-auto-save issue.

When I rename a note with denote-rename-file real-auto-save gets confused and tries to save the old buffer.

Error running timer ‘real-auto-save-buffers’: (error "No buffer named umbenannt.org")

**Comment by protesilaos** [comment]
> From: juh ***@***.***>
> Date: Wed,  4 Sep 2024 06:58:09 -0700
>
> I am not sure if this is a denote issue or a real-auto-save issue.

Can you please tell me more about 'real-auto-save'? What is it doing
exactly and how is it different from the built-in 'auto-save-mode' and
'auto-save-visited-mode'?

> When I rename a note with denote-rename-file real-auto-save gets
> confused and tries to save the old buffer.
>
> Error running timer ‘real-auto-save-buffers’: (error "No buffer named
> umbenannt.org")

We need to know more about your Denote setup and how this
'real-auto-save' works. Based on the error you show here, it seems that
you renamed a file called "umbenannt.org", Denote did this as expected,
and then the 'real-auto-save' timer ran on a file/buffer that did not
exist anymore. Is this the gist of it?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
> From: juh ***@***.***>
> Date: Thu,  5 Sep 2024 09:45:55 -0700
>
> I have no configuration of denote, just installed it. And you're right
> this is exactly what I did.

Okay.

> real-auto-save saves the file itself not in the way the built in
> auto-save-mode works. For some reason it continues to save a buffer
> that was renamed by denote. I filed a bug report to the maintainer of
> real-auto-save.
> https://github.com/ChillarAnand/real-auto-save/issues/59

Fine, let's how it goes.

Do check auto-save-visited-mode though, because it may already do what
you want and is built-in.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by juh2** [comment]
auto-save-visited-mode: It does. Vive le builtins!

**Comment by protesilaos** [comment]
> From: juh ***@***.***>
> Date: Thu,  5 Sep 2024 10:15:01 -0700
>
> auto-save-visited-mode: It does. Vive le builtins!

Nice!

-- 
Protesilaos Stavrou
https://protesilaos.com
