### ISSUE TITLE
denote-retrieve--files-in-xrefs does not return correct file names.

### ISSUE THREAD

**Issue by pRot0ta1p** [protesilaos/denote#43]
Hi, I was testing out denote and I found the backlink does not work, it always says "No links to the current note",
it appears to work in your demo video so I tried to debug the code, long story short I found this piece of code:
https://github.com/protesilaos/denote/blob/0683a1937c78068e79463df51acf936da338d301/denote-retrieve.el#L114-L115
seems to return wrong path of notes.

To test it, I create 2 notes in a empty directory `~/test` by invoke `M-x denote`, `note2.org` have a denote link to `note1.org`, 
then I `M-x eval-expression` the following codes in the `note1.org` buffer that should have a backlink to it:

```emacs-lisp
(delete (denote--file-name-relative-to-denote-directory (buffer-file-name))
(denote-retrieve--files-in-xrefs
 (denote-retrieve--xrefs (denote-retrieve--filename-identifier (buffer-file-name)))))
```

It returns something like `("test/20220710T200942--note1__random.org" "test/20220710T201012--note2__random.org")`, 
when function `denote-retrieve--files-in-output` receive those as arguments, it returns nil, so no backlinks...

I run the same test with emacs28.1 and emacs29 from a recent commit after `emacs -Q`, both shows the same results.

**Comment by protesilaos** [comment]
Hello @pRot0ta1p,

I cannot reproduce your issue.  I placed this in the scratch buffer of
`emacs -Q` (using Emacs 29 on GNU/Linux):

```elisp
(add-to-list 'load-path "/home/prot/Git/Projects/denote/")
(progn
  (require 'denote)
  (require 'denote-retrieve)
  (require 'denote-faces)
  (require 'denote-link)

  (setq denote-directory "~/testing-denote"))
```

I then did `M-x denote` and followed the prompts for title and keywords
to create a new file.  I saved it.

Then I did `M-x denote` again and created a second file.

From the second file, I did `M-x denote-link` and in the minibuffer
prompt I selected the first file.

I then switched to the first file and did `M-x denote-link-backlinks`.
It produced a backlinks' buffer, with a link to the second file.
Screenshot:

![Screenshot from 2022-07-10 17-22-42](https://user-images.githubusercontent.com/12828033/178149292-7bfc5f66-f48c-48ae-b638-5593639a6793.png)


While in the buffer of the first file, I evaluated the code you
provided:

```elisp
(delete (denote--file-name-relative-to-denote-directory (buffer-file-name))
        (denote-retrieve--files-in-xrefs
         (denote-retrieve--xrefs (denote-retrieve--filename-identifier (buffer-file-name)))))
```

It returned the path of the second file, as expected.  See the echo area
in the second screenshot.

![Screenshot from 2022-07-10 17-27-24](https://user-images.githubusercontent.com/12828033/178149283-f3ade2c3-6158-45b3-bf4f-15f03e404b57.png)

What is your `M-x emacs-version`?

**Comment by pRot0ta1p** [comment]
`GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-07-09`, run the same test as you do and till have the same problem...

Is it possible because of xref ? eval ` denote-retrieve--xrefs (denote-retrieve--filename-identifier (buffer-file-name)))`
shows
```
(("test/20220710T200942--note1__random.org" #s(xref-match-item #("#+identifier: 20220710T200942" 0 14 ... 14 29 ...) #s(xref-file-location "/home/me/test/20220710T200942--note1__random.org" 4 14) 15)) ("test/20220710T201012--note2__random.org" #s(xref-match-item #("[[denote:20220710T200942][note1]]" 9 24 ...) #s(xref-file-location "/home/me/test/20220710T201012--note2__random.org" 9 9) 15))
```

**Comment by protesilaos** [comment]
Something is amiss.  I will review things and report back to you.

**Comment by protesilaos** [comment]
What does the evaluation of this function return when called from inside the note that should have backlinks?

```elisp
(denote-retrieve--files-in-xrefs (denote-retrieve--xrefs (denote-retrieve--filename-identifier (buffer-file-name))))
```

**Comment by pRot0ta1p** [comment]
Setup: 

- note2 have a link to note1 , note1 have no link at all.
- `emacs -Q` and minimal config
```elisp
(add-to-list 'load-path "~/repo/denote/")
(progn
  (require 'denote)
  (require 'denote-retrieve)
  (require 'denote-faces)
  (require 'denote-link)
  (setq denote-directory "~/test/"))
```

Inside the note that should have backlinks (note1):
```
("test/20220710T200942--note1__random.org" "test/20220710T201012--note2__random.org")
```
Inside the note that have a link to the other note (note2):
````
("test/20220710T201012--note2__random.org")
````

**Comment by jeanphilippegg** [comment]
May I ask which version/commit of Denote you are using?

@protesilaos , the issue is probably in `denote--only-note-p`, but I cannot reproduce it with my version.

**Comment by jeanphilippegg** [comment]
@pRot0ta1p , can you evaluate

```
(denote--only-note-p "test/20220710T201012--note2__random.org")
```

**Comment by protesilaos** [comment]
> @protesilaos , the issue is probably in `denote--only-note-p`, but I cannot reproduce it with my
version.

Yes, that would be my next guess.

**Comment by pRot0ta1p** [comment]
> ```
> (denote--only-note-p "test/20220710T201012--note2__random.org")
> ```
Return value is nil.

But this reminds me,
> This might fix issue https://github.com/protesilaos/denote/issues/43 . This user seems to have a project in a parent directory, hence his errors.

Because I use the feature of git that you can set the work tree somewhere else to set the home directory as worktree , so after I delete the dotfiles git repo, backlinks works fine...

The latest version seems resolved this bug when the note directory have a git repo as parent, but with one catch,  `denote-directory` need to be a absolute path, if `~` is not expanded, I still get not backlink.

**Comment by protesilaos** [comment]
Thank you folks for figuring this out while I was asleep!

**Comment by pRot0ta1p** [comment]
No problem, thank you guys for solving this bug 😃
