### ISSUE TITLE
Prettification of links to Denote attachments

### ISSUE THREAD

**Issue by pprevos** [protesilaos/denote#434]
The `denote-retrieve-title-or-filename` function returns the raw title string for Denote attachments: `(eq (denote-filename-is-note-p file) nil)`

So instead of the link title being: `this-is-a-denote-attachment`, it should be something like: `This Is a Denote Attachment`.

The [titlecase package](https://github.com/duckwork/titlecase.el) can help, so I created this helper function:

```elisp
(defun ews-denote-file-title-to-title-case (title)
  "Convert Denote filename title string to title case."
  (let ((title-deslugged (replace-regexp-in-string "-" " " title)))
    (titlecase--string title-deslugged titlecase-style)))
```

How can we elegantly add such a function to Denote. Could we advise `denote-retrieve-filename-title`?

**Comment by jeanphilippegg** [comment]
I am not sure I understand the use case. In your title, you mention links. Maybe customizing `denote-link-description-function` is what you are looking for? This user option allows you to specify how your link descriptions are created. You can include some desluggification in there.

**Comment by pprevos** [comment]
Thanks. I was unaware of this variable. I have created a bespoke function that meets my needs.

**Comment by jeanphilippegg** [comment]
You're welcome!
