### ISSUE TITLE
function to get the path of a journal file

### ISSUE THREAD

**Issue by brabalan** [protesilaos/denote#442]
I wrote a small function to refile a task to a journal note. To do that, I needed to obtain the path to the note, create it if necessary, or choose one if there are several. Luckily for me, `denote-journal-extras-new-or-existing-entry` does all that, so here is what I wrote:
```emacs-lisp
(defun get-today-journal-file (&optional date)
  (save-window-excursion
    (denote-journal-extras-new-or-existing-entry date)
    (buffer-file-name)))
```

Would it be better to extract the logic that finds the note from `denote-journal-extras-new-or-existing-entry` and `denote-journal-extras-link-or-create-entry` (which is the same code duplicated) to a function `denote-journal-extra-path-to-new-or-existing-entry`, which I could directly use, and refactor `denote-journal-extras-new-or-existing-entry` and `denote-journal-extras-link-or-create-entry` to use it?

This function would look like this:
```emacs-lisp
(defun denote-journal-extra-path-to-new-or-existing-entry (&optional date)
  (let* ((internal-date (denote-parse-date date))
         (files (denote-journal-extras--entry-today internal-date)))
    (cond
     ((length> files 1)
      (completing-read "Select journal entry: " files nil :require-match))
     (files
      (car files))
     (t nil))))

```

**Comment by protesilaos** [comment]
> From: Alan Schmitt ***@***.***>
> Date: Thu, 19 Sep 2024 09:42:31 -0700

> [... 9 lines elided]

> Would it be better to extract the logic that finds the note from
> `denote-journal-extras-new-or-existing-entry` and
> `denote-journal-extras-link-or-create-entry` (which is the same code
> duplicated) to a function
> `denote-journal-extra-path-to-new-or-existing-entry`, which I could
> directly use, and refactor
> `denote-journal-extras-new-or-existing-entry` and
> `denote-journal-extras-link-or-create-entry` to use it?

> [... 14 lines elided]

Yes, I think that makes sense. Do you want to prepare a pull request? If
I recall correctly, you have already assigned copyright to the FSF, so
we are good.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by brabalan** [comment]
Yes, I have assigned copyright to the FSF.
