### ISSUE TITLE
denote-dired-mode ineffective with doom-emacs

### ISSUE THREAD

**Issue by LukasCBossert** [protesilaos/denote#446]
I noticed in my Doom-Emacs that regardless of the theme I have no special highlighting of the filename-structure in dired. Loading with `emacs -Q` etc. I see the filenames colored properly.

Anyone can reproduce this?

**Comment by protesilaos** [comment]
> From: "Lukas C. Bossert" ***@***.***>
> Date: Sat, 21 Sep 2024 02:41:57 -0700
>
> I noticed in my Doom-Emacs that regardless of the theme I have no
> special highlighting of the filename-structure in dired. Loading with
> `emacs -Q` etc. I see the filenames colored properly.
>
> Anyone can reproduce this?

I guess Doom uses diredfl-mode. We cannot do anything about it because
of how it is implemented. Try to disable it and see how it goes.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by LukasCBossert** [comment]
yes, that works. I will build a workaround to disable `diredfl` first. Thanks for pointing to `diredfl`.

**Comment by LukasCBossert** [comment]
For the sake of completenes in case someone finds this issue having the same problem.

In my `packages.el` I have added
```
(package! diredfl
  :disable t)
  ```
