### ISSUE TITLE
File already exists after running 'denote-journal-extras-new-entry'

### ISSUE THREAD

**Issue by hyperfocus1337** [protesilaos/denote#454]
First of all, thanks for all the efforts in putting this package together! I could really relate to the reasoning behind the workings of package, and I wanted my notes in markdown thus I migrated away from org roam.

Unfortunately though, I am dealing with a critical error and I could use some guidance as to how I should go about troubleshooting it.

Whenever I execute `denote-journal-extras-new-entry`, I trigger the following error. It also happens intermittently when executing `denote` or `denote-open-or-create`. But I can successfully trigger the error every time I run `denote-journal-extras-new-entry`.
```
File notes/journal/20241008T154731--tuesday-8-october-2024-1547__journal.md added to project /Users/user/Library/CloudStorage/Dropbox/Notebooks/notebook/ cache.
Wrote /Users/user/Library/CloudStorage/Dropbox/Notebooks/notebook/notes/journal/20241008T154731--tuesday-8-october-2024-1547__journal.md
"notes/journal/20241008T154731--tuesday-8-october-2024-1547__journal.md" 1L, 17C written
denote--prepare-note: A file named ‘/Users/user/Library/CloudStorage/Dropbox/Notebooks/notebook/notes/journal/20241008T154731--tuesday-8-october-2024-1547__journal.md’ already exists
```

Afterwards, I'm left with the file that only includes the markdown heading (`#`) symbol, no frontmatter.

This is how I installed Denote using Doom Emacs.

In `packages.el` (I'm using the latest commit starting with`855c06e`):
```
(package! denote :recipe (:host github :repo "protesilaos/denote"))
```

In `config.el`:
```
(use-package! denote
  :custom
  (denote-directory (expand-file-name "~/Library/CloudStorage/Dropbox/Notebooks/notebook/notes"))
  (denote-known-keywords '("emacs" "doom" "config" "denote"))
  (denote-infer-keywords nil) ; Infer keywords from note's content
  (denote-file-type 'markdown-yaml) ; Set file type for notes ('markdown-yaml' or 'org')
  (denote-save-buffers t)
  :hook
  (dired-mode . denote-dired-mode))
```

Here's my full Emacs [config.org](https://docs.hyperfocus1337.com/doom-emacs.html), as well as my [init.el](https://gist.github.com/hyperfocus1337/c21502a1e61a45566e7f8f5656f81de4), to check if something might be interfering from my personal configuration.

Is there anything else that I should provide to help debugging?

Also noticed you offer [coaching](https://protesilaos.com/coach/), we could take that route too if it would be useful to check my config through a screen sharing session, and discuss other note taking workflow improvements in the process. Would be happy to collaborate on this.

**Comment by protesilaos** [comment]
> From: hyperfocus1337 ***@***.***>
> Date: Tue,  8 Oct 2024 07:20:02 -0700
>
> First of all, thanks for all the efforts in putting this package
> together!

You are welcome!

> I could really relate to the reasoning behind the workings
> of package, and I wanted my notes in markdown thus I migrated away
> from org roam.
>
> Unfortunately though, I am dealing with a critical error and I could
> use some guidance as to how I should go about troubleshooting it.
>
> Whenever I execute `denote-journal-extras-new-entry`, I trigger the
> following error. It also happens intermittently when executing
> `denote` or `denote-open-or-create`. But I can successfully trigger
> the error every time I run `denote-journal-extras-new-entry`.

The intermittent error is concerning. I am not sure what it could be. We
will need to dig deeper.

> ```
> File notes/journal/20241008T154731--tuesday-8-october-2024-1547__journal.md added to project /Users/user/Library/CloudStorage/Dropbox/Notebooks/notebook/ cache.
> Wrote /Users/user/Library/CloudStorage/Dropbox/Notebooks/notebook/notes/journal/20241008T154731--tuesday-8-october-2024-1547__journal.md
> "notes/journal/20241008T154731--tuesday-8-october-2024-1547__journal.md" 1L, 17C written
> denote--prepare-note: A file named ‘/Users/user/Library/CloudStorage/Dropbox/Notebooks/notebook/notes/journal/20241008T154731--tuesday-8-october-2024-1547__journal.md’ already exists
> ```

Do you know what is that first line about the cache? We do not handle
that. Could it be that somehow the file path is generated outside of
Denote and then when Denote gets to write to the file it finds that it
is already there? Seems improbable, though I have no better guess right now.

> Afterwards, I'm left with the file that includes empty frontmatter (just a `#` symbol).
>
> This is how I installed Denote using Doom Emacs.
>
> In `packages.el` (I'm using the latest commit starting with`855c06e`):
> ```
> (package! denote :recipe (:host github :repo "protesilaos/denote"))
> ```
>
> In `config.el`:
> ```
> (use-package! denote
>   :custom
>   (denote-directory (expand-file-name "~/Library/CloudStorage/Dropbox/Notebooks/notebook/notes"))
>   (denote-known-keywords '("emacs" "doom" "config" "denote"))
>   (denote-infer-keywords nil) ; Infer keywords from note's content
>   (denote-file-type 'markdown-yaml) ; Set file type for notes ('markdown-yaml' or 'org')
>   (denote-save-buffers t)
>   :hook
>   (dired-mode . denote-dired-mode))
> ```

This configuration seems fine. Can you try to reproduce the error by
running 'emacs -Q' on the command line? This will open an Emacs frame
that has none of your and Doom's configurations. In that frame, put the
following in the scratch buffer, change the path to where denote.el is
on your system, evaluate the whole code, and then try to see if the
error happens again. This will help us understand where the source of
the problem is.

The code:

    (require 'denote "path/to/denote.el")
    (require 'denote-journal-extras "path/to/denote-journal-extras.el")

    (setq denote-directory (expand-file-name "~/Library/CloudStorage/Dropbox/Notebooks/notebook/notes"))
    (setq denote-known-keywords '("emacs" "doom" "config" "denote"))
    (setq denote-infer-keywords nil) ; Infer keywords from note's content
    (setq denote-file-type 'markdown-yaml) ; Set file type for notes ('markdown-yaml' or 'org')
    (setq denote-save-buffers t)

    (add-hook 'dired-mode-hook 'denote-dired-mode)

> Here's my full Emacs [config.org](https://docs.hyperfocus1337.com/doom-emacs.html), as well as my [init.el](https://gist.github.com/hyperfocus1337/c21502a1e61a45566e7f8f5656f81de4), to check if something might be interfering from my personal configuration.
>
> Is there anything else that I should provide to help debugging?

Let's first check what we get from 'emacs -Q' before delving into the
Doom bits. There might be a bug in Denote, which we will find this way.
Otherwise, it will be something in Doom or your configuration.

> Also noticed you offer [coaching](https://protesilaos.com/coach/), we
> could take that route too if it's very time consuming to thoroughly
> check my config for any conflicting config or packages.

Sure, though this is independent of the maintenance work I do here: this
is a community project and is available for free (and in freedom).

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by hyperfocus1337** [comment]
Thanks for the feedback!

I've tested your instructions, it works fine. I cannot reproduce it using `Emacs -Q`.
<img width="798" alt="image" src="https://github.com/user-attachments/assets/30a4f9c3-d052-41e7-9942-af85773188d0">

As expected, the problem exists within my Doom environment.

Can confirm, the intermittent error is also still happening using `denote-open-or-create`. To alleviate the issue somewhat, I discovered I can use `denote-add-front-matter` to add the missing front matter to the file.

To illustrate, I've made a video of it [here](https://capture.dropbox.com/fcy8PrvwjB1gpXzo).

> Do you know what is that first line about the cache?

I'm not sure, it might be the `projectile` cache. I will have to dig deeper.

> Sure, though this is independent of the maintenance work I do here: this
is a community project and is available for free (and in freedom).

This seems to be an issue related to my personal config. However, I feel many of my [customizations](https://docs.hyperfocus1337.com/doom-emacs.html) on top of Doom Emacs are pretty basic (and most additions are likely unrelated to what I'm experiencing). More users might be impacted by this.

If you are willing to help debug this case, I would be happy to book coaching to further dive into any potential root causes through a screen sharing session (if that is most helpful, whatever you prefer). I also have another customization I would like to discuss (support for relative links that are not appended by `denote:`). I will email you, so you have my contact details.

**Comment by hyperfocus1337** [comment]
Besides researching which potential packages could be conflicting with denote, I will try to reproduce it by installing stock Doom.

It would allow me to see whether the problem lies within Doom, or my modifications on top of Doom.

Will let you know once it get to it.

**Comment by hyperfocus1337** [comment]
Couldn't reproduce it in stock Doom. So I need to look deeper into my (enabled) packages (potentially also as part of Doom, or my configs on top).

**Comment by protesilaos** [comment]
> Couldn't reproduce it in stock Doom. So I need to look deeper into my (enabled) packages (potentially also as part of Doom, or my configs on top).

Fine. Since we saw the cache-related message earlier, I would start with that.

**Comment by hyperfocus1337** [comment]
Strangely enough, for now, it seems I can't reliably reproduce the error with `denote-journal-extras-new-entry` (whereas, previously I could). Now, after creating a journal entry, the cache write does not show in `*Messages*`, so it might very well be related to that.

I still don't expect it to be permanently fixed. If it is, it might have been magically fixed due to me installing stock Doom, and afterwards putting my old config back in place and simply having invoked `doom sync`.

Let's leave the issue open for now, in case the intermittent error shows again. I've realized it might now take some time, as I 'lost' the approach to reliably reproduce the error.

**Comment by hyperfocus1337** [comment]
I didn't notice this issue in a while, I am now confident `(setq projectile-auto-update-cache nil)` fixed the issue. However, this requires me to manually update the Projectile cache from time to time using `(setq projectile-invalidate-cache)`. Closing this issue, as it's not related to Denote.

**Comment by protesilaos** [comment]
> From: hyperfocus1337 ***@***.***>
> Date: Tue, 15 Oct 2024 06:23:41 -0700
>
> I didn't notice this issue in a while, I am now confident `(setq
> projectile-auto-update-cache nil)` fixed the issue. However, this
> requires me to manually update the Projectile cache from time to time
> using `(setq projectile-invalidate-cache)`. Closing this issue, as
> it's not related to Denote.

Good to know!

I will keep this in mind in case some related issue pops up. I am
curious to learn how/why projectile would make Denote fail in this case.
Perhaps it creates a placeholder file as part of caching it and so then
'file-exists-p' returns non-nil even though it shouldn't? Could it be
that we need a more robust check than 'file-exists-p'?

-- 
Protesilaos Stavrou
https://protesilaos.com
