### ISSUE TITLE
Use colon ":" in title OR use dashes "-" in Signature notes

### ISSUE THREAD

**Issue by x61** [protesilaos/denote#459]
Hello All:

I would like to know if it is possible to use the ":" in title name. I am looking for something like this: 

``Topic Name: this is one topic``

Looking through the doc, `signature` note might work, but I would like to use a dash "-" as a replacement for spaces between topic names. That is, I am ok if the output shows: 
``==topic-name__this-is-one-topic`` instead of ``==topic=name__this-is-one-topic``.

**Comment by jeanphilippegg** [comment]
The way file name components appear in the file name can be customized using
`denote-file-name-slug-functions`. You can choose to have spaces replaced with
hyphens if you want. Check the manual for "sluggification". There are examples
that you can adapt.

**Comment by protesilaos** [comment]
@x61 Did you have the chance to try what @jeanphilippegg suggested? This is indeed the way to go for all such specific customisations.

I think we can safely close the issue now. Let me know if there is something I missed.

**Comment by x61** [comment]
Hello @jeanphilippegg, thanks for the suggestion. I will give that a try. @protesilaos, it is safe to close it. Thanks again for the support.
