### ISSUE TITLE
:excluded-dirs-regexp in dynamic blocks is not functional

### ISSUE THREAD

**Issue by pprevos** [protesilaos/denote#463]
The `denote-org-extras-dblock--files` function does not seem to use the `:excluded-dirs-regexp` parameter in certain dynamic blocks. 

The function calls in the `org-dblock-write:denote-*links` functions don't pass this parameter on.

When I use something like this i get the correct list, but I am sure there is a more elegant solution.

``` lisp
(cl-remove-if (lambda (str)
                (string-match-p (concat denote-excluded-directories-regexp "/") str))
              (denote-directory-files files-matching-regexp :omit-current))
```

**Comment by protesilaos** [comment]
> From: Peter Prevos ***@***.***>
> Date: Fri, 18 Oct 2024 03:41:53 -0700
>
> The `denote-org-extras-dblock--files` function does not seem to use
> the `:excluded-dirs-regexp` parameter in certain dynamic blocks.
>
> The function calls in the `org-dblock-write:denote-*links` functions
> don't pass this parameter on.

Indeed! This is because the 'denote-excluded-directories-regexp' is a
user option rather than some internal variable. When it is set, it is
ultimately affecting the 'denote--directory-all-files-recursively'
function which, in turn, affects the 'denote-directory-files' function.

Something like 'denote-org-extras-dblock--files' does not do its own
search for files but delegates that task to a function that ultimately
resolves to 'denote-directory-files'.

> When I use something like this i get the correct list, but I am sure
> there is a more elegant solution.
>
> ``` lisp
> (cl-remove-if (lambda (str)
>                 (string-match-p (concat denote-excluded-directories-regexp "/") str))
>               (denote-directory-files files-matching-regexp :omit-current))
> ```

Is this some custom code you are writing? Maybe you can use the same
approach we have here, of having a 'let*' that first sets the value of
'denote-excluded-directories-regexp' and then does the search?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by pprevos** [comment]
> the 'denote-excluded-directories-regexp' is a
> user option rather than some internal variable

The various dynamic blocks have a `:excluded-dirs-regexp nil` default parameter, but the input is ignored.

Use case, two files:
- `20241021T062749--denote-test-1__xyz.org`
- `test/20241021T062827--denote-test-2__xyz.org`

Expected behavior:

```
#+BEGIN: denote-links :regexp "xyz" :excluded-dirs-regexp test
- [[denote:20241021T062749][Denote Test 1]]
#+END:
```

Actual behaviour:

#+BEGIN: denote-links :regexp "xyz" :excluded-dirs-regexp test
- [[denote:20241021T062827][Denote Test 2]]
- [[denote:20241021T062749][Denote Test 1]]
#+END:

**Comment by protesilaos** [comment]
Can you try to quote the regexp you are passing it?

```
#+BEGIN: denote-links :regexp "xyz" :excluded-dirs-regexp "test"
```

This works on my end. It does not work if the quotes are missing though (which may be a bug, but I am not sure how Org handles those ordinarily).

**Comment by protesilaos** [comment]
> From: Peter Prevos ***@***.***>
> Date: Mon, 21 Oct 2024 00:30:54 -0700
>
> Yes that did it. I am an idiot :)
>
> Thanks for the response.

No worries! Maybe we can handle this case internally? But I am not sure
this is a good idea and would prefer to know how Org handles such cases
more generally.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by pprevos** [comment]
There is no issue with the code, it was human-error on my side.

**Comment by protesilaos** [comment]
> From: Peter Prevos ***@***.***>
> Date: Mon, 21 Oct 2024 00:41:56 -0700
>
> There is no issue with the code, it was human-error on my side.

Fine, let's leave it as-is.

-- 
Protesilaos Stavrou
https://protesilaos.com
