### ISSUE TITLE
denote--creation-prepare-note-data: Wrong type argument: stringp, nil upon calling denote

### ISSUE THREAD

**Issue by hyperfocus1337** [protesilaos/denote#465]
Happened between commit `ed0eb4a` and latest commit `7dc184a`.

Fixed the problem by reverting back to `ed0eb4a` by running:
- `cd ~/.emacs.d/.local/straight/repos/denote`
- `git checkout ed0eb4a` 
- `rm -rf ../../build-29.1/denote`
- `doom sync`
- Restarting Doom

Needs to be investigated which exact commit caused it.

**Comment by hyperfocus1337** [comment]
From my testing it seems to have been caused by: https://github.com/protesilaos/denote/commit/4db0214d301c3893813b8ed55166014252895819 (and up)

I didn't experience the issue with: https://github.com/protesilaos/denote/commit/f764fac9331f393f72ac3858a7b1a49ecc7f15b3

**Comment by jeanphilippegg** [comment]
My fault, sorry! I made a pull request. It should be fixed soon. In the meantime, you can revert commit 4db0214.

**Comment by protesilaos** [comment]
> From: Jean-Philippe Gagné Guay ***@***.***>
> Date: Mon, 21 Oct 2024 17:09:07 -0700
>
> My fault, sorry! I made a pull request. It should be fixed soon. In the meantime, you can revert commit 4db0214.

Thank you!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by hyperfocus1337** [comment]
I upgraded Denote today and I can confirm the problem is resolved, closing.
