### ISSUE TITLE
Convert plain file to Denote

### ISSUE THREAD

**Issue by jeanphilippegg** [protesilaos/denote#48]
Based on the `denote-dired-rename-file` function, I came up with this function to convert an existing non-Denote file into a Denote one.

The idea is not to try to convert org-roam files to Denote, though it can probably be useful for that use case. Check the docstring of the function to know the details.

I am sharing it here because I don't know if it should be integrated to the code or where to integrate it.

What do you think?

```elisp
(defun denote-dired-convert-file-to-denote (file title keywords)
  "Convert a file to Denote format.

This function adds a front matter unconditionally at the start of
the file. It does not check if one is already present. If a front
matter is already present, you will end up with two. Consider
using `denote-dired-rename-file' in that case.

It prompts for a FILE, a TITLE and KEYWORDS.

The identifier is retrieved from the filename if there is one,
else the last modification time is used.

The default title is retrieved from a line starting with
\"#+title:\" if such a line exists (and depending on the file
type). Else, the file name is used."
  (interactive
   (let ((file (denote-dired--rename-file-is-regular (denote-dired--rename-dired-file-or-prompt))))
     (list
      file
      (denote--title-prompt (or (denote-retrieve--value-title file)
                                (file-name-sans-extension (file-name-nondirectory file))))
      (denote--keywords-prompt))))
  (let* ((dir (file-name-directory file))
         (old-name (file-name-nondirectory file))
         (id (denote-dired--file-name-id file))
         (extension (file-name-extension file t))
         (new-name (denote--format-file
                    dir
                    (denote-dired--file-name-id file)
                    keywords
                    (denote--sluggify title)
                    extension))
         (max-mini-window-height 0.33)) ; allow minibuffer to be resized
    (unless (string= old-name (file-name-nondirectory new-name))
      (when (y-or-n-p
             (format "Rename %s to %s?"
                     (propertize old-name 'face 'error)
                     (propertize (file-name-nondirectory new-name) 'face 'success)))
        (rename-file old-name new-name nil)
        (denote-dired--rename-buffer old-name new-name)
        (denote-dired-update-dired-buffers)))
    (when-let* ((filetype (denote-dired--filetype-heuristics file))
                (date (denote--date (date-to-time id)))
                (new-front-matter (denote--file-meta-header title date keywords id filetype)))
      (with-current-buffer (find-file-noselect new-name)
        (goto-char (point-min))
        (insert new-front-matter)))))
```

**Comment by jeanphilippegg** [comment]
I have read section 4 of the manual about renaming file. The function `denote-dired-rename-file` and the hooks for `denote-dired-post-rename-functions` are explained, but I do not see why I would add something to `denote-dired-post-rename-functions`, personally.

I have difficulty merging my function `denote-dired-convert-to-denote` with `denote-dired-rename-file` because of the hooks and other differences.

Since I do not understand the hooks, what I would do would be to just remove them. I would determine the behavior we want for `denote-dired-rename-file` and program that with no user hooks. For example, the spec of `denote-dired-rename-file` could be:

- Prompt for title and keywords. (Subdir, date and extension are irrelevant here. They should be inferred.)
- Rename the file.
- Rewrite the front matter.

And since `denote-dired-rename-file` already does a lot, I think I would create a distinct function for conversion purpose. The purpose of a function like `denote-dired-rename-file` is really just to change the title and add/remove keywords. Overloading it with code that does file conversion might make it hard to maintain and its docstring would have to explain its dual purpose, which could be confusing to users.

What do you think?

**Comment by jeanphilippegg** [comment]
Since `denote-dired-rename-file` already does a lot, I think I would create a distinct function for conversion purpose. The purpose of a function like `denote-dired-rename-file` is really just to change the title and add/remove keywords. Overloading it with code that does file conversion might make it hard to maintain and its docstring would have to explain its dual purpose, which could be confusing to users.

Does that make sense?

---

Also, I have read section 4 of the manual about renaming files. The function `denote-dired-rename-file` and the hooks for `denote-dired-post-rename-functions` are explained, but I do not see why I would add something to `denote-dired-post-rename-functions`, personally.

I would have difficulty merging my function `denote-dired-convert-to-denote` with `denote-dired-rename-file` if I wanted because of the hooks and other differences.

What would be a use case for `denote-dired-post-rename-functions`? Maybe there is something to be simplified here?

**Comment by jeanphilippegg** [comment]
Since `denote-dired-rename-file` already does a lot, I think I would create a distinct function for conversion purpose. The purpose of a function like `denote-dired-rename-file` is really just to change the title and add/remove keywords. Overloading it with code that does file conversion might make it hard to maintain and its docstring would have to explain its dual purpose, which could be confusing to users.

Does that make sense?

---

Also, I have read section 4 of the manual about renaming files. The function `denote-dired-rename-file` and the hooks for `denote-dired-post-rename-functions` are explained, but I do not see why I would add something to `denote-dired-post-rename-functions`, personally.

I would have difficulty merging my function `denote-dired-convert-to-denote` with `denote-dired-rename-file` because of the hooks and other differences.

What would be a use case for `denote-dired-post-rename-functions`? Maybe there is something to be simplified?

**Comment by protesilaos** [comment]
> Does that make sense?

Yes.  It makes perfect sense.  Let's keep it simple.

> What would be a use case for `denote-dired-post-rename-functions`? Maybe there is something to be simplified?

Maybe we can simplify things, though I have no concrete idea.  I thought it was better to have it this way as the user may want to add/remove functionality here.  Though I admit it is not an easy user option.

**Comment by jeanphilippegg** [comment]
> Yes. It makes perfect sense. Let's keep it simple.

Ok. I will make a pull request.

> Maybe we can simplify things, though I have no concrete idea. I thought it was better to have it this way as the user may want to add/remove functionality here. Though I admit it is not an easy user option.

Do we want to modify something for now? The only idea I would have is to remove the user option.

**Comment by protesilaos** [comment]
> The only idea I would have is to remove the user option.

I suggest we keep it at least until we have a better solution.

**Comment by jeanphilippegg** [comment]
> I suggest we keep it at least until we have a better solution.

That's good!
