### ISSUE TITLE
[Feature Request] Org Dblocks `:not-regexp` option

### ISSUE THREAD

**Issue by swflint** [protesilaos/denote#481]
Would it be possible to include a `:not-regexp` option in org dblocks?  With a semantic of something like:

 - If both `:regexp` and `:not-regexp` are provided, notes which pass the following test `(and (string-match-p regexp filename) (not (string-match-p not-regexp filename)))`
 - If only `:regexp`, continue as normal
 - If only `:not-regexp`, show links to notes which do not match `:not-regexp` (i.e., `(not (string-match-p not-regexp filename))`)

This is inspired by https://mastodon.online/@johnrakestraw/113495071981398889

**Comment by swflint** [comment]
Closing, in favor of existing #421.

**Comment by protesilaos** [comment]
> From: "Samuel W. Flint" ***@***.***>
> Date: Sat, 16 Nov 2024 18:03:55 -0800
>
> Closing, in favor of existing #421.

Fine, let us consider this holistically.

-- 
Protesilaos Stavrou
https://protesilaos.com
