### ISSUE TITLE
When prompting for an identifier, hitting enter with no input should default to the file mod time

### ISSUE THREAD

**Issue by axgfn** [protesilaos/denote#489]
Using denote to rename files in dired, sometimes I want to manually set the date to use in the identifier. However, most of the time I don't, so I expect to be able to just hit enter at the date prompt with no input and have denote choose the identifier for me.

Instead, denote always defaults to the current day rather than the file's modification time.

**Comment by jeanphilippegg** [comment]
This should already be resolved in the latest code.

Using a previous revision of the code, I have reproduced the issue using `denote-dired-rename-files` on a file "test.org". It used current-time instead of modification time.

Can you try the latest code and confirm that it works?

**Comment by axgfn** [comment]
OK I tested this again with the latest code and confirmed that it works like I want when using denote's simple minibuffer prompt. However, it still uses the current day when `denote-date-prompt-use-org-read-date` is true.

Looking at the docs for `org-read-date` I think it should be fairly simple to fix that too. In fact my original issue title was specifically about `org-read-date` until I tested out the simple prompt after opening the issue.

**Comment by jeanphilippegg** [comment]
This is a "limitation" of `org-read-date`. You cannot escape it without a date and tell it that you meant "no date" (if I read the doc correctly).

> Looking at the docs for `org-read-date` I think it should be fairly simple to fix that too.

What did you find? One idea would be to assume "no date" when the input date is close to current-time with a file that does not yet have an identifier, but that may also be confusing to users. What if you do want the current-time?

Most users would probably not want to have a date prompt when renaming files. It is only used to change the date/id or to set it to a specific value. In this case (no date prompt), the modification time is used.

Do you sometimes want to set the date to a specific value and other times to the modification time?

**Comment by axgfn** [comment]
There's no way for `org-read-date` to return "no date," but you can pass a default date and default input so that the picker starts with whatever time you want already selected. That's enough to allow me to just hit enter to move to the next prompt.

> Do you sometimes want to set the date to a specific value and other times to the modification time?

Yes, this is for when I'm importing files into a denote silo. Most of the time the modification time is reasonable but other times it's not.

**Comment by protesilaos** [comment]
I am working on it now. Will post back soon.

**Comment by protesilaos** [comment]
I just made the change. Please give it a try. If there are any bugs or missing features, we will deal with them. No worries!

**Comment by axgfn** [comment]
Just tried it out and it seems to work great, thanks!

**Comment by protesilaos** [comment]
> From: Alex Griffin ***@***.***>
> Date: Tue, 10 Dec 2024 18:40:38 -0800
>
> Just tried it out and it seems to work great, thanks!

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
