### ISSUE TITLE
`denote-org-extras--parse-rx` fails when nil is passed

### ISSUE THREAD

**Issue by swflint** [protesilaos/denote#490]
This seems like a relatively simple fix, and I believe would have happened with the former macroexpand & rx approach as well.

**Comment by protesilaos** [comment]
Thank you! I just made a change. We needed it, anyway.

**Comment by swflint** [comment]
For `denote-directory-files` et al. to behave appropriately, I think nil regexps need to remain nil throughout (empty string regexp matches everything, including the empty string).

**Comment by protesilaos** [comment]
Oh, right! I just pushed the change.

**Comment by swflint** [comment]
Thanks!
