### ISSUE TITLE
Regression with two tests about the date in the front matter

### ISSUE THREAD

**Issue by protesilaos** [protesilaos/denote#494]
Hello @jeanphilippegg! I notice our tests `denote-test--denote--format-front-matter` and `denote-test--denote-format-file-name` are failing because the date we now produce is not what they expect. Note that those tests are not perfect because they try to work without the timezone component.

Looking at what we are doing with the front matter, I think it is fine, so probably we need to rewrite those tests. I thought about splitting the front matter into a list and then testing each string for an expected value. We use `equal` (or `string=`) for all strings and `string-match-p` for the date.

What do you think?

**Comment by jeanphilippegg** [comment]
Fixed and explained in pull request #496!
