### ISSUE TITLE
denote-link-dired-marked-notes broken?

### ISSUE THREAD

**Issue by oliverepper** [protesilaos/denote#503]
I think the above function might have a bug:

I have the start note open and files marked in dired. This is what I keep getting:

```pre
Create links at point in 20241222T101941--start.org? (y or n) y
funcall-interactively: Wrong type argument: char-or-string-p, ("- [[denote:20241222T102720][The setf Macro in elisp]]
```

P.S.: Merry Christmas and thanks a lot for the great package :-D

EDIT: fixed a typo

**Comment by protesilaos** [comment]
Thank you! It must have been a faulty alias definition. I just made the change.

> P.S.: Merry Christmas and thanks a lot for the great package :-D

Merry Christmas and a Happy New Year!

**Comment by protesilaos** [comment]
No, actually there is more. Let me check...

**Comment by protesilaos** [comment]
Okay, I think we are done, but I will keep the issue open to let you confirm it on your end.

**Comment by oliverepper** [comment]
Hi Prot!

Thanks for that super quick fix! I can confirm that it does work now (8e8b43b3ccebd57f932e0a1aa2be3180f0f1e4ba) with ordinary denote notes marked in dired. There's some weirdness, though:

If the selected files are "attachment" files, like 20241219T161602--some-picture__screenshot.jpg there is another error:

"progn: No note files to link to"

Maybe that hits another edge-case?

**Comment by protesilaos** [comment]
Thank you! I just made the change. I think this covers it.

**Comment by oliverepper** [comment]
Perfect!
