### ISSUE TITLE
`denote-org-capture` creates incorrect date front matter when `date` is in `denote-prompts`

### ISSUE THREAD

**Issue by jeffvalk** [protesilaos/denote#504]
When `'date` is in `denote-prompts`, `denote-org-capture` incorrectly uses the current date rather than the user-specified one to populate the front matter `date` attribute. The user-specified date is correctly used to create the new note's identifier however.

### Steps to reproduce with `emacs -Q`:

```elisp
(require 'denote "path/to/denote-3.1.0/denote.el")

;; Prompt for date
(setq denote-prompts '(title keywords date))

;; example org-capture template from manual
(with-eval-after-load 'org-capture
  (add-to-list 'org-capture-templates
               '("n" "New note (with Denote)" plain
                 (file denote-last-path)
                 #'denote-org-capture
                 :no-save t
                 :immediate-finish nil
                 :kill-buffer t
                 :jump-to-captured t)))

```

1. For the sake of the result below, assume the following test actions are performed at 2024-12-25 12:00.
2. `M-x org-capture` ; and select "New note (with Denote)"
3. At the title prompt, enter: `A note title`
4. At the keywords prompt, enter: `keyword1,keyword2`
5. At the date prompt, enter: `2022-06-14 14:30`

### Expected result

```org
#+title:      A note title
#+date:       [2022-06-14 Tue 14:30]     <-- User-specified date
#+filetags:   :keyword1:keyword2:
#+identifier: 20220614T143000            <-- User-specified date
```

### Actual result

```org
#+title:      A note title
#+date:       [2024-12-25 Wed 12:00]     <-- Current date (should be the user-specified date)
#+filetags:   :keyword1:keyword2:
#+identifier: 20220614T143000            <-- User-specified date
```

**Comment by protesilaos** [comment]
Thank you @jeffvalk for the detailed report!

I cannot reproduce this bug on my end. I tried it with my setup as well as in `emacs -Q`. Here are the results.

## emacs -Q

![2024-12-27_10:48:13_1863x1041](https://github.com/user-attachments/assets/d7ae1ab4-11ee-48e5-832a-052609c94783)

## My configuration

![2024-12-27_10:49:09_1863x1041](https://github.com/user-attachments/assets/d865b15d-759f-4289-9729-bb3bad218e87)

## Relevant for my configuration

```elisp
(emacs-version)
;; => "GNU Emacs 31.0.50 (build 11, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0) of 2024-12-17"

(org-version)
;; => "9.7.11"

system-configuration-options
;; => "--prefix=/usr/local --with-x-toolkit=gtk3 --disable-gc-mark-trace --with-native-compilation=aot --without-gif --without-tiff --without-selinux --without-xinput2 --without-gpm --without-compress-install --without-xft --with-cairo --with-harfbuzz --with-tree-sitter=ifavailable --without-gsettings --without-gconf"
```

**Comment by jeffvalk** [comment]
That's quite strange... I tried it again with both my configuration and `emacs -Q` just now, and both behave the same as the original report:

```org
#+title:      A note title
#+date:       [2024-12-27 Fri 10:03]  <-- Current date, not the one from the prompt
#+filetags:   :k1:k2:
#+identifier: 20220614T143000
```

Here are my current configuration details:

```elisp
(emacs-version)
;; => "GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.2)"

(org-version)
;; => "9.6.15"

system-configuration-options
;; => "--sysconfdir=/etc --prefix=/usr --libexecdir=/usr/lib --with-tree-sitter --localstatedir=/var --with-cairo --disable-build-details --with-harfbuzz --with-libsystemd --with-modules --with-x-toolkit=gtk3 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/emacs/src=/usr/src/debug/emacs -flto=auto' 'LDFLAGS=-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now          -Wl,-z,pack-relative-relocs -flto=auto'"
```

Could someone else give this a try to verify?

**Comment by jeffvalk** [comment]
@protesilaos I cloned the repo and tried this at 9b2cf810542fe20148c16571b18bd3d47be3cb13 rather than with the current ELPA release (v3.1). I get the correct behavior you show above. Apparently this was fixed in `main` before I noticed it. How excellent! :smile:

**Comment by protesilaos** [comment]
Very well!
