### ISSUE TITLE
Line highlighting and alt-syntax effects lost after `modus-themes-toggle`

### ISSUE THREAD

**Issue by felipebalbi** [protesilaos/denote#56]
Hi @protesilaos,

After configuring modus themes to my liking, I noticed that the effects of `modus-themes-hl-line` and `modus-themes-syntax` are, apparently, lost after a call to `modus-themes-toggle`.

Here's what a piece of source code looks as soon as `modus-operandi` loads during `emacs` initialization:

![before](https://user-images.githubusercontent.com/45936891/179480107-eb95eecb-20ad-49cd-b682-8b913054caf5.png)

And after calling `modus-themes-toggle` twice:

![after](https://user-images.githubusercontent.com/45936891/179480330-8292a091-aacc-46f2-b1fa-6b756f4277f1.png)

Note that the effect of `intense` was lost in `modus-themes-hl-line` and, similarly, the effect of `alt-syntax` is gone from source code comments. I'm happy to test anything you want me to test, however when running the same configuration (quoted at the end of this report) on top of clean `emacs` (with `emacs -Q`), then `alt-syntax` and `intense` don't even have any effect at all.

Full configuration:

```lisp
(use-package modus-themes
  :custom
  (modus-themes-bold-constructs t)
  (modus-themes-fringes 'subtle)
  (modus-themes-hl-line '(accented intense))
  (modus-themes-italic-constructs t)
  (modus-themes-mixed-fonts t)
  (modus-themes-mode-line '(borderless))
  (modus-themes-org-blocks 'tinted-background)
  (modus-themes-paren-match '(intense bold))
  (modus-themes-prompts '(bold intense))
  (modus-themes-region '(bg-only accented))
  (modus-themes-scale-headings t)
  (modus-themes-syntax '(alt-syntax))
  (modus-themes-subtle-line-numbers t)
  (modus-themes-tabs-accented t)

  (modus-themes-completions
   '((matches . (extrabold background intense))
     (selection . (semibold accented intense))
     (popup . (accented))))

  (modus-themes-headings
   '((1 . (rainbow overline background 1.4))
     (2 . (rainbow background 1.3))
     (3 . (rainbow bold 1.2))
     (t . (semilight 1.1))))

   :config
   (load-theme 'modus-operandi t)

   :bind ("<f5>" . modus-themes-toggle))
```

UPDATE: I just noticed that pretty much every color changes. It looks like `alt-syntax` is lost. I'll confirm the colors being used later today and post a new comment

**Comment by felipebalbi** [comment]
I think this was a problem on my end. My `use-package` had `always-defer` set to `t`. After including `:defer nil` on my `modus-themes` config, I see the same colors always being used. But they look like the second screenshot above. Shouldn't `alt-syntax` use different colors for comments?

**Comment by protesilaos** [comment]
Hello @felipebalbi!

In the first screenshot you share, it is the default theme.  In the second it is `modus-operandi`.  Maybe that is the problem?

The `modus-themes-syntax` option changes comments to a more yellowish hue if you include `yellow-comments` in the list of properties.  Check the doc string of `modus-themes-syntax` for all available properties.

So it would be like this:

```elisp
(modus-themes-syntax '(yellow-comments))
```

If you want the `alt-syntax` as well, then this:

```elisp
(modus-themes-syntax '(yellow-comments alt-synatax))
```

The order in which the properties appear does not matter.

**Comment by protesilaos** [comment]
I just realised this is the repo of `denote`, not the `modus-themes`.  No worries.

**Comment by felipebalbi** [comment]
Well, let me close the issue, then. I should've checked the URL before hand. In any case, this seems to be a non-issue :-)
