### ISSUE TITLE
Make denote more compatible with non-ascii charactors

### ISSUE THREAD

**Issue by pRot0ta1p** [protesilaos/denote#57]
Currently `denote-faces--file-name-regexp` only recognize ascii title and keywords, can we change it to make it recognize non-ascii charactors? 

Some thing like:
```elisp
(defvar denote-faces--file-name-regexp
  (concat "\\(?1:[0-9]\\{8\\}\\)\\(?2:T[0-9]\\{6\\}\\)"
          "\\(?:\\(?3:--\\)\\(?4:[[:word:]_-]*\\)\\)?"
          "\\(?:\\(?5:__\\)\\(?6:[[:word:]_-]*\\)\\)?"
          "\\(?7:\\..*\\)?$"))
```
can match non-ascii charactors except punctuations.

And maybe also set the value of `denote--punctuation-regexp` to `[[:punct:]]` to make denote aware of non-ascii punctuations?

**Comment by pRot0ta1p** [comment]
Ok I did some reading and test, I think both `[:word:]` and `[:alnum:]` will suffice while `[:word:]` might be the safer option.
The description of `[:word:]` or `\w` is a little unclear

> Word constituents: ‘w’
>      Parts of words in human languages.  These are typically used in
>      variable and command names in programs.  All upper- and lower-case
>      letters, and the digits, are typically word constituents.
 
but when  invoke `describe-char` on a ASCII letter or multi-byte letter, it shows`syntax: w 	which means: word` so I guess Emacs might prefer `[:word:]`...

`[:alpha:]` however won't match digits, it only match characters.

Punctuation is kinda tricky, since Emacs' regexp is consumable, one can't match the same char twice in one regexp, something that match all punctuation but not `-` can't represent by a single regexp.

My suggestion is either make `denote--punctuation-regexp` customizable to allow user append any character they want, or change the logic so that it match all punctuation except for characters listed in say `denote--punctuation-reserved-regexp`.

**Comment by pRot0ta1p** [comment]
Yes the patch works, I can now remove full width punctuations simply by some thing like this:
```emacs-lisp
(setq denote-punctuation-excluded
      "[『』〖〗｛｝「」【】〔〕［］（）《》〈〉«»！＃￥％…＆＂＇＊，。；：、？—]*")
```

**Comment by protesilaos** [comment]
Thank you!  I just pushed the change:

```
  commit fb534987cef774a6e8b1584630bf019556db3d8f
  Author: Protesilaos Stavrou <info@protesilaos.com>
  Date:   Wed Jul 20 07:16:32 2022 +0300
  
      Add variable to extend "illegal" punctuation
      
      This is to allow users to omit non-ascii characters from file names.
      
      Thanks to pRot0ta1p for the feedback in issue 57 over at the GitHub
      mirror: <https://github.com/protesilaos/denote/issues/57>.
      
      Example based on the input of pRot0ta1p:
      
          (setq denote-punctuation-excluded-extra-regexp
                "[『』〖〗｛｝「」【】〔〕［］（）《》〈〉«»！＃￥％…＆＂＇＊，。；：、？—]*")
  
   denote.el | 11 ++++++++++-
   1 file changed, 10 insertions(+), 1 deletion(-)
```

I wrote this for the variable, so that we keep it in mind if a robust
solution comes up:

```elisp
(defvar denote-punctuation-excluded-extra-regexp nil
  "Additional punctuation that is removed from file names.
This variable is for advanced users who need to extend the
`denote--punctuation-regexp'.  Once we have a better
understanding of what we should be omitting, we will update
things accordingly.")
```

**Comment by pRot0ta1p** [comment]
Thanks! That's one problem solved, what should we do with `denote-faces--file-name-regexp` ? Change it to a defvar to test it out before we figure out the perfect regexp?

**Comment by protesilaos** [comment]
It already is a defvar.  But maybe you mean we should follow the same approach of concating what we have with a user-defined variable?  I am okay with that.  Just asking to be sure.

**Comment by pRot0ta1p** [comment]
Oops, sorry I didn't check the source code refore reply.
I'm ok with what it is now, the definiton of `denote-faces--file-name-regexp` is clear and simple, user who want to hack it should have no problem.

Close this issue for now, in case there are any breakage I will report to you. Thanks again.

**Comment by protesilaos** [comment]
You are welcome!  Please let me know how it goes.
