### ISSUE TITLE
consider some kind of interoperability with Karl Voits tools

### ISSUE THREAD

**Issue by ginabythebay** [protesilaos/denote#59]
Hi!

I find myself intrigued with denote and wanted to mention the suite of tools that Karl Voit has put together that seem to have a very similar philosophy about file naming, dates, and tags.  He describes it here:   https://github.com/novoid/filetags#why

I'm not sure what exactly I am suggesting you do here, but wanted to point out the tools in case you are not familiar.  It seems like denote and his tools are almost, but not quite compatible (e.g. he separates his tags with spaces).

**Comment by protesilaos** [comment]
Hello @ginabythebay!

I will need to check it out.  I am happy to help with such integration if it is possible.

Spaces are awkward with a generic shell.  This is why Denote's file names are always hyphenated (and why certain characters are omitted from the file name).  I know this is not a problem for Emacs, but the idea is to think long-term about accessing those files from environments where Emacs is not available.

**Comment by ginabythebay** [comment]
Yeah I find spaces in file names annoying especially when I am trying to using find with xargs. At the same time, some kind of agreement about the file name format would make both tools more useful I think

**Comment by protesilaos** [comment]
> Yeah I find spaces in file names annoying especially when I am trying to using find with xargs.

They are just a hassle, in my experience.

> At the same time, some kind of agreement about the file name format would make both tools more useful I think

I took a look.  While I share the sentiment, I don't think it is possible to have a common scheme.  The differences cannot be reconciled (this is not to say that Denote is better---just a stylistic difference).

The README includes this:

```
(<ISO date/time stamp>)?(?<descriptive file name>)?( -- <list of tags separated by spaces>)?.<file extension>
```

Which looks like:

```
2013-05-09T16.17 file name with time stamp -- tag3.csv
```

The Denote equivalent would be:

```
20130509T161700--file-name-with-time-stamp__tag3.csv
```

We have a `--` delimiter between the identifier (date+time) and the title.  The identifier must always include seconds.  We then have a `__` delimiter between the title and the tags.  There can be no spaces in the file name.  Everything is explained at length in the manual: <https://protesilaos.com/emacs/denote#h:4e9c7512-84dc-4dfb-9fa9-e15d51178e5d>.

Am I misreading this?  Maybe you still think there is a way to make the two schemes compatible?

**Comment by ginabythebay** [comment]
I believe you are reading it correctly.  I think that there are many potential ways to make the two pieces of software compatible but it would require a change in at least one of them.

**Comment by protesilaos** [comment]
> I think that there are many potential ways to make the two pieces of software compatible but it would require a change in at least one of them.

In that case I think we have reached a dead end.  Karl would be justified not to make such drastic changes to an established project, while I have good reasons not to modify Denote's file-naming scheme.

I am thus closing this.  Thank you for your time!
