### ISSUE TITLE
Fontification in dired buffer fails if name contains non [0-9A-Za-z-] character

### ISSUE THREAD

**Issue by hpgisler** [protesilaos/denote#61]
A file with name:
```20220702T230825--intervention-des-simulations-schöpfers-macht-diesen-erkennbar__phantasy_philosophy.org```

(note the German character ```ö``` in the word ```Schöpfer```), 
fontification fails in ```denote-dired-mode'.

I.e. the regexp should be modified (negated) to include basically all characters, but '_', to support non ASCII letters as well.

**Comment by protesilaos** [comment]
Hello @hpgisler!

Coincidentally, we are having a discussion about the same topic on the mailing list: https://lists.sr.ht/~protesilaos/denote/%3C2273b3b1-344c-6c6e-3ab6-a227b6bc3721%40eh-is.de%3E

Copying the relevant part of what I wrote:

> We basically need to tweak the 'denote-faces--file-name-regexp', specifically groups 4 and 6.  Though I am not sure exactly which character class we should include.
> 
> Read the Elisp manual by evaluating:
> 
>     (info "(elisp) Char Classes")
> 
> My guess is either [:alpha:] or a combination of [:ascii:] and [:nonascii:] plus the numbers.

Do you think that is the right approach or we should simplify it as you suggest?  Also, we technically downcase the title so the current regexp is not correct anyway.

**Comment by protesilaos** [comment]
This works for me:

```elisp
(defvar denote-faces--file-name-regexp
  (concat "\\(?1:[0-9]\\{8\\}\\)\\(?2:T[0-9]\\{6\\}\\)"
          "\\(?:\\(?3:--\\)\\(?4:[[:alnum:]-]*\\)\\)?"
          "\\(?:\\(?5:__\\)\\(?6:[[:alnum:]_-]*\\)\\)?"
          "\\(?7:\\..*\\)?$")
  "Regexp of file names for fontification.")

(defconst denote-faces-file-name-keywords
  `((,(concat " " denote-faces--file-name-regexp)
     (1 'denote-faces-date)
     (2 'denote-faces-time)
     (3 'denote-faces-delimiter nil t)
     (4 'denote-faces-title nil t)
     (5 'denote-faces-delimiter nil t)
     (6 'denote-faces-keywords nil t)
     (7 'denote-faces-extension nil t )))
  "Keywords for fontification of file names.")
```

Kill the dired buffer and open it again.

**Comment by hpgisler** [comment]
Yes, your solution works; thank you.

I've tried the following, which also seems to work;
however, your's more readable, I think 
and perhaps it is better to not 'open up' the number of 
allowed characters to much...

```lisp
(defvar denote-faces--file-name-regexp
  (concat "\\(?1:[0-9]\\{8\\}\\)\\(?2:T[0-9]\\{6\\}\\)"
          "\\(?:\\(?3:--\\)\\(?4:[^_]*\\)\\)?"
          "\\(?:\\(?5:__\\)\\(?6:[^.]*\\)\\)?"
          "\\(?7:\\..*\\)?$")
  "Regexp of file names for fontification.")
```

**Comment by protesilaos** [comment]
Thank you for the feedback!  Based on it, I pushed my change.  Also tweaked some other variables to make them compatible with this.

I will prepare a new release in the coming days.  Maybe tomorrow or the day after, depending on how things go.

Closing this issue now.
