### ISSUE TITLE
Is it possible to not replace tags when renaming from dired?

### ISSUE THREAD

**Issue by atanasj** [protesilaos/denote#87]
I have a number of notes that I have migrated from evernote and have reformatted the `yaml` header to be as close as possible to the `denote` format. However, I do not want to change the existing tags in the `yaml`. Can I skip over them without changing or manually selecting them from the minibuffer?

Ideally, I would want these tags to persist… Is this possible?

**Comment by protesilaos** [comment]
Hello @atanasj!

If I understand this correctly: you want the front matter to stay as-is and have the file name be renamed according to that data, right?

If so, check the command `denote-rename-file-using-front-matter`.  Documented here: https://protesilaos.com/emacs/denote#h:3ab08ff4-81fa-4d24-99cb-79f97c13a373

[ Try it with a test file before operating on your actual data. ]

**Comment by atanasj** [comment]
Thanks for that, I did try that, but it did not work. I get the message:

`denote-rename-file-using-front-matter: No front matter for title and/or keywords`

The format of the `yaml` front matter looks like below: 

```md
---
date: 2017-07-25T05:38:27+0000
identifier: "20170725T053827"

title: "IASP - Special Interest Group: Suicidal Behaviour in Adolescents"
tags: ["Treatment"]
url: https://iasp.info/suicidal_behaviour_in_adolescents.php
source: web.clip

---
```

**Comment by protesilaos** [comment]
Yes, I forgot to mention that the file name must already have an identifier.  It should, at the very least, be named `20170725T053827.md`.

We will need to update the command to work on any file that ends with one of our supported extensions.  Will look into it now.

**Comment by atanasj** [comment]
Okay… I could probably fudge something on the command line to rename using the identifier, but if it is built in, all the better! Thanks for being so responsive!

**Comment by protesilaos** [comment]
Yes, it should be provided by Denote.  There is no reason to keep the current restriction.

**Comment by atanasj** [comment]
That would be awesome!

**Comment by protesilaos** [comment]
@atanasj You are pulling directly from git, right?  If so, please check the latest commit `1bdd0eb`.  I just tried it with sample.md and valid front matter and got the expected renamed name.

**Comment by atanasj** [comment]
@protesilaos, yes! That works as expected. 😄

**Comment by protesilaos** [comment]
Very well!  Let's keep this open for a while longer.  There may be some more refinements to be made.  Will keep you posted.

**Comment by atanasj** [comment]
Okay… I seem to be having problems in marking and bulk renaming in `dired`.... I have `ranger` installed, so not sure if this is causing an issue... However, I disabled the `ranger` and it still did not work. The message I get is:

```
No marked files; aborting
```

Could it be something with my setup? I am also using `evil`, however the problem persists in `emacs-mode` within `doomemacs`.

**Comment by protesilaos** [comment]
Which command did you use?  The error most likely is internal to Denote.

**Comment by atanasj** [comment]
I am using `denote-dired-rename-marked-files-using-front-matter`

**Comment by protesilaos** [comment]
I just pushed a change.   It basically relaxes the condition of what counts as a writable file.  Same idea with what I did for the single file renaming.  Please try commit `46f123c`.

**Comment by atanasj** [comment]
WORKING! Nice job! This solves the issue for me, so I'll gratefully close! 😄

**Comment by protesilaos** [comment]
Very well!  Thanks again for your feedback!
