### ISSUE TITLE
Multiword keyword and fontification issue

### ISSUE THREAD

**Issue by svnsbck** [protesilaos/denote#9]
Hi Prot!
The latest change with the keywords is nice and certainly adds clarity, but somehow the fontification in Dired doesn't correctly work, or at the least it doesn't on my end:

![Screenshot from 2022-06-11 16-43-35](https://user-images.githubusercontent.com/8381669/173190608-3cf9043e-ae08-4ee7-96d8-9dbd19fc59f6.png)

Entries with multiple keywords work as expected.

Of course I might have messed up something myself. Always a possibility :-)

**Comment by protesilaos** [comment]
Hello @svnsbck!  The fault is not yours.  Just fixed it in commit d83c166.  Please give it a try.

**Comment by svnsbck** [comment]
Great! Just gave it a try and it works now.
 
![Screenshot from 2022-06-11 18-09-39](https://user-images.githubusercontent.com/8381669/173193609-7d29cc78-684c-477f-b3ab-265abcb0a0c4.png)

One idea that came to mind is, if the separator (ie. the underscore) between the keywords could have the same color, the light-grey, as the other separators. Surely it is only a minor difference but I think it would visually clarify that its two different keywords and not just one very long one which contains underscores.

I don't know if that's even possible though.

**Comment by protesilaos** [comment]
> One idea that came to mind is, if the separator (ie. the underscore)
> between the keywords could have the same color, the light-grey, as the
> other separators. Surely it is only a minor difference but I think it
> would visually clarify that its two different keywords and not just
> one very long one which contains underscores.

Good idea!  Done in commit 142b628.  I might still tweak it a bit further.

**Comment by protesilaos** [comment]
Also adjusted the grey colour of the field delimiters.  We now have these:

![Screenshot from 2022-06-11 18-46-05](https://user-images.githubusercontent.com/12828033/173194993-21373e70-df42-4b34-9121-93d99e621c1f.png)

![Screenshot from 2022-06-11 18-45-14](https://user-images.githubusercontent.com/12828033/173194992-6964fdca-4eb6-4a47-a64c-c68edc34b101.png)

**Comment by svnsbck** [comment]
Nice! I think that looks great and it is visually very clear!

Jun 11, 2022 18:47:46 Protesilaos Stavrou ***@***.***>:

**Comment by protesilaos** [comment]
Thanks!  Closing now.
