### ISSUE TITLE
Using denote as journal or diary

### ISSUE THREAD

**Issue by atanasj** [protesilaos/denote#95]
The online manual provides an example of how to use `denote` as a journal... Is there a way to make it function my similar to `org-journal`, whereby a new note can be created for a day, week, etc., and then each entry is appended to the bottom with the time stamp as a sub-header? I've tried to hack something together, by my `elisp` is not very good... I thought it might be combination of the stuff below, but couldn't get it working…

```elisp
;; from the manual
(defun my-denote-journal ()
  "Create an entry tagged 'journal' with the date as its title."
  (interactive)
  (denote
   (format-time-string "%A %e %B %Y") ; format like Tuesday 14 June 2022
   '("journal"))) ; multiple keywords are a list of strings: '("one" "two")

(with-eval-after-load 'org-capture
  (add-to-list 'org-capture-templates
               '("J" "New Journal (with Denote)" plain
                 (file+headline denote-last-path (format-time-string "%A %e %B %Y"))
                 #'denote-org-capture
                 :no-save t
                 :immediate-finish nil
                 :kill-buffer t
                 :jump-to-captured t
                 :prepend t)))
```

**Comment by protesilaos** [comment]
Hello @atanasj!

Denote is designed to work with a one-file-per-note workflow.  All the Denote commands which pertain to new note creation expect a file path to be returned.  They then use `find-file` on that path.

Denote does not have the means to add to an existing file.  That is an Org-specific feature.  Also, Denote does not have a date picker the way Org does.  That too is Org-specific.  In both cases the code is not trivial.  Just check the implementation of `org-read-date` to see what I mean.

Perhaps there is a way to hack this together, though it would still not make for an optimal choice, based on the requirements you have described.  I then wonder why not use `org-journal` directly?

I personally use Denote for journaling.  Each entry has a `journal` keyword (among others), which makes it easy to filter them from the rest of the notes.  The individual files also make it possible to share a file when I need to (happens from time-to-time with people I can trust).

**Comment by jeanphilippegg** [comment]
Hello @atanasj !

I pasted below the `my-denote-journal` command I have in my config. Maybe you can adapt it to your specific needs.

- `C-c n j` creates a new note for today if none already exists. If it already exists, it opens today's note.
- `C-c n J` prompts for the date of the note you want to edit (or create).

The code:

```elisp
(defun first-file-with-substring (dir substring)
  "Return the first file in DIR containing SUBSTRING.
Return nil if there is no files with SUBSTRING in its name."
  (let ((files (file-expand-wildcards (concat dir "*" substring "*"))))
    (when (>= (length files) 1)
      (car files))))

(defun my-denote-journal (&optional date-prompt)
  "Add or modify today's journal entry.

With prefix arg of if DATE-PROMPT is non-nil, prompt for a date."
  (interactive "P")
  (let* ((denote-directory (expand-file-name "~/some-directory/"))  ; I don't keep them in the same place as my other notes.
         (denote-file-type 'text)
         (time (get-time date-prompt))
         (title (format-time-string "%A %-d %B %Y" time))
         (file-name-string (concat (replace-regexp-in-string " " "-" (downcase title)) "__journal"))
         (existing-journal-entry (first-file-with-substring (denote-directory) file-name-string)))
    (if existing-journal-entry
        (find-file existing-journal-entry)
      (denote title '("journal")))))

(global-set-key (kbd "C-c n j") #'my-denote-journal)
(global-set-key (kbd "C-c n J") #'(lambda () (interactive) (my-denote-journal t)))
```

Adding a timestamp at the end of an existing note can be done by adding a few line in the `if` condition in `my-denote-journal`.

Hope it can be useful to you!

**Comment by jeanphilippegg** [comment]
Hello @atanasj !

I pasted below the `my-denote-journal` command I have in my config. Maybe you can adapt it to your specific needs.

- `C-c n j` creates a new note for today if none already exists. If it already exists, it opens today's note.
- `C-c n J` prompts for the date of the note you want to edit (or create).

The code:

```elisp
(defun first-file-with-substring (dir substring)
  "Return the first file in DIR containing SUBSTRING.
Return nil if there is no files with SUBSTRING in its name."
  (let ((files (file-expand-wildcards (concat dir "*" substring "*"))))
    (when (>= (length files) 1)
      (car files))))

(defun my-denote-journal (&optional date-prompt)
  "Add or modify today's journal entry.

With prefix arg of if DATE-PROMPT is non-nil, prompt for a date."
  (interactive "P")
  (let* ((denote-directory (expand-file-name "~/some-directory/"))  ; I don't keep them in the same place as my other notes.
         (denote-file-type 'text)
         (time (org-read-date nil t))
         (title (format-time-string "%A %-d %B %Y" time))
         (file-name-string (concat (replace-regexp-in-string " " "-" (downcase title)) "__journal"))
         (existing-journal-entry (first-file-with-substring (denote-directory) file-name-string)))
    (if existing-journal-entry
        (find-file existing-journal-entry)
      (denote title '("journal")))))

(global-set-key (kbd "C-c n j") #'my-denote-journal)
(global-set-key (kbd "C-c n J") #'(lambda () (interactive) (my-denote-journal t)))
```

Adding a timestamp at the end of an existing note can be done by adding a few line in the `if` condition in `my-denote-journal`.

Hope it can be useful to you!

**Comment by jeanphilippegg** [comment]
Hello @atanasj !

I pasted below the `my-denote-journal` command I have in my config. Maybe you can adapt it to your specific needs.

- `C-c n j` creates a new note for today if none already exists. If it already exists, it opens today's note.
- `C-c n J` prompts for the date of the note you want to edit (or create).

The code:

```elisp
(defun first-file-with-substring (dir substring)
  "Return the first file in DIR containing SUBSTRING.
Return nil if there is no files with SUBSTRING in its name."
  (let ((files (file-expand-wildcards (concat dir "*" substring "*"))))
    (when (>= (length files) 1)
      (car files))))

(defun my-denote-journal (&optional date-prompt)
  "Add or modify today's journal entry.

With prefix arg of if DATE-PROMPT is non-nil, prompt for a date."
  (interactive "P")
  (let* ((denote-directory (expand-file-name "~/some-directory/"))  ; I don't keep them in the same place as my other notes.
         (denote-file-type 'text)
         (time (org-read-date nil t))
         (title (format-time-string "%A %-d %B %Y" time))
         (file-name-string (concat (replace-regexp-in-string " " "-" (downcase title)) "__journal"))
         (existing-journal-entry (first-file-with-substring (denote-directory) file-name-string)))
    (if existing-journal-entry
        (find-file existing-journal-entry)
      (denote title '("journal")))))

(global-set-key (kbd "C-c n j") #'my-denote-journal)
(global-set-key (kbd "C-c n J") #'(lambda () (interactive) (my-denote-journal t)))
```

Adding a timestamp at the end of an existing note can be done by adding a few line in the `if` condition in `my-denote-journal`.

Hope it can be useful to you!

**Comment by protesilaos** [comment]
@jeanphilippegg Do you think we should add this general feature to denote.el?  My concern is that once we get into the task of appending to a file, we will have to consider all sorts of edge cases.  You already know perfectly well from the renaming facility how tricky those things get.

Also, about `org-read-date`: we had this discussion before but maybe we can provide it as an opt-in feature?  It seems straightforward and shouldn't complicate things on our end (I think).

**Comment by jeanphilippegg** [comment]
> @jeanphilippegg Do you think we should add this general feature to denote.el? My concern is that once we get into the task of appending to a file, we will have to consider all sorts of edge cases. You already know perfectly well from the renaming facility how tricky those things get.

I am not sure about adding it in `denote.el`. It could be one more example in the manual if you want. But I think you are right to be concerned about all other use-cases that could be supported if we start doing that. We could wait to see if there is a more precise need in the future.

> Also, about `org-read-date`: we had this discussion before but maybe we can provide it as an opt-in feature? It seems straightforward and shouldn't complicate things on our end (I think).

Yes, maybe we could. Are you thinking of `(setq denote-date-prompt-use-org-read-date t)`?

**Comment by protesilaos** [comment]
> It could be one more example in the manual if you want.

Yes, that would be better at this stage.  Though I prefer not to document it right now as we might think of a better solution.

> Yes, maybe we could. Are you thinking of `(setq denote-date-prompt-use-org-read-date t)`?

Indeed! My only concern is to make Org optional so that the user who does not load Org is not affected by this.

**Comment by atanasj** [comment]
That's excellent guys, thanks. You're super helpful and responsive. I'm happy to close as this is no longer an issues. 😄

**Comment by protesilaos** [comment]
You are welcome!
