### ISSUE TITLE
Is there a way to add link title for none-denote-type files

### ISSUE THREAD

**Issue by nowislewis** [protesilaos/denote#98]
Hello Protesilaos, and anyone who loves denote. This may be a bit long-winded question, but please allow me to express the origin of the problem.

One of the features I like about denote is that as long as I add a link, such as “b”, to another file in a note file, such as “a”, and as long as “b” is in denote-dir, no matter how I move the “b” file to any subfolder, “b” would always be found  and open accurately and quickly.

I love the convenience and wonder if there is a way to manage other files with the denote solution.

I first used denote-rename to rename a xxx.pdf file, (denote-rename is a very useful method) and got, “20220820T211207--test-pdf__test.pdf”. But when I use denote-link to insert this pdf into a note file, I can only get the name [[denote:20220820T211207]], then I click this link, denote quickly finds and opens the pdf, even after the file has been moved to another subdir

My question here is whether I can make this link add a reasonable description and a file identifier,such as "[[denote:xxxx][pdf:test]]"  in org mode so that I can fully rely on denote to efficiently manage all my files.

Have a good day

**Comment by protesilaos** [comment]
Hello @nowislewis!  There have been changes on this front in the current development version.  One of them is the ability to add links to "non-note" files, such as PDFs.  The other is to extract the `TITLE` component from the file name and use it as the description of the link.

This will be available in version `0.6.0`.  I expect to have this done in about a week from now.

**Comment by nowislewis** [comment]
Fantastic, I will try it and look forward to the new version.

**Comment by protesilaos** [comment]
If you do try it before the new version is out, please let me know what you think of it.  Feel welcome to re-open this issue.
